texchannels = {
	'png': {"": ""}, # default png UI icons
	'pAOTexture': {"": "AO"},
	# 'pAOTextureDetailBase': {"": ""},
	# 'pAOTextureDetailBlend': {"": ""},
	# 'pBaseColour2Texture': {"RGB": "", "A": ""},
	'pBaseColourTexture': {"RGB": "BC", "A": ""},
	'pBaseColourTexture1': {"RGB": "BC", "A": ""},
	# 'pBaseColourTexture2': {"RGB": "", "A": ""},
	# 'pBaseColourTexture3': {"RGB": "", "A": ""},
	# 'pBaseColourTexture4': {"RGB": "", "A": ""},
	# 'pBaseColourTextureDetailBase': {"RGB": "", "A": ""},
	# 'pBaseColourTextureDetailBlend': {"RGB": "", "A": ""},
	'pCavityRoughnessDielectricArray': {"R": "CA", "G": "RN", "B": "SP", "A": ""},
	'pCavitySmoothnessTexture': {"R": "CA", "G": "SM", "B": "", "A": "FO"},  # from PC1
	# 'pCoarseNoise': {"": ""},
	'pCustomisation_AOTexture': {"": "AO"},
	# 'pCustomisation_Channel1PatternTexture': {"": ""},
	# 'pCustomisation_Channel2PatternTexture': {"": ""},
	# 'pCustomisation_Channel3PatternTexture': {"": ""},
	# 'pCustomisation_Channel4PatternTexture': {"": ""},
	# 'pCustomisation_ChannelMasksTexture': {"": ""},
	# 'pCustomisation_HSVOffsetTexture': {"": ""},
	# 'pCustomisation_MasterMaskTexture': {"": ""},
	'pCustomisation_Value2Texture': {"": "DE_BC"},
	'pCustomisation_ValueTexture': {"": "TI_BC"}, # should be mixed with some color?
	'pDetailNormalTexture': {"RG": "NM"},
	'pDiffuseAlphaTexture': {"RGB": "BC", "A": "OP"},
	'pDiffuseArray': {"": "BC"},
	'pDiffuseTexture': {"RGB": "BC", "A": ""},
	'pEmissiveOpacityTexture': {"RGB": "EM", "A": "OP"},
	'pEmissiveTexture': {"": "EM"},
	'pFlexiColourMasksTexture': {"R": "F1", "G": "F2", "B": "F3", "A": "F4"},
	# 'pFoamTexture': {"": ""},
	# 'pFoamWhitewaterTex': {"": ""},
	# 'pFullScaleDiffuseAndSpecial': {"": ""},
	'pGradHeightArray': {"RG": "NM", "B": "HE", "A": ""},
	# 'pIBLTexture': {"": ""},
	# 'pIBLTextureB': {"": ""},
	# 'pIBLTextureFlowmap': {"": ""},
	# 'pIBLTextureFlowmapB': {"": ""},
	# 'pIBLTexturePhaseOffsetmap': {"": ""},
	# 'pIBLTexturePhaseOffsetmapB': {"": ""},
	# 'pLightSequenceTexture': {"": ""},
	# 'pLightSequence_ChannelMasksTexture': {"": ""},
	# 'pLightSequence_EmissiveMaskTexture': {"": ""},
	'pMacroDiffuse': {"": "DE"},
	# 'pMaskAOTextureUnique': {"": ""},
	'pMetalSmoothnessCavityOpacityTexture': {"R": "MT", "G": "SM", "B": "CA", "A": "OP"},  # from PC1
	'pMetalSmoothnessCavityTexture': {"R": "MT", "G": "SM", "B": "CA", "A": ""},  # from PC1
	# 'pMossBaseColourRoughnessPackedTexture': {"RGB": "", "A": ""},
	# 'pMossNormalTexture': {"": ""},
	# 'pMossVarianceTexture': {"": ""},
	'pNormal2Texture': {"": "NM"},
	'pNormalMapTextureUnique': {"RG": "NQ_NM", "B": "DM", "A": "NQ_AO"},
	'pNormalTexture': {"RGB": "NM", "A": ""},  # ?
	'pNormalTextureDetailBase': {"RG": "DE_NM"},  # Overlaid on pNormalMapTextureUnique
	'pNormalTextureDetailBlend': {"RG": "BL_NM"},  # Overlaid on pNormalTextureDetailBase
	'pOpacity': {"": "OP"},
	# 'pOpacity2': {"": ""},
	'pOpacityMap': {"": "OP"},
	'pOpacityTexture': {"": "OP"},
	# 'pPropertyTexture': {"": ""},
	'pRoughnessPacked2Texture': {"R": "MT", "G": "RN"},
	'pRoughnessPackedTexture': {"R": "MT", "G": "SP", "B": "RN", "A": "FO"},  # from JWE2
	# 'pRoughnessTexture': {"": ""},
	'pSmoothnessCavityFlexiColourMaskMasterTexture': {"R": "CA", "G": "SM", "B": "", "A": "FO"}, # from PC1, order not checked
	'pSpecularTexture': {"": "SP"},
	# 'pStriationTexture': {"": ""},
	'pTransmission': {"": "TR"},
	'pTransmissionTexture': {"": "TR"},
	# 'pTriplanarCustomisation_ValueTexture': {"": ""},
	# 'pTriplanar_BaseColourTexture': {"": ""},
	# 'pTriplanar_NormalTexture': {"": ""},
	# 'pTriplanar_RoughnessPackedTexture': {"R": "", "G": "", "B": "", "A": ""},
	# 'pWaterDetailNormalMapTexture': {"": ""},
	# 'pWaterDetailTextureGradient': {"": ""},
	# 'pWaterDetailTextureHeight': {"": ""},
	# 'pWaterFoamMapTexture': {"": ""},
	# 'pWaterHighFreqDetailNormalMap': {"": ""},
	# 'pWaterSimDataTexture': {"": ""},
	# 'pWaterfall_WaterFlowAndTimeOffsetMap': {"R": "", "G": "", "B": "", "A": ""},
	# 'pWaterfall_WaterFoamMaskMap': {"R": "", "G": "", "B": "", "A": ""},
	# 'pWaterfall_WaterNormalRoughnessMap': {"RGB": "", "A": ""},
	# 'pWaveFoamTexture': {"": ""},
}
