texchannels = {
	'png': {"": ""}, # default png UI icons
	'pAOTexture': {"": "AO"},
	# 'pAOTextureDetailBase': {"": ""},
	# 'pAOTextureDetailBlend': {"": ""},
	# 'pBaseColour2Texture': {"RGB": "", "A": ""},
	'pBaseColourTexture': {"RGB": "BC", "A": ""},
	# 'pBaseColourTexture1': {"RGB": "", "A": ""},
	# 'pBaseColourTexture2': {"RGB": "", "A": ""},
	# 'pBaseColourTexture3': {"RGB": "", "A": ""},
	# 'pBaseColourTexture4': {"RGB": "", "A": ""},
	# 'pBaseColourTextureDetailBase': {"RGB": "", "A": ""},
	# 'pBaseColourTextureDetailBlend': {"RGB": "", "A": ""},
	# 'pCavityRoughnessDielectricArray': {"R": "", "G": "", "B": "", "A": ""},
	'pCavitySmoothnessTexture': {"R": "CA", "G": "SM", "B": "", "A": "FO"},  # from PC1
	# 'pCoarseNoise': {"": ""},
	# 'pCustomisation_AOTexture': {"": ""},
	# 'pCustomisation_Channel1PatternTexture': {"": ""},
	# 'pCustomisation_Channel2PatternTexture': {"": ""},
	# 'pCustomisation_Channel3PatternTexture': {"": ""},
	# 'pCustomisation_Channel4PatternTexture': {"": ""},
	# 'pCustomisation_ChannelMasksTexture': {"": ""},
	# 'pCustomisation_HSVOffsetTexture': {"": ""},
	# 'pCustomisation_MasterMaskTexture': {"": ""},
	# 'pCustomisation_Value2Texture': {"": ""},
	# 'pCustomisation_ValueTexture': {"": ""},
	# 'pDetailNormalTexture': {"": ""},
	'pDiffuseAlphaTexture': {"RGB": "BC", "A": "OP"},
	# 'pDiffuseArray': {"": ""},
	'pDiffuseTexture': {"RGB": "BC", "A": ""},
	'pEmissiveOpacityTexture': {"RGB": "EM", "A": "OP"},
	'pEmissiveTexture': {"": "EM"},
	'pFlexiColourMasksTexture': {"R": "F1", "G": "F2", "B": "F3", "A": "F4"},
	# 'pFoamTexture': {"": ""},
	# 'pFoamWhitewaterTex': {"": ""},
	# 'pFullScaleDiffuseAndSpecial': {"": ""},
	# 'pGradHeightArray': {"RG": "", "B": "", "A": ""},
	# 'pIBLTexture': {"": ""},
	# 'pIBLTextureB': {"": ""},
	# 'pIBLTextureFlowmap': {"": ""},
	# 'pIBLTextureFlowmapB': {"": ""},
	# 'pIBLTexturePhaseOffsetmap': {"": ""},
	# 'pIBLTexturePhaseOffsetmapB': {"": ""},
	# 'pLightSequenceTexture': {"": ""},
	# 'pLightSequence_ChannelMasksTexture': {"": ""},
	# 'pLightSequence_EmissiveMaskTexture': {"": ""},
	# 'pMacroDiffuse': {"": ""},
	# 'pMaskAOTextureUnique': {"": ""},
	'pMetalSmoothnessCavityOpacityTexture': {"R": "MT", "G": "SM", "B": "CA", "A": "OP"},  # from PC1
	'pMetalSmoothnessCavityTexture': {"R": "MT", "G": "SM", "B": "CA", "A": ""},  # from PC1
	# 'pMossBaseColourRoughnessPackedTexture': {"RGB": "", "A": ""},
	# 'pMossNormalTexture': {"": ""},
	# 'pMossVarianceTexture': {"": ""},
	# 'pNormal2Texture': {"": ""},
	# 'pNormalMapTextureUnique': {"RG": "", "B": "", "A": ""},
	'pNormalTexture': {"RGB": "NM", "A": ""},  # ?
	# 'pNormalTextureDetailBase': {"RG": "", "B": "", "A": ""},
	# 'pNormalTextureDetailBlend': {"RGB": "", "A": ""},
	'pOpacity': {"": "OP"},
	# 'pOpacity2': {"": ""},
	# 'pOpacityMap': {"": ""},
	# 'pOpacityTexture': {"": ""},
	# 'pPropertyTexture': {"": ""},
	# 'pRoughnessPacked2Texture': {"": ""},
	'pRoughnessPackedTexture': {"R": "MT", "G": "SP", "B": "RN", "A": "FO"},  # from JWE2
	# 'pRoughnessTexture': {"": ""},
	# 'pSmoothnessCavityFlexiColourMaskMasterTexture': {"": ""},
	'pSpecularTexture': {"": "SP"},
	# 'pStriationTexture': {"": ""},
	# 'pTransmission': {"": ""},
	# 'pTransmissionTexture': {"": ""},
	# 'pTriplanarCustomisation_ValueTexture': {"": ""},
	# 'pTriplanar_BaseColourTexture': {"": ""},
	# 'pTriplanar_NormalTexture': {"": ""},
	# 'pTriplanar_RoughnessPackedTexture': {"R": "", "G": "", "B": "", "A": ""},
	# 'pWaterDetailNormalMapTexture': {"": ""},
	# 'pWaterDetailTextureGradient': {"": ""},
	# 'pWaterDetailTextureHeight': {"": ""},
	# 'pWaterFoamMapTexture': {"": ""},
	# 'pWaterHighFreqDetailNormalMap': {"": ""},
	# 'pWaterSimDataTexture': {"": ""},
	# 'pWaterfall_WaterFlowAndTimeOffsetMap': {"R": "", "G": "", "B": "", "A": ""},
	# 'pWaterfall_WaterFoamMaskMap': {"R": "", "G": "", "B": "", "A": ""},
	# 'pWaterfall_WaterNormalRoughnessMap': {"RGB": "", "A": ""},
	# 'pWaveFoamTexture': {"": ""},
}
