texchannels = {
	# 'pAOTexture': {"": ""},
	# 'pAOTextureDetailBase': {"": ""},
	# 'pAOTextureDetailBlend': {"": ""},
	# 'pBaseColour2Texture': {"RGB": "", "A": ""},
	# 'pBaseColourTexture': {"RGB": "", "A": ""},
	# 'pBaseColourTexture1': {"RGB": "", "A": ""},
	# 'pBaseColourTexture2': {"RGB": "", "A": ""},
	# 'pBaseColourTexture3': {"RGB": "", "A": ""},
	# 'pBaseColourTexture4': {"RGB": "", "A": ""},
	# 'pBaseColourTextureDetailBase': {"RGB": "", "A": ""},
	# 'pBaseColourTextureDetailBlend': {"RGB": "", "A": ""},
	# 'pCavityRoughnessDielectricArray': {"R": "", "G": "", "B": "", "A": ""},
	# 'pCavitySmoothnessTexture': {"": ""},
	# 'pCoarseNoise': {"": ""},
	# 'pCustomisation_AOTexture': {"": ""},
	# 'pCustomisation_Channel1PatternTexture': {"": ""},
	# 'pCustomisation_Channel2PatternTexture': {"": ""},
	# 'pCustomisation_Channel3PatternTexture': {"": ""},
	# 'pCustomisation_Channel4PatternTexture': {"": ""},
	# 'pCustomisation_ChannelMasksTexture': {"": ""},
	# 'pCustomisation_HSVOffsetTexture': {"": ""},
	# 'pCustomisation_MasterMaskTexture': {"": ""},
	# 'pCustomisation_Value2Texture': {"": ""},
	# 'pCustomisation_ValueTexture': {"": ""},
	# 'pDetailNormalTexture': {"": ""},
	# 'pDiffuseAlphaTexture': {"RGB": "", "A": ""},
	# 'pDiffuseArray': {"": ""},
	# 'pDiffuseTexture': {"RGB": "", "A": ""},
	# 'pEmissiveOpacityTexture': {"": ""},
	# 'pEmissiveTexture': {"": ""},
	# 'pFlexiColourMasksTexture': {"R": "", "G": "", "B": "", "A": ""},
	# 'pFoamTexture': {"": ""},
	# 'pFoamWhitewaterTex': {"": ""},
	# 'pFullScaleDiffuseAndSpecial': {"": ""},
	# 'pGradHeightArray': {"RG": "", "B": "", "A": ""},
	# 'pIBLTexture': {"": ""},
	# 'pIBLTextureB': {"": ""},
	# 'pIBLTextureFlowmap': {"": ""},
	# 'pIBLTextureFlowmapB': {"": ""},
	# 'pIBLTexturePhaseOffsetmap': {"": ""},
	# 'pIBLTexturePhaseOffsetmapB': {"": ""},
	# 'pLightSequenceTexture': {"": ""},
	# 'pLightSequence_ChannelMasksTexture': {"": ""},
	# 'pLightSequence_EmissiveMaskTexture': {"": ""},
	# 'pMacroDiffuse': {"": ""},
	# 'pMaskAOTextureUnique': {"": ""},
	# 'pMetalSmoothnessCavityOpacityTexture': {"": ""},
	# 'pMetalSmoothnessCavityTexture': {"": ""},
	# 'pMossBaseColourRoughnessPackedTexture': {"RGB": "", "A": ""},
	# 'pMossNormalTexture': {"": ""},
	# 'pMossVarianceTexture': {"": ""},
	# 'pNormal2Texture': {"": ""},
	# 'pNormalMapTextureUnique': {"RG": "", "B": "", "A": ""},
	# 'pNormalTexture': {"RGB": "", "A": ""},
	# 'pNormalTextureDetailBase': {"RG": "", "B": "", "A": ""},
	# 'pNormalTextureDetailBlend': {"RGB": "", "A": ""},
	# 'pOpacity': {"": ""},
	# 'pOpacity2': {"": ""},
	# 'pOpacityMap': {"": ""},
	# 'pOpacityTexture': {"": ""},
	# 'pPropertyTexture': {"": ""},
	# 'pRoughnessPacked2Texture': {"": ""},
	# 'pRoughnessPackedTexture': {"R": "", "G": "", "B": "", "A": ""},
	# 'pRoughnessTexture': {"": ""},
	# 'pSmoothnessCavityFlexiColourMaskMasterTexture': {"": ""},
	# 'pSpecularTexture': {"": ""},
	# 'pStriationTexture': {"": ""},
	# 'pTransmission': {"": ""},
	# 'pTransmissionTexture': {"": ""},
	# 'pTriplanarCustomisation_ValueTexture': {"": ""},
	# 'pTriplanar_BaseColourTexture': {"": ""},
	# 'pTriplanar_NormalTexture': {"": ""},
	# 'pTriplanar_RoughnessPackedTexture': {"R": "", "G": "", "B": "", "A": ""},
	# 'pWaterDetailNormalMapTexture': {"": ""},
	# 'pWaterDetailTextureGradient': {"": ""},
	# 'pWaterDetailTextureHeight': {"": ""},
	# 'pWaterFoamMapTexture': {"": ""},
	# 'pWaterHighFreqDetailNormalMap': {"": ""},
	# 'pWaterSimDataTexture': {"": ""},
	# 'pWaterfall_WaterFlowAndTimeOffsetMap': {"R": "", "G": "", "B": "", "A": ""},
	# 'pWaterfall_WaterFoamMaskMap': {"R": "", "G": "", "B": "", "A": ""},
	# 'pWaterfall_WaterNormalRoughnessMap': {"RGB": "", "A": ""},
	# 'pWaveFoamTexture': {"": ""},
}
