texchannels = {
	# 'pAOSamplerTexture': {"": ""},
	# 'pBaseColourTexture': {"RGB": "", "A": ""},
	# 'pCavitySmoothnessArrayTexture': {"": ""},
	# 'pCavitySmoothnessOpacitySamplerTexture': {"R": "", "G": "", "B": "", "A": ""},
	# 'pCavitySmoothnessSamplerTexture': {"": ""},
	# 'pCoarseNoiseTexture': {"": ""},
	# 'pDiffuseArrayTexture': {"": ""},
	# 'pDiffuseOpacityTexture': {"": ""},
	'pDiffuseTexture': {"": "BC"},
	'pEmissiveOpacityTexture': {"RGB": "EM", "A": "OP"},
	'pEmissiveTexture': {"": "EM"},
	'pFlexiColourMasksSamplerTexture': {"R": "F1", "G": "F2", "B": "F3", "A": "F4"},
	# 'pFoamMapTexture': {"": ""},
	# 'pGradHeightArrayTexture': {"RG": "", "B": "", "A": ""},
	# 'pLightSequenceTexture': {"": ""},
	# 'pMacroDiffuseTexture': {"": ""},
	# 'pMetalSmoothnessCavityOpacitySamplerTexture': {"R": "", "G": "", "B": "", "A": ""},
	# 'pMetalSmoothnessCavitySamplerTexture': {"R": "", "G": "", "B": "", "A": ""},
	# 'pMist0Texture': {"": ""},
	# 'pMist1Texture': {"": ""},
	'pNormalTexture': {"RG": "NM"},
	'pOpacityMapTexture': {"": "OP"},
	# 'pRibbonMask1Texture': {"": ""},
	# 'pShoreWavesTexture': {"": ""},
	# 'pSkirtDiffuseArrayTexture': {"": ""},
	# 'pSkirtMaterialMaskTexture': {"": ""},
	# 'pSkirtNormalsTexture': {"": ""},
	# 'pSpecularArrayTexture': {"": ""},
	# 'pSpecularSamplerTexture': {"": ""},
	# 'pSpecularSmoothnessSamplerTexture': {"R": "", "G": "", "B": "", "A": ""},
	# 'pWaterDetailNormalMapTexture': {"": ""},
	# 'pWaterFoamMapTexture': {"": ""},
	# 'pWaterHighFreqDetailNormalMapTexture': {"": ""},
}
