attributes = {
    "gAnisotropicStrength": 0,
    "gBendStretchScale": 0,
    "gDirectionScale": 0,
    "gFinBrushScale": 0,
    "gFurExtension": 0,
    "gHeightStretchScale": 0,
    "gLodFade": 1,
    "gShellClumping": 0,
    "gShellUVStretchPower": 0,
    "gWetBrightness": 0,
    "gWetClumping": 0,
    "gWetFlattening": 0,
    "gWetHairBaseDirectionStrength": 0,
    "gWetHairDirectionStrength": 0,
    "gWetHairDownwardPush": 0,
    "pAASoftness": 0,
    "pAOTexCoordIndex": 5,
    "pAlbinoHeightScale": 0,
    "pAlphaClip": 0,
    "pAlphaTestRef": 0,
    "pAmbientTransmissionAmount": 0,
    "pAmbientTransmissionTint": 2,
    "pAngleDarkenPower": 0,
    "pAngles": 1,
    "pAnimalIdentityMask": 5,
    "pAnisoNormalBend": 0,
    "pAnisotropicLength": 0,
    "pAnisotropicRotation": 0,
    "pAnisotropicStrength": 0,
    "pAtmosphere_AmbientScatterColour": 2,
    "pAtmosphere_AmbientScatterIntensity": 0,
    "pAtmosphere_BetaMieExtScale": 0,
    "pAtmosphere_ColourMie": 2,
    "pAtmosphere_DensityMie": 0,
    "pAtmosphere_DensityPower": 0,
    "pAtmosphere_DirectionalScatterDirectivity0": 0,
    "pAtmosphere_DirectionalScatterDirectivity1": 0,
    "pAtmosphere_DirectionalScatterIntensity0": 0,
    "pAtmosphere_DirectionalScatterIntensity1": 0,
    "pAtmosphere_Height": 0,
    "pBaseColourDetailStrength": 0,
    "pBaseColourUniqueBlend": 0,
    "pBoundThickness": 0,
    "pBoundaryPosHalfSizeXZ": 3,
    "pBrightness": 0,
    "pClipThreshold": 0,
    "pCoarseNoiseScale": 0,
    "pCoarseNoiseTile": 0,
    "pColourMask_HSLGenetic0": 2,
    "pColourMask_HSLGenetic1": 2,
    "pColourMask_HSLGeneticAlbino0": 2,
    "pColourMask_HSLGeneticAlbino1": 2,
    "pColourMask_HSLGeneticErythristic0": 2,
    "pColourMask_HSLGeneticErythristic1": 2,
    "pColourMask_HSLGeneticLeucistic0": 2,
    "pColourMask_HSLGeneticLeucistic1": 2,
    "pColourMask_HSLGeneticMelanistic0": 2,
    "pColourMask_HSLGeneticMelanistic1": 2,
    "pColourMask_HSLGeneticXanthic0": 2,
    "pColourMask_HSLGeneticXanthic1": 2,
    "pColourMask_NoiseContrast": 0,
    "pColourMask_NoiseThreshold": 0,
    "pColourMask_NoiseWeight": 0,
    "pContrast": 0,
    "pCorpseTint": 2,
    "pCrownRadius": 0,
    "pDamageFade": 0,
    "pDamageLevelForClip": 0,
    "pDamageThreshold25": 0,
    "pDamageThreshold50": 0,
    "pDamageThreshold75": 0,
    "pDepthBias": 0,
    "pDepthColour": 2,
    "pDepthDistance": 0,
    "pDetailBaseOffset": 1,
    "pDetailMapTileRate": 0,
    "pDetailNormalStrength": 0,
    "pDetailTexCoordData": 3,
    "pDetailTexCoordIndex": 5,
    "pDetailTile": 0,
    "pDielectricSpecularLevel": 0,
    "pDiffuseHeightVarianceOcclusionBias": 0,
    "pDiffuseTint": 2,
    "pDiffuseTransmittance": 0,
    "pDirectScatterTransmittance": 2,
    "pDirectionalLightTransmittanceOcclusion": 0,
    "pDirtDryColour": 2,
    "pDirtWetColour": 2,
    "pDistanceEndForOpaqueAtDistance": 0,
    "pDistanceFieldParams": 3,
    "pDistanceStartForOpaqueAtDistance": 0,
    "pDistortionOpacityThreshold": 0,
    "pDistortionScale": 0,
    "pEmissiveAdaptiveBrighnessWeight": 0,
    "pEmissiveAlphaBlendWeight": 0,
    "pEmissiveAngleOpacity": 1,
    "pEmissiveBlend": 0,
    "pEmissiveColour": 2,
    "pEmissiveColour0": 2,
    "pEmissiveColour1": 2,
    "pEmissiveExposureWeight": 0,
    "pEmissiveIntensity": 0,
    "pEmissiveLightPower": 0,
    "pEmissiveLightType": 5,
    "pEmissiveMaskPower": 0,
    "pEmissiveMaskSize": 1,
    "pEmissiveScrollData": 2,
    "pEmissiveTint": 2,
    "pEnableAlphaTestRefFade": 6,
    "pEnableEmissiveFlexiColour": 6,
    "pEnableOpaqueAtDistance": 6,
    "pEnablePoweredEmissive": 6,
    "pEnablePulsingEmissive": 6,
    "pEnableRandomSubLayerOffset": 6,
    "pEnableScreenSpaceAO": 6,
    "pEnableVertexAO": 6,
    "pEnableWeatherPooling": 6,
    "pEnabledNewHeightBlending": 6,
    "pEndThickness": 0,
    "pErythristicHeightScale": 0,
    "pExpose": 6,
    "pExposureWeight": 0,
    "pEyeHorizonOffset": 0,
    "pEyeSunYMultiplierIris": 0,
    "pEyeSunYMultiplierLens": 0,
    "pEyelidOcclusion": 1,
    "pFaceCamera": 6,
    "pFallbackCavityRoughness": 1,
    "pFallbackSpecular": 2,
    "pFalloff": 0,
    "pFinAxisFade": 0,
    "pFinCorpseAlpha": 0,
    "pFinNormalBend": 0,
    "pFinNormalCurveBend": 0,
    "pFinOpacity": 0,
    "pFinRimFade": 0,
    "pFinTilingRate": 0,
    "pFlexiColourBlended": 6,
    "pFlexiColourStrength": 0,
    "pFlexiColourTexCoordIndex": 5,
    "pFlexiColourUseAdditiveBlend": 6,
    "pFlexiColourVertexColour": 6,
    "pForwardFadeOffset": 0,
    "pForwardFadeScale": 0,
    "pFurAlbinoDepthScale": 0,
    "pFurAlbinoSpecularDepthScale": 0,
    "pFurDepthScale": 0,
    "pFurErythristicDepthScale": 0,
    "pFurErythristicSpecularDepthScale": 0,
    "pFurLeucisticDepthScale": 0,
    "pFurLeucisticSpecularDepthScale": 0,
    "pFurMelanisticDepthScale": 0,
    "pFurMelanisticSpecularDepthScale": 0,
    "pFurSpecularDepthScale": 0,
    "pFurXanthicDepthScale": 0,
    "pFurXanthicSpecularDepthScale": 0,
    "pGrassDarkenEnd": 0,
    "pGrassDarkenFactor": 0,
    "pGrassDarkenStart": 0,
    "pGrassRoughness": 0,
    "pGrassUpBias": 0,
    "pGrassiness": 0,
    "pHeightBlendingDistance": 0,
    "pHeightBlendingScale": 0,
    "pHeightScale": 0,
    "pHighlightAlphaTestRefBias": 0,
    "pHighlightChannelWeights": 3,
    "pHighlightPatternDistance": 5,
    "pHighlightPatternSpeed": 0,
    "pHighlightUsePattern": 6,
    "pIBLRoughness": 0,
    "pIBLRoughnessTweak": 0,
    "pIBLScatterTransmittanceSurfaceNormalDistortion": 0,
    "pIncreaseRoughnessByRainIntensity": 1,
    "pIridescenceColourRange": 0,
    "pIridescenceCurve": 0,
    "pIridescenceFilmThickness": 0,
    "pIridescenceHueRange": 1,
    "pIridescenceHueRoll": 0,
    "pIsDisplayPanel": 6,
    "pIsSpeedTree": 6,
    "pLayerHeightBlend": 0,
    "pLensRoughness": 0,
    "pLensSpecularLevel": 0,
    "pLeucisticHeightScale": 0,
    "pMacroDamageBlendMapTiling": 1,
    "pMacroDamageFade": 0,
    "pMacroScale": 0,
    "pMacroTile": 0,
    "pMarkingMipBias": 0,
    "pMarkingNoiseEnableRandomOffset": 6,
    "pMarkingNoiseScale": 0,
    "pMaskNormals": 6,
    "pMaximumSnowAmount": 0,
    "pMaximumWaterPermeability": 0,
    "pMelanisticHeightScale": 0,
    "pMetalSpecularDarken_Invert": 6,
    "pMetalSpecularDarken_Power": 0,
    "pMetalSpecularDarken_Scale": 0,
    "pMetalSpecularDarken_StartAngle": 0,
    "pMetalSpecularFill_Power": 0,
    "pMetalSpecularFill_Scale": 0,
    "pMetalSpecularFill_StartAngle": 0,
    "pMetallicDetailStrength": 0,
    "pMipBias": 0,
    "pMossAmount": 0,
    "pMossDielectricSpecularLevel": 0,
    "pMossDiscolour": 2,
    "pMossDiscolourEdge": 0,
    "pMossDiscolourRelativeToHeight": 6,
    "pMossEdge": 0,
    "pMossEdgeDetail": 0,
    "pMossEdgeFalloff": 0,
    "pMossEnabled": 6,
    "pMossHeight": 0,
    "pMossHeightVertexColourScale": 0,
    "pMossPitch": 0,
    "pMossSheenAmount": 0,
    "pMossSheenTint": 2,
    "pMossTiling": 0,
    "pMossVarianceAmount": 0,
    "pMossVarianceEdge": 0,
    "pMossVarianceEdgeFalloff": 0,
    "pMossVarianceTiling": 0,
    "pMossYaw": 0,
    "pMotionBlendStrength": 0,
    "pNoisiness": 0,
    "pNormalDetailStrength": 0,
    "pNormalMapAngleDarkenStrength": 0,
    "pNormalMapRefractionStrength": 0,
    "pNormalizeType": 0,
    "pNumFramesX": 5,
    "pNumFramesY": 5,
    "pOcclusionBillboardHeightOffset": 0,
    "pOcclusionBillboardScale": 0,
    "pOceanDiffuseDarken_Power": 0,
    "pOceanDiffuseDarken_Scale": 0,
    "pOceanDiffuseDarken_StartAngle": 0,
    "pOffset0": 0,
    "pOffset1": 0,
    "pOffset2": 0,
    "pOpacity": 0,
    "pOpacityDistance": 0,
    "pOpacityMapScaleOffset": 1,
    "pOpacityScale": 0,
    "pParticleFadeCollapse": 1,
    "pParticleLightScatterData": 1,
    "pParticleNormalType": 5,
    "pParticleSoftDepth": 6,
    "pPatternClip": 6,
    "pPatternTexCoordOffset": 1,
    "pPatternTexCoordScale": 0,
    "pPatternTexCoordWrap": 6,
    "pPositionalFade_Position": 2,
    "pPositionalFade_StartEndDistance": 1,
    "pPulsingEmitDarkenScale": 0,
    "pPulsingEmitFrequency": 0,
    "pRandomFrequency": 0,
    "pRandomScale": 0,
    "pReflectionDistortion": 0,
    "pReflectionPlaneRoughnessTolerance": 0,
    "pRefractionDistortion": 0,
    "pRelativeFalloff": 6,
    "pRenderLayerOverride": 5,
    "pRetroreflectiveBrightness": 0,
    "pRoughness": 0,
    "pRoughnessDetailBlend": 0,
    "pRoughnessDetailStrength": 0,
    "pRoughnessRefractionStrength": 0,
    "pSSAOScatterReflectionOcclusionStrength": 0,
    "pSSRReflectionTransmittanceMip": 0,
    "pSSRReflectionTransmittanceScale": 0,
    "pScale0": 0,
    "pScale1": 0,
    "pScale1Normal": 0,
    "pScale2": 0,
    "pScale2Normal": 0,
    "pScarBaldnessCutoff": 0,
    "pScarBaldnessCutoffAlbino": 0,
    "pScarBaldnessCutoffErythristic": 0,
    "pScarBaldnessCutoffLeucistic": 0,
    "pScarBaldnessCutoffMelanistic": 0,
    "pScarBaldnessCutoffXanthic": 0,
    "pScarMaskPower": 0,
    "pScatterHeightVarianceOcclusionBias": 0,
    "pScreenSpaceAOStrength": 0,
    "pScrollSpeed0": 1,
    "pScrollSpeed1": 1,
    "pShadowOpacity": 0,
    "pShadowStrength": 0,
    "pShellCorpseAlphaCut": 0,
    "pShellOpacity": 0,
    "pShellRimFade": 0,
    "pShellRimNudge": 0,
    "pShellTilingRate": 0,
    "pSkirtMaskScaleOffset": 3,
    "pSnowOnSlopesOffset": 0,
    "pSpecularBrightness": 0,
    "pSpecularHeightVarianceOcclusionBias": 0,
    "pSpecularLevel": 0,
    "pSpecularOcclusion": 0,
    "pSpecularSaturation": 0,
    "pStartFade": 0,
    "pStartThickness": 0,
    "pSubLayer0": 3,
    "pSubLayer0DiffuseTint": 2,
    "pSubLayer1": 3,
    "pSubLayer1DiffuseTint": 2,
    "pSubLayerAOMipBias": 0,
    "pSubLayerAOStregnth": 0,
    "pSubLayerOpacityMipBias": 0,
    "pSubLayerTile": 0,
    "pTilingDetailBlend": 0,
    "pTopSeeTroughModifier": 0,
    "pTransmissionColour": 2,
    "pTransmissionFalloff": 0,
    "pTransmissionRoughness": 0,
    "pTransmittance": 0,
    "pTransmittanceMinimum": 0,
    "pTransmittanceScale": 0,
    "pTriPlanarTile": 0,
    "pTrunkHeight": 0,
    "pUnderwaterOnly": 6,
    "pUseDamageThresholds": 6,
    "pUseExplicitNormals": 6,
    "pUseMotionVectors": 6,
    "pUseOrenNayar": 6,
    "pUsePlanarReflections": 6,
    "pUseTwoSidedExplicitNormal": 6,
    "pUseTwoSidedNormal": 6,
    "pUseVertexColour": 6,
    "pVerticalTiling": 0,
    "pWaterColour": 2,
    "pWaterDetailTile01": 1,
    "pWaterDetailWeights01": 1,
    "pWaterDrawParticleRipples": 6,
    "pWaterEdgeOpacityScale": 0,
    "pWaterFoggingDistance": 0,
    "pWaterPlaneThickness": 0,
    "pWaterRainRipplesScale": 0,
    "pWaterSpecular": 0,
    "pWaterUseTexcoords": 6,
    "pWaterfall_EnableDynamicRipples": 6,
    "pWaterfall_EnableRainRipples": 6,
    "pWaterfall_RainIntensityRoughnessModifier": 1,
    "pWaterfall_RainRipplesIntensity": 0,
    "pWaterfall_ReflectionDistortion": 0,
    "pWaterfall_RefractionDistortion": 0,
    "pWaterfall_WaterBaseBlendweights": 1,
    "pWaterfall_WaterBaseScrollSpeed0": 1,
    "pWaterfall_WaterBaseScrollSpeed1": 1,
    "pWaterfall_WaterBaseTileRates": 1,
    "pWaterfall_WaterEdgeOpacityScale": 0,
    "pWaterfall_WaterFlowBlendweight": 0,
    "pWaterfall_WaterFlowFoamBlendDistance": 1,
    "pWaterfall_WaterFlowFoamBlendweights": 1,
    "pWaterfall_WaterFlowFoamFlowDistanceStrength": 1,
    "pWaterfall_WaterFlowFoamTileOffset": 3,
    "pWaterfall_WaterFlowFoamTileRate": 1,
    "pWaterfall_WaterFlowIntensity": 0,
    "pWaterfall_WaterFlowMaxSpeed": 0,
    "pWaterfall_WaterFlowMaxTimeOffset": 0,
    "pWaterfall_WaterFlowMipBias": 1,
    "pWaterfall_WaterFlowTileRate": 1,
    "pWaterfall_WaterFoggingDistance": 0,
    "pWaterfall_WaterMaxFlowDistance": 1,
    "pWaveAmplitudes": 3,
    "pWaveCompliance": 0,
    "pWaveFrequencies": 3,
    "pWeather_Enable": 6,
    "pWeather_ExplicitNormalThreshold": 0,
    "pWeather_LocalWaterAmount": 0,
    "pWeight1Power": 0,
    "pWetRoughnessStrength": 0,
    "pWetRoughnessValue": 0,
    "pWetSpecularStrength": 0,
    "pWetSpecularValue": 0,
    "pWetnessYPositionLower": 0,
    "pWetnessYPositionUpper": 0,
    "pWindScale": 0,
    "pWoundBloodDepthStrength": 0,
    "pWoundBloodNormalStrength": 0,
    "pWoundBloodRoughness": 0,
    "pWoundBloodSpecularReflectance": 0,
    "pWoundDepthMaskPower": 0,
    "pWoundScarDepthStrength": 0,
    "pWoundScarNormalStrength": 0,
    "pWoundScarRoughness": 0,
    "pWoundScarSpecularReflectance": 0,
    "pXanthicHeightScale": 0,
}

textures = {
    "p2MarkingBaldnessScarTexture",
    "p3MarkingScarTexture",
    "pAOTexture",
    "pAOTexture2",
    "pAOTextureDetail",
    "pAOTextureUnique",
    "pAlbedoAndRoughnessDetail",
    "pAlbinoBaseColourAndMaskTexture",
    "pBaldnessScarTexture",
    "pBaseColour2",
    "pBaseColourAndMaskTexture",
    "pBaseColourTexture",
    "pBaseColourTexture2",
    "pBaseColourTextureDetail",
    "pBaseColourTextureDetailBase",
    "pBaseColourTextureDetailBlend",
    "pBaseColourTextureUnique",
    "pBaseDielectricSpecularLevelTexture",
    "pBaseNormalTexture",
    "pCavityRoughnessDielectricArray",
    "pClipMap2",
    "pClut",
    "pCoarseNoise",
    "pDamageBlendMap",
    "pDetailMask",
    "pDetailNormalTexture",
    "pDetailRoughnessTexture",
    "pDiffuse",
    "pDiffuseAlbino",
    "pDiffuseArray",
    "pDiffuseErythristic",
    "pDiffuseLeucistic",
    "pDiffuseMelanistic",
    "pDiffuseTexture",
    "pDiffuseXanthic",
    "pDistortionTexture",
    "pEmissiveMaskTexture",
    "pEmissiveTexture",
    "pErythristicBaseColourAndMaskTexture",
    "pFinAlphaTexture",
    "pFlexiColourMasksTexture",
    "pGradHeightArray",
    "pHeight",
    "pIridescenceStrength",
    "pIridescenceTexture",
    "pLeucisticBaseColourAndMaskTexture",
    "pMacroDamageBlendMap",
    "pMacroDiffuse",
    "pMarkingNoise",
    "pMarkingPatchworkMask",
    "pMaskAOTextureUnique",
    "pMelanisticBaseColourAndMaskTexture",
    "pMossBaseColourRoughnessPackedTexture",
    "pMossNormalTexture",
    "pMossVarianceTexture",
    "pNormalBlendWeightTexture",
    "pNormalMapTextureUnique",
    "pNormalTexture",
    "pNormalTexture2",
    "pNormalTextureDetail",
    "pNormalTextureDetailBase",
    "pNormalTextureDetailBlend",
    "pNormalTextureUnique",
    "pOpacityTexture",
    "pOpacityTexture2",
    "pRetroreflectiveness",
    "pRoughnessAOPackedTextureDetailBase",
    "pRoughnessPackedTexture",
    "pRoughnessPackedTexture2",
    "pRoughnessPackedTextureDetail",
    "pRoughnessPackedTextureUnique",
    "pScarClut",
    "pShellMap",
    "pSkirtMaterialMask",
    "pSkirtNormals",
    "pSubLayerDiffuse0Texture",
    "pSubLayerDiffuse1Texture",
    "pThicknessTexture",
    "pTransmittancePackedTexture",
    "pWaterDetailNormalTexture",
    "pWaterDetailRoughnessTexture",
    "pWaterfall_WaterFlowAndTimeOffsetMap",
    "pWaterfall_WaterFoamMaskMap",
    "pWaterfall_WaterNormalRoughnessMap",
    "pXanthicBaseColourAndMaskTexture",
}

shaders = {
    "Animal_Clip_DoubleSided",
    "Animal_Eye",
    "Animal_Skin",
    "Animal_Skin",
    "Animal_SkinDetail",
    "Animal_SkinMarkings",
    "Animal_Skin_NoDirt",
    "Animal_Whisker",
    "Collection_Pattern",
    "Depth_Fade",
    "Depth_Fade_Dissolve",
    "Foliage_Billboard",
    "Foliage_BillboardEmissive",
    "Foliage_Clip",
    "Foliage_Clip",
    "Foliage_Clip_NotSpeedTree",
    "Foliage_Grass_DetailObject",
    "Foliage_Opaque",
    "Foliage_Opaque",
    "Foliage_Opaque_NotSpeedTree",
    "FrontEnd_Atmosphere",
    "FrontEnd_GlobeArea",
    "FrontEnd_Metal",
    "FrontEnd_Ocean",
    "FrontEnd_Radial",
    "FrontEnd_SkyBox",
    "FurBase",
    "FurBaseAlpha",
    "FurBaseAlpha_SingleSided",
    "FurFin",
    "FurPatchworkBaldnessBase",
    "FurPatchworkBaldnessFin",
    "FurPatchworkBaldnessShell",
    "FurPatchworkBase",
    "FurPatchworkFin",
    "FurPatchworkShell",
    "FurShell",
    "Game_Terrain",
    "Game_WeatherParticle",
    "Game_WeatherParticle_AnimatedSplash",
    "Game_WeatherParticle_RainDrop",
    "Game_WeatherParticle_TiledRain",
    "Glass_Distant_Wall",
    "Glass_Preview_Textured",
    "Glass_Preview_TexturedTwoSided",
    "Glass_Preview_Textured_Wall",
    "Glass_TexturedTwoSided_Weather",
    "Glass_TexturedTwoSided_Weather",
    "Glass_TexturedTwoSided_Weather_Distant",
    "Glass_TexturedTwoSided_Weather_PerPixelFlexiColour",
    "Glass_Textured_Weather",
    "Glass_Textured_Weather_Distant",
    "Glass_Textured_Weather_Distant_Dissolve",
    "Glass_Textured_Weather_PerPixelFlexiColour",
    "Glass_Wall",
    "Ice_Opaque",
    "Ice_OpaqueSurface_TriPlanar",
    "Ice_Opaque_Extrusion2D",
    "Ice_Opaque_TriPlanar",
    "Ice_Opaque_TriPlanar_Dissolve",
    "Ice_Preview_ClipDoubleSided_Extrusion2D",
    "Ice_Preview_Opaque",
    "Ice_Preview_OpaqueSurface_TriPlanar",
    "Ice_Preview_Opaque_Extrusion2D",
    "Ice_Preview_Opaque_TriPlanar",
    "IridescentAnisotropic",
    "IridescentAnisotropicAlpha",
    "Metallic_Roughness_Clip_DiffuseBlend_Dissolve",
    "Metallic_Roughness_Clip_DoubleSided_Extrusion2D",
    "Metallic_Roughness_Clip_DoubleSided_Extrusion2D_TAAGroup4",
    "Metallic_Roughness_Clip_EmissiveLightType_Weather",
    "Metallic_Roughness_Clip_EmissiveLightType_Weather_DoubleSided_TAAGroup6",
    "Metallic_Roughness_Clip_Flag",
    "Metallic_Roughness_Clip_Geometry_Decal",
    "Metallic_Roughness_Clip_TextEmissiveLightType_Weather",
    "Metallic_Roughness_Clip_Text_Weather",
    "Metallic_Roughness_Clip_Wall",
    "Metallic_Roughness_Clip_Weather",
    "Metallic_Roughness_Clip_Weather_Dissolve",
    "Metallic_Roughness_Clip_Weather_DoubleSided",
    "Metallic_Roughness_Clip_Weather_DoubleSided_Dissolve",
    "Metallic_Roughness_Clip_Weather_DoubleSided_TAAGroup6",
    "Metallic_Roughness_Clip_Weather_TAAGroup6",
    "Metallic_Roughness_Clip_Weather_Transmissive",
    "Metallic_Roughness_Detail_Basic_Opaque_Weather",
    "Metallic_Roughness_Detail_Opaque_Weather",
    "Metallic_Roughness_OneWayGlassOpaque_Wall",
    "Metallic_Roughness_Opaque",
    "Metallic_Roughness_OpaqueEmissive_Extrusion2D",
    "Metallic_Roughness_OpaqueEmissive_Game_NoWeather_TAAGroup4",
    "Metallic_Roughness_Opaque_DiffuseBlend_Dissolve",
    "Metallic_Roughness_Opaque_Dissolve",
    "Metallic_Roughness_Opaque_EmissiveLightType_Weather",
    "Metallic_Roughness_Opaque_Extrusion2D",
    "Metallic_Roughness_Opaque_Extrusion2D_TAAGroup4",
    "Metallic_Roughness_Opaque_Game_NoWeather_TAAGroup4",
    "Metallic_Roughness_Opaque_Surface_TriPlanar_Weather",
    "Metallic_Roughness_Opaque_Wall",
    "Metallic_Roughness_Preview_Clip",
    "Metallic_Roughness_Preview_ClipDoubleSided",
    "Metallic_Roughness_Preview_ClipDoubleSided_Extrusion2D",
    "Metallic_Roughness_Preview_Clip_Wall",
    "Metallic_Roughness_Preview_Detail_Opaque",
    "Metallic_Roughness_Preview_Opaque",
    "Metallic_Roughness_Preview_Opaque_Extrusion2D",
    "Metallic_Roughness_Preview_Opaque_Surface_TriPlanar",
    "Metallic_Roughness_Preview_Opaque_Wall",
    "Opaque_DetailObject",
    "Particle_Alpha",
    "Particle_Alpha_AmbientOnly",
    "Particle_Alpha_AmbientOnly_TexBlend",
    "Particle_Alpha_AmbientOnly_TexBlend_PositionalFade",
    "Particle_Alpha_AmbientOnly_WaterOccludee",
    "Particle_Alpha_EmissiveOnly",
    "Particle_Alpha_EmissiveOnly_TexBlend",
    "Particle_Alpha_Modulate",
    "Particle_Alpha_TexBlend",
    "Particle_Clip",
    "Particle_Clip_Specular",
    "Particle_Clip_TexBlend",
    "Particle_Refractive",
    "RenderMesh_WhiteWorldUI",
    "Retroreflective",
    "Terrain_Boundary",
    "Terrain_Edit_Grid",
    "Terrain_Ice_Decal",
    "Terrain_Metallic_Roughness_Decal",
    "Terrain_Preview_Ice_Decal",
    "Terrain_Preview_Metallic_Roughness_Decal",
    "Terrain_Skirt_Weather",
    "UI_Clip_Emissive",
    "UI_Opaque_Emissive_Extrusion2D",
    "Water_Water",
    "Water_WaterFlexi",
    "Water_WaterOccluder",
    "Water_WaterVolume",
    "Water_WaterVolumeCW",
    "Water_WaterVolumeOpaque",
    "Water_WaterVolumeOpaqueCW",
    "Water_WaterVolumeSide",
    "Water_WaterVolumeSideCW",
    "Water_WaterVolumeSideOpaque",
    "Water_WaterVolumeSideOpaqueCW",
    "Waterfall_Water",
    "Weather_PrecipitationOcclusion",
    "WindVectorField_Debug",
}
