attributes = {
    "gAnisotropicStrength": 0,
    "gBendStretchScale": 0,
    "gDirectionScale": 0,
    "gFinBrushScale": 0,
    "gHeightStretchScale": 0,
    "gLodFade": 1,
    "gShellClumping": 0,
    "gShellUVStretchPower": 0,
    "gWetClumping": 0,
    "gWetHairBaseDirectionStrength": 0,
    "gWetHairDirectionStrength": 0,
    "gWetHairDownwardPush": 0,
    "isHorizontal": 6,
    "pAlphaBlendWeight": 0,
    "pAlphaClip": 0,
    "pAlphaTestRef": 0,
    "pAlphaToOpacityRemap": 1,
    "pAmbientTransmissionAmount": 0,
    "pAmbientTransmissionTint": 2,
    "pAngleDarkenPower": 0,
    "pAnisoNormalBend": 0,
    "pAniso_DirectionOffset": 0,
    "pAniso_IsBody": 6,
    "pAniso_LengthStraightenStrength": 0,
    "pAniso_Strength": 0,
    "pAshColour": 2,
    "pAshSmoothStepMax": 0,
    "pAshSmoothStepMin": 0,
    "pAutoZoomLodDitherScale": 0,
    "pAutoZoomLodOffset": 0,
    "pAutoZoomLodPostScale": 0,
    "pAutoZoomLodPreScale": 0,
    "pBarkNormalStrength": 0,
    "pBlendDistance": 0,
    "pBlendMode": 5,
    "pBlendWeightLodDistanceCoeff": 0,
    "pBlendWeightLodLayerScale": 0,
    "pBlendWeightLodTriplanarScale": 0,
    "pColour": 3,
    "pCrownRadius": 0,
    "pDecals_IsEnabled": 6,
    "pDepthBias": 0,
    "pDepthColour": 2,
    "pDepthDistance": 0,
    "pDetailBaseOffset": 1,
    "pDetailNormalLodFade": 1,
    "pDetailNormalScale": 0,
    "pDetailNormalStrength": 0,
    "pDetailNormalTile": 0,
    "pDetailTile": 0,
    "pDielectricReflectivity": 5,
    "pDielectricSpecularLevel": 0,
    "pDiffuseContrast": 0,
    "pDiffuseHeightVarianceOcclusionBias": 0,
    "pDiffuseLevels": 1,
    "pDiffuseSaturation": 0,
    "pDiffuseTint": 2,
    "pDiffuseTransmittance": 0,
    "pDinoWind_FurDirectionScale": 0,
    "pDinoWind_JitterMax": 0,
    "pDinoWind_JitterSpeed": 0,
    "pDinoWind_JitterSpread": 0,
    "pDinoWind_JitterStrength": 0,
    "pDinoWind_NormalBend": 0,
    "pDinoWind_ShellDisplacementMin": 0,
    "pDinoWind_ShellDisplacementRange": 0,
    "pDinoWind_Strength": 0,
    "pDinoWind_WindSizeScale": 0,
    "pDinoWind_WindStrength": 0,
    "pDinosaurFur_OverrideShellCount": 5,
    "pDirectScatterTransmittance": 2,
    "pDirectionalLightTransmittanceOcclusion": 0,
    "pDirectionalScatterOcclusionScale": 0,
    "pDistortionOpacityThreshold": 0,
    "pDistortionScale": 0,
    "pEmissiveAdaptiveBrighnessWeight": 0,
    "pEmissiveBlend": 0,
    "pEmissiveIntensity": 0,
    "pEmissivePower": 0,
    "pEmissiveScale": 0,
    "pEmissiveScrollData": 2,
    "pEmissiveTint": 2,
    "pEnableAlphaScrolling": 6,
    "pEnableAlphaTestRefFade": 6,
    "pEnableBaseDiffuseTexture": 6,
    "pEnableBlendWeightLod": 6,
    "pEnableDiffuseFlexiColour": 6,
    "pEnableEmissiveFlexiColour": 6,
    "pEnableFeathersBaseDiffuseTexture": 6,
    "pEnableFresnelOpacity": 6,
    "pEnableMoss": 6,
    "pEnableNearPlaneAvoidance": 6,
    "pEnableNormalContrast": 6,
    "pEnableRandomSubLayerOffset": 6,
    "pEnableScreenSpaceAO": 6,
    "pEnableSpecularFlexiColour": 6,
    "pEnableVertexAO": 6,
    "pEnableVerticalMacro": 6,
    "pEnableWeatherPooling": 6,
    "pEnvironmentalMossEdge": 0,
    "pEnvironmentalMossEdgeFalloff": 0,
    "pEnvironmentalMossTiling": 0,
    "pEnvironmentalMossYaw": 0,
    "pExtrusionScaling": 1,
    "pFaceCamera": 6,
    "pFallbackCavityRoughness": 1,
    "pFallbackSpecular": 2,
    "pFalloff": 0,
    "pFinAxisFade": 0,
    "pFinCorpseAlpha": 0,
    "pFinNormalBend": 0,
    "pFinNormalCurveBend": 0,
    "pFinOpacity": 0,
    "pFinRimFade": 0,
    "pFinTilingRate": 0,
    "pFlexiColourBlended": 6,
    "pFlexiColourTexCoordIndex": 5,
    "pFlexiColourUseAdditiveBlend": 6,
    "pFlexiColourVertexColour": 6,
    "pFlexicolourMasterMask": 0,
    "pFoamMultiplier": 0,
    "pFoamTile1": 0,
    "pFoamTile2": 0,
    "pForwardFadeOffset": 0,
    "pForwardFadeScale": 0,
    "pFresnelPower": 0,
    "pFurDepthScale": 0,
    "pFurSpecularDepthScale": 0,
    "pGeometryDecalAlphaBlendMode": 5,
    "pGlobalColouringWeight": 0,
    "pGlobalEffectModifier": 6,
    "pHeightBlendScaleA": 0,
    "pHeightBlendScaleB": 0,
    "pHeightOffset": 0,
    "pHeightScale": 0,
    "pHighlightAlphaTestRefBias": 0,
    "pHyperloops_DiffuseIntensity": 0,
    "pHyperloops_DiffuseTint": 2,
    "pHyperloops_EnableFresnelOpacity": 6,
    "pHyperloops_FresnelPower": 0,
    "pHyperloops_OpacityHeightAdjust": 0,
    "pHyperloops_OpacityHeightWeight": 0,
    "pHyperloops_OpacityScale": 0,
    "pIBLRoughnessTweak": 0,
    "pIBLScatterTransmittanceSurfaceNormalDistortion": 0,
    "pIncreaseRoughnessByRainIntensity": 1,
    "pIncreaseRoughnessByWindSpeed": 2,
    "pIridescenceAmount": 0,
    "pIridescenceColourRange": 0,
    "pIridescenceCurve": 0,
    "pIridescenceFilmThickness": 0,
    "pIridescenceHueRange": 1,
    "pIridescenceHueRoll": 0,
    "pIsSpeedTree": 6,
    "pLayerHeightBlend": 0,
    "pLayered_AshUpwards": 0,
    "pLayered_AshWeight": 0,
    "pLayered_BlendWeightBatchCount": 5,
    "pLayered_EnableWarp": 6,
    "pLayered_HeightScale": 0,
    "pLayered_LayerCount": 5,
    "pLayered_PositionOffset": 2,
    "pLayered_PositionScale": 2,
    "pLengthTransmissionStrength": 0,
    "pLight_Height": 0,
    "pLight_Rotation": 0,
    "pLight_Shading": 0,
    "pLightingParticleVolumeAdaptiveBrighnessWeight": 0,
    "pLightingParticleVolumeBetaMieExtScale": 0,
    "pLightingParticleVolumeBrightnessScale": 0,
    "pLightingParticleVolumeDirectivityAttenuation": 0,
    "pLightingParticleVolumeLightOpticalDepthAttenuation": 0,
    "pLightingParticleVolumeMieDensity": 0,
    "pLightingParticleVolumeMieDirectivity0": 0,
    "pLightingParticleVolumeMieDirectivity1": 0,
    "pLightingParticleVolumeMieDirectivityWeight": 0,
    "pLightingParticleVolumeTransmittanceAttenuation": 0,
    "pLightingSurfaceDiffuseWrap": 0,
    "pLightingVolumeDiffuseTextureStrength": 0,
    "pLightingVolumeOpacityTextureCurve": 0,
    "pLightingVolumeOpacityTextureScale": 0,
    "pMacroTile": 0,
    "pMaskNormals": 6,
    "pMaximumDustAmount": 0,
    "pMaximumSnowAmount": 0,
    "pMaximumWaterPermeability": 0,
    "pMetallic": 0,
    "pMipBias": 0,
    "pModelViewer_AnimatedGlowFrequencyCircular": 0,
    "pModelViewer_AnimatedGlowFrequencyNoisy": 0,
    "pModelViewer_AnimatedGlowIntensityCircular": 0,
    "pModelViewer_AnimatedGlowIntensityNoisy": 0,
    "pModelViewer_AnimatedGlowMapContributionCircular": 0,
    "pModelViewer_AnimatedGlowMapContributionNoisy": 0,
    "pModelViewer_AnimatedGlowSpeedCircular": 0,
    "pModelViewer_AnimatedGlowSpeedNoisy": 0,
    "pModelViewer_ChomaticAbberationIntensity": 0,
    "pModelViewer_EchoDistance": 0,
    "pModelViewer_EchoOpacity1": 0,
    "pModelViewer_EchoOpacity2": 0,
    "pModelViewer_EchoSteps": 5,
    "pModelViewer_EmissiveStrength1": 0,
    "pModelViewer_EmissiveStrength2": 0,
    "pModelViewer_ExposureCompensation": 0,
    "pModelViewer_GridColour": 2,
    "pModelViewer_GridSize": 0,
    "pModelViewer_HorizonFadeFalloff": 0,
    "pModelViewer_LineThickness": 0,
    "pModelViewer_SpecularStrength": 0,
    "pModelViewer_UseEchoEffect": 6,
    "pModelViewer_UseTexturedEmissive": 6,
    "pMossAmount": 0,
    "pMossDielectricSpecularLevel": 0,
    "pMossDiscolour": 2,
    "pMossDiscolourEdge": 0,
    "pMossDiscolourRelativeToHeight": 6,
    "pMossEdge": 0,
    "pMossEdgeDetail": 0,
    "pMossEdgeFalloff": 0,
    "pMossHeight": 0,
    "pMossHeightVertexColourScale": 0,
    "pMossNoiseMaskTilingX": 0,
    "pMossNoiseMaskTilingY": 0,
    "pMossNormalStrength": 0,
    "pMossPitch": 0,
    "pMossProjectionBreaker": 0,
    "pMossRockBottomEdgeFalloff": 0,
    "pMossRockBottomHeight": 0,
    "pMossRockTopEdgeFalloff": 0,
    "pMossRockTopHeight": 0,
    "pMossSheenAmount": 0,
    "pMossSheenTint": 2,
    "pMossTiling": 0,
    "pMossTrunkBaseEdgeFalloff": 0,
    "pMossTrunkBaseHeight": 0,
    "pMossTypeEnum": 5,
    "pMossVarianceAmount": 0,
    "pMossVarianceEdge": 0,
    "pMossVarianceEdgeFalloff": 0,
    "pMossVarianceTiling": 0,
    "pMossYaw": 0,
    "pMotionBlendStrength": 0,
    "pNormalContrast": 0,
    "pNormalMapAngleDarkenStrength": 0,
    "pNormalMapRefractionStrength": 0,
    "pNormalStrength": 0,
    "pNormalizeType": 0,
    "pNumFramesX": 5,
    "pNumFramesY": 5,
    "pObjectPressScale": 0,
    "pOcclusionDistance": 0,
    "pOcclusionEmissiveIntensity": 1,
    "pOcclusionEmissiveTint0": 2,
    "pOcclusionEmissiveTint1": 2,
    "pOcclusionOpacity": 1,
    "pOffset0": 0,
    "pOffset1": 0,
    "pOffset2": 0,
    "pOpacity": 0,
    "pOpacityRef": 0,
    "pOpacityScale": 0,
    "pPOM_AOStrength": 0,
    "pPOM_DisplacementStrength": 0,
    "pParticleExpands": 6,
    "pParticleExpandsFinalScale": 0,
    "pParticleFacesCamera": 6,
    "pParticleFadeCollapse": 1,
    "pParticleFadeInTimeProportion": 0,
    "pParticleFadeOutTimeProportion": 0,
    "pParticleGravity": 0,
    "pParticleInitialVerticalSpeed": 0,
    "pParticleNormalType": 5,
    "pParticleRotationSpeed": 0,
    "pParticleRotationSpeedVariation": 0,
    "pParticleSize": 0,
    "pParticleSizeVariation": 0,
    "pParticleSoftDepth": 6,
    "pPatchBlendMapScale": 0,
    "pPatchBlendMapTile": 0,
    "pPatternClip": 6,
    "pPatternTexCoordOffset": 1,
    "pPatternTexCoordScale": 0,
    "pPatternTexCoordWrap": 6,
    "pPatterning_EmissiveAdaptiveBrighnessWeight": 0,
    "pPatterning_EmissiveMaximumBrightness": 0,
    "pPerceptualRoughness": 0,
    "pPerturbationViewFlag": 5,
    "pPlayAreaBlendFactorScaleOffset": 1,
    "pPlayAreaHeightScaleOffset": 1,
    "pPlayAreaTexelMetrics": 3,
    "pPlayAreaUVScaleOffset": 3,
    "pPrimaryBlendMapScale": 0,
    "pPrimaryBlendMapTile": 0,
    "pProjection_AmbientOcclusion": 0,
    "pProjection_AmbientSaturation": 0,
    "pProjection_AtlasDimensionU": 5,
    "pProjection_AtlasDimensionV": 5,
    "pProjection_BackgroundPlaneAtlasRandomSeed": 5,
    "pProjection_BackgroundPlanePosition": 2,
    "pProjection_BackgroundPlaneUVOffset": 1,
    "pProjection_BackgroundPlaneUVTile": 1,
    "pProjection_ColourTint": 2,
    "pProjection_CoordinateScale": 0,
    "pProjection_CylinderWeight": 0,
    "pProjection_Dimensions": 1,
    "pProjection_EmissiveBrightness": 0,
    "pProjection_EmissiveColour": 2,
    "pProjection_EmissiveColourBrightness": 0,
    "pProjection_EnableVertexAmbientOcclusion": 6,
    "pProjection_ForegoundPlanePosition": 2,
    "pProjection_ForegroundPlaneAtlasRandomSeed": 5,
    "pProjection_ForegroundPlaneUVOffset": 1,
    "pProjection_ForegroundPlaneUVTile": 1,
    "pProjection_FresnelDarken": 1,
    "pProjection_HeightOffset": 0,
    "pProjection_IsBackgroundPlaneAtlasTexCoordEnabled": 6,
    "pProjection_IsBackgroundPlaneEnabled": 6,
    "pProjection_IsForegroundPlaneAtlasTexCoordEnabled": 6,
    "pProjection_IsForegroundPlaneEnabled": 6,
    "pProjection_MipBias": 1,
    "pProjection_Offset": 1,
    "pProjection_Plane0TexCoords": 3,
    "pProjection_Plane1TexCoords": 3,
    "pProjection_Plane2TexCoords": 3,
    "pProjection_PlanePositions": 2,
    "pProjection_Scale": 2,
    "pProjection_TexCoordDimensions": 1,
    "pProjection_TexCoordIndex": 5,
    "pProjection_TexCoords": 1,
    "pRainRipplesIntensity": 0,
    "pRandomFrequency": 0,
    "pRandomScale": 0,
    "pReflectionDistortion": 0,
    "pRefractionDistortion": 0,
    "pRefractionStrength": 1,
    "pRelativeFalloff": 6,
    "pRemapLutIndex": 5,
    "pRenderLayerOverride": 5,
    "pRoughness": 0,
    "pRoughnessDetailBlend": 0,
    "pRoughnessRefractionStrength": 0,
    "pSSAOScatterReflectionOcclusionStrength": 0,
    "pSSRReflectionTransmittanceMip": 0,
    "pSSRReflectionTransmittanceScale": 0,
    "pScale0": 0,
    "pScale1": 0,
    "pScale1Normal": 0,
    "pScale2": 0,
    "pScale2Normal": 0,
    "pScatterHeightVarianceOcclusionBias": 0,
    "pScatteringAlbedoScale": 0,
    "pScreenDistortionStrength": 0,
    "pScreenSpaceAOStrength": 0,
    "pScrollSpeed0": 1,
    "pScrollSpeed1": 1,
    "pShadowStrength": 0,
    "pShellCorpseAlphaCut": 0,
    "pShellOpacity": 0,
    "pShellRimFade": 0,
    "pShellRimNudge": 0,
    "pShellTilingRate": 0,
    "pSkirtMaskScaleOffset": 3,
    "pSkirtNormalBlend": 1,
    "pSkirtShadowBorderScaleOffset": 1,
    "pSnowOnSlopesOffset": 0,
    "pSnowOpacity": 0,
    "pSpecialMaskType": 5,
    "pSpecularHeightVarianceOcclusionBias": 0,
    "pSpecularReflectance": 2,
    "pSubLayer0": 3,
    "pSubLayer0DiffuseTint": 2,
    "pSubLayer1": 3,
    "pSubLayer1DiffuseTint": 2,
    "pSubLayerAOMipBias": 0,
    "pSubLayerAOStregnth": 0,
    "pSubLayerOpacityMipBias": 0,
    "pSubLayerTile": 0,
    "pSurfaceNormalDistortion": 0,
    "pTerrainMaximumWaterPermeability": 0,
    "pTilingDetailBlend": 0,
    "pTintRampRate": 0,
    "pTintRampStart": 0,
    "pTransmissionAmbient": 0,
    "pTransmissionColour": 2,
    "pTransmissionColourTint": 2,
    "pTransmissionFalloff": 0,
    "pTransmissionIridescenceTint": 0,
    "pTransmissionRoughness": 0,
    "pTransmissionScale": 0,
    "pTransmittance": 0,
    "pTransmittanceMinimum": 0,
    "pTransmittanceScale": 0,
    "pTriPlanarTile": 0,
    "pTrunkHeight": 0,
    "pUVEnableProjection": 6,
    "pUVOffset": 1,
    "pUVRotationAngle": 0,
    "pUVRotationPosition": 1,
    "pUVTile": 1,
    "pUnderwaterOnly": 6,
    "pUseExplicitNormals": 6,
    "pUseMotionVectors": 6,
    "pUseOrenNayar": 6,
    "pUseTwoSidedExplicitNormal": 6,
    "pVerticalTiling": 0,
    "pWaterDetailIntensity": 0,
    "pWaterDetailMipBias": 0,
    "pWaterDetailMipBiasMinimum": 0,
    "pWaterDetailNormalIntensity": 1,
    "pWaterDetailParallaxAmount": 0,
    "pWaterDetailParallaxCentre": 0,
    "pWaterDetailPlayRate": 5,
    "pWaterDetailRoughness": 0,
    "pWaterDetailScrollSpeed": 1,
    "pWaterDetailTile": 1,
    "pWaterDetailWeights": 1,
    "pWaterDiffuse_Foamy": 2,
    "pWaterEdgeOpacityScale": 0,
    "pWaterEdge_Falloff": 0,
    "pWaterEdge_NoiseScale": 0,
    "pWaterEdge_NoiseSpeed": 0,
    "pWaterEdge_NoiseStrength": 0,
    "pWaterEdge_WaterEdgeThreshold": 0,
    "pWaterFoamSpeed1": 1,
    "pWaterFoamSpeed2": 1,
    "pWaterFogging": 2,
    "pWaterIsUnderside": 6,
    "pWaterNormalIntensity": 1,
    "pWaterParallaxAmount": 0,
    "pWaterParallaxCentre": 0,
    "pWaterRoughnessFadeDitherWeight": 0,
    "pWaterRoughnessFadePower": 0,
    "pWaterScattering": 2,
    "pWaterScrollSpeed0": 1,
    "pWaterScrollSpeed1": 1,
    "pWaterSmoothness": 0,
    "pWaterSmoothness_Foamy": 0,
    "pWaterSpecularLevel_Foamy": 2,
    "pWaterStrengthTextureLODBias": 0,
    "pWaterStrengthTextureRemap": 3,
    "pWaterStrengthTextureScrollSpeed": 3,
    "pWaterStrengthTextureUVTileRate": 1,
    "pWaterTile": 1,
    "pWaterTile_OscillationAmplitude": 0,
    "pWaterTile_OscillationSpeed": 0,
    "pWaterTile_OscillationSpread": 0,
    "pWaterTile_WaterAmountHeightIncrease": 0,
    "pWaterTilingRate": 1,
    "pWaterUseTexcoords": 6,
    "pWaveChopLod": 0,
    "pWaveChopScale": 0,
    "pWaveHeightLod": 0,
    "pWaveHeightScale": 0,
    "pWaveTiling": 0,
    "pWeather_Enable": 6,
    "pWeather_ExplicitNormalThreshold": 0,
    "pWeather_GrassPoolOffset": 0,
    "pWeather_LocalWaterAmount": 0,
    "pWeight1Power": 0,
    "pWetFlattening": 0,
    "pWetSurfaceRoughness": 0,
    "pWindScale": 0,
    "testing": 0,
    "u_baseColourContrast1": 0,
    "u_baseColourContrast10": 0,
    "u_baseColourContrast11": 0,
    "u_baseColourContrast12": 0,
    "u_baseColourContrast13": 0,
    "u_baseColourContrast14": 0,
    "u_baseColourContrast15": 0,
    "u_baseColourContrast16": 0,
    "u_baseColourContrast2": 0,
    "u_baseColourContrast3": 0,
    "u_baseColourContrast4": 0,
    "u_baseColourContrast5": 0,
    "u_baseColourContrast6": 0,
    "u_baseColourContrast7": 0,
    "u_baseColourContrast8": 0,
    "u_baseColourContrast9": 0,
    "u_baseColourSaturation1": 0,
    "u_baseColourSaturation10": 0,
    "u_baseColourSaturation11": 0,
    "u_baseColourSaturation12": 0,
    "u_baseColourSaturation13": 0,
    "u_baseColourSaturation14": 0,
    "u_baseColourSaturation15": 0,
    "u_baseColourSaturation16": 0,
    "u_baseColourSaturation2": 0,
    "u_baseColourSaturation3": 0,
    "u_baseColourSaturation4": 0,
    "u_baseColourSaturation5": 0,
    "u_baseColourSaturation6": 0,
    "u_baseColourSaturation7": 0,
    "u_baseColourSaturation8": 0,
    "u_baseColourSaturation9": 0,
    "u_colourKey_01_Position": 5,
    "u_colourKey_01_RGB": 2,
    "u_colourKey_02_Position": 5,
    "u_colourKey_02_RGB": 2,
    "u_colourKey_03_Position": 5,
    "u_colourKey_03_RGB": 2,
    "u_colourKey_04_Position": 5,
    "u_colourKey_04_RGB": 2,
    "u_colourKey_05_Position": 5,
    "u_colourKey_05_RGB": 2,
    "u_colourKey_06_Position": 5,
    "u_colourKey_06_RGB": 2,
    "u_colourKey_07_Position": 5,
    "u_colourKey_07_RGB": 2,
    "u_colourKey_08_Position": 5,
    "u_colourKey_08_RGB": 2,
    "u_colourKey_09_Position": 5,
    "u_colourKey_09_RGB": 2,
    "u_colourKey_10_Position": 5,
    "u_colourKey_10_RGB": 2,
    "u_colourKey_11_Position": 5,
    "u_colourKey_11_RGB": 2,
    "u_colourKey_12_Position": 5,
    "u_colourKey_12_RGB": 2,
    "u_emissiveKey_01_Position": 5,
    "u_emissiveKey_01_RGB": 2,
    "u_emissiveKey_02_Position": 5,
    "u_emissiveKey_02_RGB": 2,
    "u_emissiveKey_03_Position": 5,
    "u_emissiveKey_03_RGB": 2,
    "u_emissiveKey_04_Position": 5,
    "u_emissiveKey_04_RGB": 2,
    "u_emissiveKey_05_Position": 5,
    "u_emissiveKey_05_RGB": 2,
    "u_emissiveKey_06_Position": 5,
    "u_emissiveKey_06_RGB": 2,
    "u_emissiveKey_07_Position": 5,
    "u_emissiveKey_07_RGB": 2,
    "u_emissiveKey_08_Position": 5,
    "u_emissiveKey_08_RGB": 2,
    "u_emissiveKey_09_Position": 5,
    "u_emissiveKey_09_RGB": 2,
    "u_emissiveKey_10_Position": 5,
    "u_emissiveKey_10_RGB": 2,
    "u_emissiveKey_11_Position": 5,
    "u_emissiveKey_11_RGB": 2,
    "u_emissiveKey_12_Position": 5,
    "u_emissiveKey_12_RGB": 2,
    "u_enableBaseColourContrast1": 6,
    "u_enableBaseColourContrast10": 6,
    "u_enableBaseColourContrast11": 6,
    "u_enableBaseColourContrast12": 6,
    "u_enableBaseColourContrast13": 6,
    "u_enableBaseColourContrast14": 6,
    "u_enableBaseColourContrast15": 6,
    "u_enableBaseColourContrast16": 6,
    "u_enableBaseColourContrast2": 6,
    "u_enableBaseColourContrast3": 6,
    "u_enableBaseColourContrast4": 6,
    "u_enableBaseColourContrast5": 6,
    "u_enableBaseColourContrast6": 6,
    "u_enableBaseColourContrast7": 6,
    "u_enableBaseColourContrast8": 6,
    "u_enableBaseColourContrast9": 6,
    "u_enableBaseColourSaturation1": 6,
    "u_enableBaseColourSaturation10": 6,
    "u_enableBaseColourSaturation11": 6,
    "u_enableBaseColourSaturation12": 6,
    "u_enableBaseColourSaturation13": 6,
    "u_enableBaseColourSaturation14": 6,
    "u_enableBaseColourSaturation15": 6,
    "u_enableBaseColourSaturation16": 6,
    "u_enableBaseColourSaturation2": 6,
    "u_enableBaseColourSaturation3": 6,
    "u_enableBaseColourSaturation4": 6,
    "u_enableBaseColourSaturation5": 6,
    "u_enableBaseColourSaturation6": 6,
    "u_enableBaseColourSaturation7": 6,
    "u_enableBaseColourSaturation8": 6,
    "u_enableBaseColourSaturation9": 6,
    "u_enableGlobalColourWeight1": 6,
    "u_enableGlobalColourWeight10": 6,
    "u_enableGlobalColourWeight11": 6,
    "u_enableGlobalColourWeight12": 6,
    "u_enableGlobalColourWeight13": 6,
    "u_enableGlobalColourWeight14": 6,
    "u_enableGlobalColourWeight15": 6,
    "u_enableGlobalColourWeight16": 6,
    "u_enableGlobalColourWeight2": 6,
    "u_enableGlobalColourWeight3": 6,
    "u_enableGlobalColourWeight4": 6,
    "u_enableGlobalColourWeight5": 6,
    "u_enableGlobalColourWeight6": 6,
    "u_enableGlobalColourWeight7": 6,
    "u_enableGlobalColourWeight8": 6,
    "u_enableGlobalColourWeight9": 6,
    "u_enableRemapIndex1": 6,
    "u_enableRemapIndex10": 6,
    "u_enableRemapIndex11": 6,
    "u_enableRemapIndex12": 6,
    "u_enableRemapIndex13": 6,
    "u_enableRemapIndex14": 6,
    "u_enableRemapIndex15": 6,
    "u_enableRemapIndex16": 6,
    "u_enableRemapIndex2": 6,
    "u_enableRemapIndex3": 6,
    "u_enableRemapIndex4": 6,
    "u_enableRemapIndex5": 6,
    "u_enableRemapIndex6": 6,
    "u_enableRemapIndex7": 6,
    "u_enableRemapIndex8": 6,
    "u_enableRemapIndex9": 6,
    "u_furTint": 2,
    "u_globalColourBrightnessBase": 0,
    "u_globalColourBrightnessPalette": 0,
    "u_globalColourRotationOffsetBase": 0,
    "u_globalColourRotationOffsetPalette": 0,
    "u_globalColourSaturationBase": 0,
    "u_globalColourSaturationPalette": 0,
    "u_globalColourWeight1": 0,
    "u_globalColourWeight10": 0,
    "u_globalColourWeight11": 0,
    "u_globalColourWeight12": 0,
    "u_globalColourWeight13": 0,
    "u_globalColourWeight14": 0,
    "u_globalColourWeight15": 0,
    "u_globalColourWeight16": 0,
    "u_globalColourWeight2": 0,
    "u_globalColourWeight3": 0,
    "u_globalColourWeight4": 0,
    "u_globalColourWeight5": 0,
    "u_globalColourWeight6": 0,
    "u_globalColourWeight7": 0,
    "u_globalColourWeight8": 0,
    "u_globalColourWeight9": 0,
    "u_globalKeyColour": 2,
    "u_globalKeyThreshold": 0,
    "u_globalKeyTolerance": 0,
    "u_globalKeyType": 5,
    "u_globalPaletteMaximumComplexity": 5,
    "u_globalPaletteSeed": 5,
    "u_instancePaletteOffset": 0,
    "u_instancePaletteScale": 0,
    "u_instancePaletteStrength": 0,
    "u_opacityKey_01_Position": 5,
    "u_opacityKey_01_Value": 0,
    "u_opacityKey_02_Position": 5,
    "u_opacityKey_02_Value": 0,
    "u_opacityKey_03_Position": 5,
    "u_opacityKey_03_Value": 0,
    "u_opacityKey_04_Position": 5,
    "u_opacityKey_04_Value": 0,
    "u_opacityKey_05_Position": 5,
    "u_opacityKey_05_Value": 0,
    "u_opacityKey_06_Position": 5,
    "u_opacityKey_06_Value": 0,
    "u_opacityKey_07_Position": 5,
    "u_opacityKey_07_Value": 0,
    "u_opacityKey_08_Position": 5,
    "u_opacityKey_08_Value": 0,
    "u_patchworkFlags": 5,
    "u_remapIndex1": 5,
    "u_remapIndex10": 5,
    "u_remapIndex11": 5,
    "u_remapIndex12": 5,
    "u_remapIndex13": 5,
    "u_remapIndex14": 5,
    "u_remapIndex15": 5,
    "u_remapIndex16": 5,
    "u_remapIndex2": 5,
    "u_remapIndex3": 5,
    "u_remapIndex4": 5,
    "u_remapIndex5": 5,
    "u_remapIndex6": 5,
    "u_remapIndex7": 5,
    "u_remapIndex8": 5,
    "u_remapIndex9": 5,
    "u_usePatchwork": 6,
    "u_usePatternLUT": 6,
}

textures = {
    "pAOTexture",
    "pAlphaTexture",
    "pBaseAOTexture",
    "pBaseColourTexture",
    "pBaseColourTextureDetailBase",
    "pBaseColourTextureDetailBlend",
    "pBaseDielectricSpecularLevelTexture",
    "pBaseDiffuseTexture",
    "pBaseNormalTexture",
    "pCavityRoughnessDielectricArray",
    "pDetailNormalTexture",
    "pDetailRoughnessTexture",
    "pDetailTexture",
    "pDiffuseAlphaTexture",
    "pDiffuseArray",
    "pDiffuseTexture",
    "pDinosaurFeathers_BaseDiffuseTexture",
    "pEmissiveTexture",
    "pEnvironmentalNoiseMask",
    "pFeathersBaseDiffuseTexture",
    "pFeathers_AOHeightOpacityTransmission_PackedTexture",
    "pFeathers_Aniso_PackedTexture",
    "pFeathers_BaseColourTexture",
    "pFeathers_EmissiveTexture",
    "pFeathers_NormalTexture",
    "pFeathers_RoughnessPackedTexture",
    "pFinAlphaTexture",
    "pFlexiColourMasksTexture",
    "pFoamMapTexture",
    "pFoamyAreasDistantMap",
    "pFullScaleDiffuseAndSpecial",
    "pGradHeightArray",
    "pHeightTexture",
    "pHyperloops_AlphaEmissiveMaskTexture",
    "pHyperloops_DiffuseTexture",
    "pIridescenceMaskTexture",
    "pIridescenceTexture",
    "pLayered_BlendWeights",
    "pLayered_DiffuseTexture",
    "pLayered_HeightTexture",
    "pLayered_PackedTexture",
    "pLayered_RemapTexture",
    "pLayered_WarpOffset",
    "pMacroDiffuse",
    "pModelViewer_GridPatternMap",
    "pMoiseNoiseMask",
    "pMossBaseColour",
    "pMossBaseColourRoughnessPackedTexture",
    "pMossNormalTexture",
    "pMossVarianceTexture",
    "pNoiseTexture",
    "pNormalBlendWeightTexture",
    "pNormalMapTextureUnique",
    "pNormalTexture",
    "pNormalTextureDetailBase",
    "pNormalTextureDetailBlend",
    "pOpacityTexture",
    "pPOM_DisplacementRelaxedConeTexture",
    "pPackedTexture",
    "pPatchBlendMap",
    "pPatterning_FeathersPatchworkGradientMap",
    "pPatterning_FeathersPatternGradientMap",
    "pPatterning_PatchworkGradientMap",
    "pPatterning_PatternGradientMap",
    "pPrimaryBlendMap",
    "pProjection_BackgroundPlaneDiffuseTexture",
    "pProjection_BackgroundPlaneEmissiveTexture",
    "pProjection_DiffuseTexture",
    "pProjection_EmissiveTexture",
    "pProjection_ForegroundPlaneDiffuseTexture",
    "pProjection_ForegroundPlaneEmissiveTexture",
    "pProjection_Plane0Texture",
    "pProjection_Plane1Texture",
    "pProjection_Plane2Texture",
    "pProjection_Texture",
    "pRemapTexture",
    "pRoughnessPackedTexture",
    "pRoughnessTexture",
    "pShellMap",
    "pSpecularTexture",
    "pSubLayerDiffuse0Texture",
    "pSubLayerDiffuse1Texture",
    "pThicknessTexture",
    "pWaterBottomHeight",
    "pWaterDetailGradientMap",
    "pWaterDetailHeightMap",
    "pWaterDetailNormalMapTexture",
    "pWaterDetailSpecMapTexture",
    "pWaterNormalMapTexture",
    "pWaterRipplesTexture",
    "pWaterRoughnessMapTexture",
    "u_basePatchworkMap",
    "u_basePatternMap",
    "u_feathersBasePatchworkMap",
    "u_feathersBasePatternMap",
}

shaders = {
    "Building_BiomeLayer",
    "Collection_Pattern",
    "Depth_Fade",
    "Depth_Pollution",
    "DinosaurFeathers_ClipDoubleSided",
    "DinosaurFur_Vanilla_Base",
    "DinosaurFur_Vanilla_BaseLayered",
    "DinosaurFur_Vanilla_Fin",
    "DinosaurFur_Vanilla_Shell",
    "DinosaurLayered_Layer",
    "DinosaurLayered_Layered_Opaque",
    "DinosaurLayered_Pattern",
    "DinosaurLayered_PatternSet",
    "DinosaurLayered_Swatch_Opaque",
    "DinosaurLayered_Variant",
    "DinosaurLayered_VariantSet",
    "Foliage_Billboard",
    "Foliage_BillboardFading_DetailObject",
    "Foliage_Billboard_DetailObject",
    "Foliage_Clip",
    "Foliage_ClipLeafFading_DetailObject",
    "Foliage_ClipLeaf_DetailObject",
    "Foliage_ClipNoDisplacement",
    "Foliage_ClipTexcoordWeight",
    "Foliage_ClipTexcoordWeightFading_DetailObject",
    "Foliage_ClipTexcoordWeight_DetailObject",
    "Foliage_GrassPrioritisedCull_DetailObject",
    "Foliage_Opaque",
    "Foliage_OpaqueNoDisplacement",
    "Foliage_OpaqueTrunkFading_DetailObject",
    "Foliage_OpaqueTrunk_DetailObject",
    "Galileo_TerrainOverlay",
    "Galileo_Terrain_BespokeSkirtLayers",
    "Galileo_Terrain_BespokeSkirtLayers_Cutout",
    "Game_WeatherParticle",
    "Game_WeatherParticle_AnimatedDust",
    "Game_WeatherParticle_AnimatedSplash",
    "Game_WeatherParticle_CameraDust",
    "Game_WeatherParticle_RainDrop",
    "Game_WeatherParticle_TiledRain",
    "Glass_Textured",
    "Glass_TexturedNormalsTwoSided",
    "Glass_TexturedWeather",
    "Glass_Uniform",
    "Glass_UniformOpaqueWeather",
    "Glass_UniformWeather",
    "Glass_UniformWeatherTwoSided",
    "Ice_Opaque_TriPlanar",
    "Metallic_Roughness_Alpha_Emissive",
    "Metallic_Roughness_Clip_Extrusion2D",
    "Metallic_Roughness_Clip_Geometry_Decal",
    "Metallic_Roughness_Clip_Weather",
    "Metallic_Roughness_Clip_Weather_BC7",
    "Metallic_Roughness_Clip_Weather_DoubleSided_BC7",
    "Metallic_Roughness_Detail_Basic_Opaque_Weather_WithMoss",
    "Metallic_Roughness_Opaque",
    "Metallic_Roughness_OpaqueCable",
    "Metallic_Roughness_OpaqueCheap_Weather",
    "Metallic_Roughness_OpaqueNoFlexi_Weather",
    "Metallic_Roughness_Opaque_BC7",
    "Metallic_Roughness_Opaque_Cavity_Projection_Weather",
    "Metallic_Roughness_Opaque_Emissive",
    "Metallic_Roughness_Opaque_Kerb",
    "Metallic_Roughness_Opaque_Weather",
    "Metallic_Roughness_Opaque_Weather_Emissive_Extrusion2D",
    "Metallic_Roughness_Opaque_Weather_Extrusion2D",
    "ModelViewer_FloorGrid",
    "ParallaxOcclusionMapping_GeometryDecal",
    "Particle_Alpha",
    "Particle_Alpha_AmbientOnly",
    "Particle_Alpha_AmbientOnly_TexBlend",
    "Particle_Alpha_AmbientOnly_WaterOccludee",
    "Particle_Alpha_EmissiveOnly",
    "Particle_Alpha_EmissiveOnly_TexBlend",
    "Particle_Alpha_Modulate",
    "Particle_Alpha_Specular_Normal_TexBlend",
    "Particle_Alpha_TexBlend",
    "Particle_Clip",
    "Particle_Clip_Specular",
    "Particle_Clip_TexBlend",
    "Particle_Refractive",
    "Particle_Volumetric",
    "Particle_VolumetricEmissive_TexBlend",
    "Particle_Volumetric_TexBlend",
    "Perturbation_Invisible",
    "Projection_Interior",
    "Terrain_Edit_Grid",
    "Tornado_Funnel",
    "Tornado_Funnel2",
    "UI_Hyperloops",
    "UI_Transparent",
    "UI_TransparentBillboard",
    "Water_CameraBubble",
    "Water_Water",
    "Water_WaterOccluder",
    "Water_WaterParticle",
    "Water_WaterPool",
    "Water_WaterSimulation",
    "Water_WaterSimulationSkirt",
    "Water_WaterVolume",
    "Water_WaterVolumeSide",
    "WindVectorField_Debug",
}

shader_attribs = {
    "Building_BiomeLayer":
         ['pBlendDistance', 'pBlendMode'],

    "Metallic_Roughness_Opaque_Weather":
         ['pEnableScreenSpaceAO', 'pEnableWeatherPooling', 'pExtrusionScaling', 'pFlexiColourBlended', 'pFlexiColourTexCoordIndex', 'pFlexiColourUseAdditiveBlend', 'pFlexiColourVertexColour', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pPerturbationViewFlag', 'pRenderLayerOverride', 'pSnowOnSlopesOffset', 'pSnowOpacity', 'pVerticalTiling', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_Enable', 'pWeather_ExplicitNormalThreshold'],

    "Metallic_Roughness_Opaque_Emissive":
         ['pEmissiveAdaptiveBrighnessWeight', 'pEmissiveIntensity', 'pEmissiveScrollData', 'pEmissiveTint', 'pEnableEmissiveFlexiColour', 'pEnableScreenSpaceAO', 'pExtrusionScaling', 'pFlexiColourBlended', 'pFlexiColourTexCoordIndex', 'pFlexiColourUseAdditiveBlend', 'pFlexiColourVertexColour', 'pPerturbationViewFlag', 'pRenderLayerOverride', 'pVerticalTiling', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold'],

    "Metallic_Roughness_Opaque_Weather_Emissive_Extrusion2D":
         ['pEmissiveAdaptiveBrighnessWeight', 'pEmissiveIntensity', 'pEmissiveScrollData', 'pEmissiveTint', 'pEnableEmissiveFlexiColour', 'pEnableScreenSpaceAO', 'pEnableWeatherPooling', 'pExtrusionScaling', 'pFlexiColourBlended', 'pFlexiColourTexCoordIndex', 'pFlexiColourUseAdditiveBlend', 'pFlexiColourVertexColour', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pRenderLayerOverride', 'pSnowOnSlopesOffset', 'pSnowOpacity', 'pVerticalTiling', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_Enable', 'pWeather_ExplicitNormalThreshold'],

    "Metallic_Roughness_Clip_Weather":
         ['pAlphaTestRef', 'pEnableAlphaTestRefFade', 'pEnableScreenSpaceAO', 'pEnableWeatherPooling', 'pExtrusionScaling', 'pFlexiColourBlended', 'pFlexiColourTexCoordIndex', 'pFlexiColourUseAdditiveBlend', 'pFlexiColourVertexColour', 'pHighlightAlphaTestRefBias', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pPerturbationViewFlag', 'pRenderLayerOverride', 'pSnowOnSlopesOffset', 'pSnowOpacity', 'pTransmittance', 'pVerticalTiling', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_Enable', 'pWeather_ExplicitNormalThreshold'],

    "Metallic_Roughness_Opaque":
         ['pEnableScreenSpaceAO', 'pExtrusionScaling', 'pFlexiColourBlended', 'pFlexiColourTexCoordIndex', 'pFlexiColourUseAdditiveBlend', 'pFlexiColourVertexColour', 'pPerturbationViewFlag', 'pRenderLayerOverride', 'pVerticalTiling', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold'],

    "Metallic_Roughness_Detail_Basic_Opaque_Weather_WithMoss":
         ['pDetailBaseOffset', 'pDielectricSpecularLevel', 'pEnableScreenSpaceAO', 'pEnableWeatherPooling', 'pEnvironmentalMossEdge', 'pEnvironmentalMossEdgeFalloff', 'pEnvironmentalMossTiling', 'pEnvironmentalMossYaw', 'pExtrusionScaling', 'pMaskNormals', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pMossAmount', 'pMossDielectricSpecularLevel', 'pMossDiscolour', 'pMossDiscolourEdge', 'pMossDiscolourRelativeToHeight', 'pMossEdge', 'pMossEdgeDetail', 'pMossEdgeFalloff', 'pMossHeight', 'pMossHeightVertexColourScale', 'pMossNoiseMaskTilingX', 'pMossNoiseMaskTilingY', 'pMossNormalStrength', 'pMossPitch', 'pMossRockBottomEdgeFalloff', 'pMossRockBottomHeight', 'pMossRockTopEdgeFalloff', 'pMossRockTopHeight', 'pMossSheenAmount', 'pMossSheenTint', 'pMossTiling', 'pMossTypeEnum', 'pMossVarianceAmount', 'pMossVarianceEdge', 'pMossVarianceEdgeFalloff', 'pMossVarianceTiling', 'pMossYaw', 'pRenderLayerOverride', 'pRoughnessDetailBlend', 'pSnowOnSlopesOffset', 'pSnowOpacity', 'pTilingDetailBlend', 'pVerticalTiling', 'pWeather_Enable', 'pWeather_ExplicitNormalThreshold'],

    "Metallic_Roughness_OpaqueNoFlexi_Weather":
         ['pDecals_IsEnabled', 'pEnableScreenSpaceAO', 'pEnableWeatherPooling', 'pExtrusionScaling', 'pFlexiColourBlended', 'pFlexiColourTexCoordIndex', 'pFlexiColourUseAdditiveBlend', 'pFlexiColourVertexColour', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pPerturbationViewFlag', 'pRenderLayerOverride', 'pSnowOnSlopesOffset', 'pSnowOpacity', 'pVerticalTiling', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_Enable', 'pWeather_ExplicitNormalThreshold'],

    "Ice_Opaque_TriPlanar":
         ['pAngleDarkenPower', 'pDetailNormalStrength', 'pDetailTile', 'pDiffuseTint', 'pDirectScatterTransmittance', 'pDirectionalLightTransmittanceOcclusion', 'pEnableRandomSubLayerOffset', 'pEnableScreenSpaceAO', 'pEnableWeatherPooling', 'pExtrusionScaling', 'pFlexiColourBlended', 'pFlexiColourTexCoordIndex', 'pFlexiColourUseAdditiveBlend', 'pFlexiColourVertexColour', 'pIBLScatterTransmittanceSurfaceNormalDistortion', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pNormalMapAngleDarkenStrength', 'pNormalMapRefractionStrength', 'pOpacityScale', 'pRenderLayerOverride', 'pRoughnessRefractionStrength', 'pSSAOScatterReflectionOcclusionStrength', 'pSSRReflectionTransmittanceMip', 'pSSRReflectionTransmittanceScale', 'pSnowOnSlopesOffset', 'pSnowOpacity', 'pSubLayer0', 'pSubLayer0DiffuseTint', 'pSubLayer1', 'pSubLayer1DiffuseTint', 'pSubLayerAOMipBias', 'pSubLayerAOStregnth', 'pSubLayerOpacityMipBias', 'pSubLayerTile', 'pTransmittanceMinimum', 'pTransmittanceScale', 'pUseOrenNayar', 'pVerticalTiling', 'pWeather_Enable', 'pWeather_ExplicitNormalThreshold'],

    "Depth_Fade":
         ['pDepthColour', 'pDepthDistance', 'pExtrusionScaling', 'pRenderLayerOverride', 'pVerticalTiling'],

    "Glass_UniformOpaqueWeather":
         ['pDiffuseTint', 'pEnableScreenSpaceAO', 'pEnableWeatherPooling', 'pExtrusionScaling', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pPerturbationViewFlag', 'pRenderLayerOverride', 'pRoughness', 'pSnowOnSlopesOffset', 'pSnowOpacity', 'pSpecularReflectance', 'pVerticalTiling', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_Enable', 'pWeather_ExplicitNormalThreshold'],

    "Glass_TexturedWeather":
         ['pEnableDiffuseFlexiColour', 'pEnableSpecularFlexiColour', 'pEnableWeatherPooling', 'pExtrusionScaling', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pRenderLayerOverride', 'pSnowOnSlopesOffset', 'pSnowOpacity', 'pVerticalTiling', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_Enable', 'pWeather_ExplicitNormalThreshold'],

    "Glass_TexturedNormalsTwoSided":
         ['pEnableDiffuseFlexiColour', 'pEnableSpecularFlexiColour', 'pEnableWeatherPooling', 'pExtrusionScaling', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pRenderLayerOverride', 'pSnowOnSlopesOffset', 'pSnowOpacity', 'pTransmittance', 'pVerticalTiling', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_Enable', 'pWeather_ExplicitNormalThreshold'],

    "Projection_Interior":
         ['pEnableScreenSpaceAO', 'pEnableWeatherPooling', 'pExtrusionScaling', 'pFlexiColourBlended', 'pFlexiColourTexCoordIndex', 'pFlexiColourUseAdditiveBlend', 'pFlexiColourVertexColour', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pOpacity', 'pOpacityRef', 'pPerturbationViewFlag', 'pProjection_AmbientOcclusion', 'pProjection_AmbientSaturation', 'pProjection_AtlasDimensionU', 'pProjection_AtlasDimensionV', 'pProjection_BackgroundPlaneAtlasRandomSeed', 'pProjection_BackgroundPlanePosition', 'pProjection_BackgroundPlaneUVOffset', 'pProjection_BackgroundPlaneUVTile', 'pProjection_EmissiveBrightness', 'pProjection_EmissiveColour', 'pProjection_EnableVertexAmbientOcclusion', 'pProjection_ForegoundPlanePosition', 'pProjection_ForegroundPlaneAtlasRandomSeed', 'pProjection_ForegroundPlaneUVOffset', 'pProjection_ForegroundPlaneUVTile', 'pProjection_FresnelDarken', 'pProjection_IsBackgroundPlaneAtlasTexCoordEnabled', 'pProjection_IsBackgroundPlaneEnabled', 'pProjection_IsForegroundPlaneAtlasTexCoordEnabled', 'pProjection_IsForegroundPlaneEnabled', 'pProjection_MipBias', 'pProjection_Offset', 'pProjection_Scale', 'pProjection_TexCoordDimensions', 'pProjection_TexCoordIndex', 'pRefractionStrength', 'pRenderLayerOverride', 'pSnowOnSlopesOffset', 'pSnowOpacity', 'pVerticalTiling', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_Enable', 'pWeather_ExplicitNormalThreshold'],

    "Metallic_Roughness_Opaque_BC7":
         ['pEnableScreenSpaceAO', 'pEnableWeatherPooling', 'pExtrusionScaling', 'pFlexiColourBlended', 'pFlexiColourTexCoordIndex', 'pFlexiColourUseAdditiveBlend', 'pFlexiColourVertexColour', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pPerturbationViewFlag', 'pRenderLayerOverride', 'pSnowOnSlopesOffset', 'pSnowOpacity', 'pVerticalTiling', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_Enable', 'pWeather_ExplicitNormalThreshold'],

    "Metallic_Roughness_Clip_Weather_DoubleSided_BC7":
         ['pAlphaTestRef', 'pEnableAlphaTestRefFade', 'pEnableScreenSpaceAO', 'pEnableWeatherPooling', 'pExtrusionScaling', 'pFlexiColourBlended', 'pFlexiColourTexCoordIndex', 'pFlexiColourUseAdditiveBlend', 'pFlexiColourVertexColour', 'pHighlightAlphaTestRefBias', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pPerturbationViewFlag', 'pRenderLayerOverride', 'pSnowOnSlopesOffset', 'pSnowOpacity', 'pTransmittance', 'pVerticalTiling', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_Enable', 'pWeather_ExplicitNormalThreshold'],

    "Metallic_Roughness_OpaqueCheap_Weather":
         ['pEnableScreenSpaceAO', 'pEnableWeatherPooling', 'pExtrusionScaling', 'pFlexiColourBlended', 'pFlexiColourTexCoordIndex', 'pFlexiColourUseAdditiveBlend', 'pFlexiColourVertexColour', 'pFlexicolourMasterMask', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pMetallic', 'pPerturbationViewFlag', 'pRenderLayerOverride', 'pSnowOnSlopesOffset', 'pSnowOpacity', 'pVerticalTiling', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_Enable', 'pWeather_ExplicitNormalThreshold'],

    "Metallic_Roughness_Clip_Geometry_Decal":
         ['pAlphaTestRef', 'pDecals_IsEnabled', 'pEnableAlphaTestRefFade', 'pEnableScreenSpaceAO', 'pEnableWeatherPooling', 'pExtrusionScaling', 'pFlexiColourBlended', 'pFlexiColourTexCoordIndex', 'pFlexiColourUseAdditiveBlend', 'pFlexiColourVertexColour', 'pGeometryDecalAlphaBlendMode', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pRenderLayerOverride', 'pSnowOnSlopesOffset', 'pSnowOpacity', 'pTransmittance', 'pVerticalTiling', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_Enable', 'pWeather_ExplicitNormalThreshold'],

    "ParallaxOcclusionMapping_GeometryDecal":
         ['pAlphaTestRef', 'pEnableAlphaTestRefFade', 'pEnableScreenSpaceAO', 'pEnableWeatherPooling', 'pExtrusionScaling', 'pFlexiColourBlended', 'pFlexiColourTexCoordIndex', 'pFlexiColourUseAdditiveBlend', 'pFlexiColourVertexColour', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pNormalStrength', 'pPOM_AOStrength', 'pPOM_DisplacementStrength', 'pRenderLayerOverride', 'pSnowOnSlopesOffset', 'pSnowOpacity', 'pTransmittance', 'pVerticalTiling', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_Enable', 'pWeather_ExplicitNormalThreshold'],

    "Metallic_Roughness_Clip_Weather_BC7":
         ['pAlphaTestRef', 'pEnableAlphaTestRefFade', 'pEnableScreenSpaceAO', 'pEnableWeatherPooling', 'pExtrusionScaling', 'pFlexiColourBlended', 'pFlexiColourTexCoordIndex', 'pFlexiColourUseAdditiveBlend', 'pFlexiColourVertexColour', 'pHighlightAlphaTestRefBias', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pPerturbationViewFlag', 'pRenderLayerOverride', 'pSnowOnSlopesOffset', 'pSnowOpacity', 'pTransmittance', 'pVerticalTiling', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_Enable', 'pWeather_ExplicitNormalThreshold'],

    "Galileo_TerrainOverlay":
         ['pEnableScreenSpaceAO', 'pEnableWeatherPooling', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pPatternTexCoordScale', 'pPlayAreaBlendFactorScaleOffset', 'pPlayAreaHeightScaleOffset', 'pPlayAreaTexelMetrics', 'pPlayAreaUVScaleOffset', 'pRenderLayerOverride', 'pSkirtMaskScaleOffset', 'pSkirtNormalBlend', 'pSkirtShadowBorderScaleOffset', 'pSnowOnSlopesOffset', 'pSnowOpacity', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_Enable', 'pWeather_ExplicitNormalThreshold'],

    "Metallic_Roughness_Opaque_Kerb":
         ['pEnableScreenSpaceAO', 'pEnableWeatherPooling', 'pExtrusionScaling', 'pFlexiColourBlended', 'pFlexiColourTexCoordIndex', 'pFlexiColourUseAdditiveBlend', 'pFlexiColourVertexColour', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pRenderLayerOverride', 'pSnowOnSlopesOffset', 'pSnowOpacity', 'pVerticalTiling', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_Enable', 'pWeather_ExplicitNormalThreshold'],

    "Metallic_Roughness_OpaqueCable":
         ['pEnableScreenSpaceAO', 'pRenderLayerOverride', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold'],

    "Metallic_Roughness_Opaque_Weather_Extrusion2D":
         ['pEnableScreenSpaceAO', 'pEnableWeatherPooling', 'pExtrusionScaling', 'pFlexiColourBlended', 'pFlexiColourTexCoordIndex', 'pFlexiColourUseAdditiveBlend', 'pFlexiColourVertexColour', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pRenderLayerOverride', 'pSnowOnSlopesOffset', 'pSnowOpacity', 'pVerticalTiling', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_Enable', 'pWeather_ExplicitNormalThreshold'],

    "Metallic_Roughness_Clip_Extrusion2D":
         ['pAlphaTestRef', 'pEnableAlphaTestRefFade', 'pEnableScreenSpaceAO', 'pExtrusionScaling', 'pFlexiColourBlended', 'pFlexiColourTexCoordIndex', 'pFlexiColourUseAdditiveBlend', 'pFlexiColourVertexColour', 'pHighlightAlphaTestRefBias', 'pPerturbationViewFlag', 'pRenderLayerOverride', 'pTransmittance', 'pVerticalTiling', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold'],

    "Collection_Pattern":
         ['pPatternClip', 'pPatternTexCoordOffset', 'pPatternTexCoordScale', 'pPatternTexCoordWrap'],

    "DinosaurLayered_Layered_Opaque":
         ['pAshColour', 'pAshSmoothStepMax', 'pAshSmoothStepMin', 'pDiffuseLevels', 'pEnableScreenSpaceAO', 'pExtrusionScaling', 'pLayered_AshUpwards', 'pLayered_AshWeight', 'pLayered_BlendWeightBatchCount', 'pLayered_EnableWarp', 'pLayered_HeightScale', 'pLayered_LayerCount', 'pLayered_PositionOffset', 'pLayered_PositionScale', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pNormalContrast', 'pPatterning_EmissiveAdaptiveBrighnessWeight', 'pPatterning_EmissiveMaximumBrightness', 'pPerturbationViewFlag', 'pRenderLayerOverride', 'pSnowOnSlopesOffset', 'pVerticalTiling', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_ExplicitNormalThreshold'],

    "DinosaurLayered_Layer":
         ['pDiffuseContrast', 'pDiffuseSaturation', 'pGlobalColouringWeight', 'pHeightBlendScaleA', 'pHeightBlendScaleB', 'pHeightOffset', 'pHeightScale', 'pRemapLutIndex', 'pUVEnableProjection', 'pUVOffset', 'pUVRotationAngle', 'pUVRotationPosition', 'pUVTile'],

    "DinosaurLayered_PatternSet":
         [],

    "DinosaurLayered_Pattern":
         ['u_colourKey_01_Position', 'u_colourKey_01_RGB', 'u_colourKey_02_Position', 'u_colourKey_02_RGB', 'u_colourKey_03_Position', 'u_colourKey_03_RGB', 'u_colourKey_04_Position', 'u_colourKey_04_RGB', 'u_colourKey_05_Position', 'u_colourKey_05_RGB', 'u_colourKey_06_Position', 'u_colourKey_06_RGB', 'u_colourKey_07_Position', 'u_colourKey_07_RGB', 'u_colourKey_08_Position', 'u_colourKey_08_RGB', 'u_colourKey_09_Position', 'u_colourKey_09_RGB', 'u_colourKey_10_Position', 'u_colourKey_10_RGB', 'u_colourKey_11_Position', 'u_colourKey_11_RGB', 'u_colourKey_12_Position', 'u_colourKey_12_RGB', 'u_emissiveKey_01_Position', 'u_emissiveKey_01_RGB', 'u_emissiveKey_02_Position', 'u_emissiveKey_02_RGB', 'u_emissiveKey_03_Position', 'u_emissiveKey_03_RGB', 'u_emissiveKey_04_Position', 'u_emissiveKey_04_RGB', 'u_emissiveKey_05_Position', 'u_emissiveKey_05_RGB', 'u_emissiveKey_06_Position', 'u_emissiveKey_06_RGB', 'u_emissiveKey_07_Position', 'u_emissiveKey_07_RGB', 'u_emissiveKey_08_Position', 'u_emissiveKey_08_RGB', 'u_emissiveKey_09_Position', 'u_emissiveKey_09_RGB', 'u_emissiveKey_10_Position', 'u_emissiveKey_10_RGB', 'u_emissiveKey_11_Position', 'u_emissiveKey_11_RGB', 'u_emissiveKey_12_Position', 'u_emissiveKey_12_RGB', 'u_opacityKey_01_Position', 'u_opacityKey_01_Value', 'u_opacityKey_02_Position', 'u_opacityKey_02_Value', 'u_opacityKey_03_Position', 'u_opacityKey_03_Value', 'u_opacityKey_04_Position', 'u_opacityKey_04_Value', 'u_opacityKey_05_Position', 'u_opacityKey_05_Value', 'u_opacityKey_06_Position', 'u_opacityKey_06_Value', 'u_opacityKey_07_Position', 'u_opacityKey_07_Value', 'u_opacityKey_08_Position', 'u_opacityKey_08_Value', 'u_patchworkFlags', 'u_usePatchwork', 'u_usePatternLUT'],

    "DinosaurLayered_Variant":
         ['u_baseColourContrast1', 'u_baseColourContrast10', 'u_baseColourContrast11', 'u_baseColourContrast12', 'u_baseColourContrast13', 'u_baseColourContrast14', 'u_baseColourContrast15', 'u_baseColourContrast16', 'u_baseColourContrast2', 'u_baseColourContrast3', 'u_baseColourContrast4', 'u_baseColourContrast5', 'u_baseColourContrast6', 'u_baseColourContrast7', 'u_baseColourContrast8', 'u_baseColourContrast9', 'u_baseColourSaturation1', 'u_baseColourSaturation10', 'u_baseColourSaturation11', 'u_baseColourSaturation12', 'u_baseColourSaturation13', 'u_baseColourSaturation14', 'u_baseColourSaturation15', 'u_baseColourSaturation16', 'u_baseColourSaturation2', 'u_baseColourSaturation3', 'u_baseColourSaturation4', 'u_baseColourSaturation5', 'u_baseColourSaturation6', 'u_baseColourSaturation7', 'u_baseColourSaturation8', 'u_baseColourSaturation9', 'u_enableBaseColourContrast1', 'u_enableBaseColourContrast10', 'u_enableBaseColourContrast11', 'u_enableBaseColourContrast12', 'u_enableBaseColourContrast13', 'u_enableBaseColourContrast14', 'u_enableBaseColourContrast15', 'u_enableBaseColourContrast16', 'u_enableBaseColourContrast2', 'u_enableBaseColourContrast3', 'u_enableBaseColourContrast4', 'u_enableBaseColourContrast5', 'u_enableBaseColourContrast6', 'u_enableBaseColourContrast7', 'u_enableBaseColourContrast8', 'u_enableBaseColourContrast9', 'u_enableBaseColourSaturation1', 'u_enableBaseColourSaturation10', 'u_enableBaseColourSaturation11', 'u_enableBaseColourSaturation12', 'u_enableBaseColourSaturation13', 'u_enableBaseColourSaturation14', 'u_enableBaseColourSaturation15', 'u_enableBaseColourSaturation16', 'u_enableBaseColourSaturation2', 'u_enableBaseColourSaturation3', 'u_enableBaseColourSaturation4', 'u_enableBaseColourSaturation5', 'u_enableBaseColourSaturation6', 'u_enableBaseColourSaturation7', 'u_enableBaseColourSaturation8', 'u_enableBaseColourSaturation9', 'u_enableGlobalColourWeight1', 'u_enableGlobalColourWeight10', 'u_enableGlobalColourWeight11', 'u_enableGlobalColourWeight12', 'u_enableGlobalColourWeight13', 'u_enableGlobalColourWeight14', 'u_enableGlobalColourWeight15', 'u_enableGlobalColourWeight16', 'u_enableGlobalColourWeight2', 'u_enableGlobalColourWeight3', 'u_enableGlobalColourWeight4', 'u_enableGlobalColourWeight5', 'u_enableGlobalColourWeight6', 'u_enableGlobalColourWeight7', 'u_enableGlobalColourWeight8', 'u_enableGlobalColourWeight9', 'u_enableRemapIndex1', 'u_enableRemapIndex10', 'u_enableRemapIndex11', 'u_enableRemapIndex12', 'u_enableRemapIndex13', 'u_enableRemapIndex14', 'u_enableRemapIndex15', 'u_enableRemapIndex16', 'u_enableRemapIndex2', 'u_enableRemapIndex3', 'u_enableRemapIndex4', 'u_enableRemapIndex5', 'u_enableRemapIndex6', 'u_enableRemapIndex7', 'u_enableRemapIndex8', 'u_enableRemapIndex9', 'u_furTint', 'u_globalColourBrightnessBase', 'u_globalColourBrightnessPalette', 'u_globalColourRotationOffsetBase', 'u_globalColourRotationOffsetPalette', 'u_globalColourSaturationBase', 'u_globalColourSaturationPalette', 'u_globalColourWeight1', 'u_globalColourWeight10', 'u_globalColourWeight11', 'u_globalColourWeight12', 'u_globalColourWeight13', 'u_globalColourWeight14', 'u_globalColourWeight15', 'u_globalColourWeight16', 'u_globalColourWeight2', 'u_globalColourWeight3', 'u_globalColourWeight4', 'u_globalColourWeight5', 'u_globalColourWeight6', 'u_globalColourWeight7', 'u_globalColourWeight8', 'u_globalColourWeight9', 'u_globalKeyColour', 'u_globalKeyThreshold', 'u_globalKeyTolerance', 'u_globalKeyType', 'u_globalPaletteMaximumComplexity', 'u_globalPaletteSeed', 'u_instancePaletteOffset', 'u_instancePaletteScale', 'u_instancePaletteStrength', 'u_remapIndex1', 'u_remapIndex10', 'u_remapIndex11', 'u_remapIndex12', 'u_remapIndex13', 'u_remapIndex14', 'u_remapIndex15', 'u_remapIndex16', 'u_remapIndex2', 'u_remapIndex3', 'u_remapIndex4', 'u_remapIndex5', 'u_remapIndex6', 'u_remapIndex7', 'u_remapIndex8', 'u_remapIndex9'],

    "DinosaurLayered_VariantSet":
         ['pEnableBaseDiffuseTexture', 'pEnableFeathersBaseDiffuseTexture', 'pEnableNormalContrast', 'pNormalContrast'],

    "DinosaurLayered_Swatch_Opaque":
         ['pAshColour', 'pAshSmoothStepMax', 'pAshSmoothStepMin', 'pEnableScreenSpaceAO', 'pExtrusionScaling', 'pGlobalColouringWeight', 'pGlobalEffectModifier', 'pLayered_AshUpwards', 'pLayered_AshWeight', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pPerturbationViewFlag', 'pRenderLayerOverride', 'pSnowOnSlopesOffset', 'pVerticalTiling', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_ExplicitNormalThreshold'],

    "Terrain_Edit_Grid":
         ['pEmissiveIntensity', 'pEmissiveScrollData', 'pEmissiveTint', 'pEnableEmissiveFlexiColour', 'pRenderLayerOverride', 'pTriPlanarTile'],

    "Water_WaterVolume":
         ['pDiffuseHeightVarianceOcclusionBias', 'pEnableNearPlaneAvoidance', 'pExtrusionScaling', 'pIncreaseRoughnessByRainIntensity', 'pRainRipplesIntensity', 'pReflectionDistortion', 'pRefractionDistortion', 'pRenderLayerOverride', 'pScatterHeightVarianceOcclusionBias', 'pSpecularHeightVarianceOcclusionBias', 'pVerticalTiling', 'pWaterDetailIntensity', 'pWaterDetailMipBias', 'pWaterDetailMipBiasMinimum', 'pWaterDetailParallaxAmount', 'pWaterDetailParallaxCentre', 'pWaterDetailPlayRate', 'pWaterDetailRoughness', 'pWaterDetailScrollSpeed', 'pWaterDetailTile', 'pWaterFogging', 'pWaterIsUnderside', 'pWaterNormalIntensity', 'pWaterParallaxAmount', 'pWaterParallaxCentre', 'pWaterRoughnessFadeDitherWeight', 'pWaterRoughnessFadePower', 'pWaterScattering', 'pWaterScrollSpeed0', 'pWaterScrollSpeed1', 'pWaterStrengthTextureLODBias', 'pWaterStrengthTextureRemap', 'pWaterStrengthTextureScrollSpeed', 'pWaterStrengthTextureUVTileRate', 'pWaterTile', 'pWaveChopScale', 'pWaveHeightScale', 'pWaveTiling'],

    "Water_WaterSimulation":
         ['pDiffuseHeightVarianceOcclusionBias', 'pFoamMultiplier', 'pFoamTile1', 'pFoamTile2', 'pIncreaseRoughnessByRainIntensity', 'pIncreaseRoughnessByWindSpeed', 'pReflectionDistortion', 'pRefractionDistortion', 'pRenderLayerOverride', 'pScatterHeightVarianceOcclusionBias', 'pScrollSpeed0', 'pScrollSpeed1', 'pSpecularHeightVarianceOcclusionBias', 'pWaterDetailMipBias', 'pWaterDetailTile', 'pWaterDetailWeights', 'pWaterDiffuse_Foamy', 'pWaterEdgeOpacityScale', 'pWaterFoamSpeed1', 'pWaterFoamSpeed2', 'pWaterFogging', 'pWaterIsUnderside', 'pWaterRoughnessFadeDitherWeight', 'pWaterRoughnessFadePower', 'pWaterScattering', 'pWaterSmoothness', 'pWaterSmoothness_Foamy', 'pWaterSpecularLevel_Foamy', 'pWaveChopLod', 'pWaveChopScale', 'pWaveHeightLod', 'pWaveHeightScale', 'pWaveTiling'],

    "Water_WaterSimulationSkirt":
         ['pDiffuseHeightVarianceOcclusionBias', 'pFoamMultiplier', 'pFoamTile1', 'pFoamTile2', 'pIncreaseRoughnessByRainIntensity', 'pIncreaseRoughnessByWindSpeed', 'pReflectionDistortion', 'pRefractionDistortion', 'pRenderLayerOverride', 'pScatterHeightVarianceOcclusionBias', 'pScrollSpeed0', 'pScrollSpeed1', 'pSpecularHeightVarianceOcclusionBias', 'pWaterDetailMipBias', 'pWaterDetailTile', 'pWaterDetailWeights', 'pWaterDiffuse_Foamy', 'pWaterEdgeOpacityScale', 'pWaterFoamSpeed1', 'pWaterFoamSpeed2', 'pWaterFogging', 'pWaterIsUnderside', 'pWaterRoughnessFadeDitherWeight', 'pWaterRoughnessFadePower', 'pWaterScattering', 'pWaterSmoothness', 'pWaterSmoothness_Foamy', 'pWaterSpecularLevel_Foamy', 'pWaveChopScale', 'pWaveHeightScale', 'pWaveTiling'],

    "Water_Water":
         ['pDiffuseHeightVarianceOcclusionBias', 'pExtrusionScaling', 'pIncreaseRoughnessByRainIntensity', 'pRainRipplesIntensity', 'pReflectionDistortion', 'pRefractionDistortion', 'pRenderLayerOverride', 'pScatterHeightVarianceOcclusionBias', 'pScrollSpeed0', 'pScrollSpeed1', 'pSpecularHeightVarianceOcclusionBias', 'pVerticalTiling', 'pWaterDetailMipBias', 'pWaterDetailNormalIntensity', 'pWaterDetailTile', 'pWaterFogging', 'pWaterIsUnderside', 'pWaterRoughnessFadeDitherWeight', 'pWaterRoughnessFadePower', 'pWaterScattering', 'pWaterTilingRate', 'pWaterUseTexcoords', 'pWaveChopScale', 'pWaveHeightScale', 'pWaveTiling'],

    "Water_WaterPool":
         ['pDiffuseHeightVarianceOcclusionBias', 'pIncreaseRoughnessByRainIntensity', 'pRainRipplesIntensity', 'pReflectionDistortion', 'pRefractionDistortion', 'pRenderLayerOverride', 'pScatterHeightVarianceOcclusionBias', 'pSpecularHeightVarianceOcclusionBias', 'pWaterDetailIntensity', 'pWaterDetailMipBias', 'pWaterDetailMipBiasMinimum', 'pWaterDetailParallaxAmount', 'pWaterDetailParallaxCentre', 'pWaterDetailPlayRate', 'pWaterDetailRoughness', 'pWaterDetailScrollSpeed', 'pWaterDetailTile', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWaterFogging', 'pWaterIsUnderside', 'pWaterNormalIntensity', 'pWaterParallaxAmount', 'pWaterParallaxCentre', 'pWaterRoughnessFadeDitherWeight', 'pWaterRoughnessFadePower', 'pWaterScattering', 'pWaterScrollSpeed0', 'pWaterScrollSpeed1', 'pWaterStrengthTextureLODBias', 'pWaterStrengthTextureRemap', 'pWaterStrengthTextureScrollSpeed', 'pWaterStrengthTextureUVTileRate', 'pWaterTile', 'pWaterTile_OscillationAmplitude', 'pWaterTile_OscillationSpeed', 'pWaterTile_OscillationSpread', 'pWaterTile_WaterAmountHeightIncrease', 'pWaveChopScale', 'pWaveHeightScale', 'pWaveTiling'],

    "Water_WaterParticle":
         ['pColour', 'pEnableScreenSpaceAO', 'pFalloff', 'pLightingParticleVolumeBetaMieExtScale', 'pLightingParticleVolumeMieDensity', 'pLightingParticleVolumeMieDirectivity0', 'pLightingParticleVolumeMieDirectivity1', 'pLightingParticleVolumeMieDirectivityWeight', 'pParticleExpands', 'pParticleExpandsFinalScale', 'pParticleFacesCamera', 'pParticleFadeCollapse', 'pParticleFadeInTimeProportion', 'pParticleFadeOutTimeProportion', 'pParticleGravity', 'pParticleInitialVerticalSpeed', 'pParticleNormalType', 'pParticleRotationSpeed', 'pParticleRotationSpeedVariation', 'pParticleSize', 'pParticleSizeVariation', 'pParticleSoftDepth', 'pRelativeFalloff', 'pRenderLayerOverride', 'pUnderwaterOnly'],

    "Water_WaterVolumeSide":
         ['pDiffuseHeightVarianceOcclusionBias', 'pEnableNearPlaneAvoidance', 'pExtrusionScaling', 'pReflectionDistortion', 'pRefractionDistortion', 'pRenderLayerOverride', 'pScatterHeightVarianceOcclusionBias', 'pSpecularHeightVarianceOcclusionBias', 'pVerticalTiling', 'pWaterEdgeOpacityScale', 'pWaterFogging', 'pWaterNormalIntensity', 'pWaterRoughnessFadeDitherWeight', 'pWaterRoughnessFadePower', 'pWaterScattering'],

    "Game_WeatherParticle_AnimatedDust":
         ['pEmissiveIntensity', 'pEmissivePower', 'pOpacity', 'pRenderLayerOverride'],

    "Game_WeatherParticle_AnimatedSplash":
         ['pEmissiveIntensity', 'pEmissiveTint', 'pOpacity', 'pRenderLayerOverride'],

    "Game_WeatherParticle_CameraDust":
         ['pEmissiveIntensity', 'pFaceCamera', 'pForwardFadeOffset', 'pForwardFadeScale', 'pNumFramesX', 'pNumFramesY', 'pOpacity', 'pRenderLayerOverride'],

    "Game_WeatherParticle_RainDrop":
         ['pEmissiveIntensity', 'pEmissiveTint', 'pFaceCamera', 'pForwardFadeOffset', 'pForwardFadeScale', 'pNumFramesX', 'pNumFramesY', 'pOpacity', 'pRenderLayerOverride'],

    "Game_WeatherParticle_TiledRain":
         ['pEmissiveIntensity', 'pEmissiveTint', 'pFaceCamera', 'pForwardFadeOffset', 'pForwardFadeScale', 'pNumFramesX', 'pNumFramesY', 'pOpacity', 'pRenderLayerOverride'],

    "Tornado_Funnel":
         ['pRenderLayerOverride', 'pShadowStrength', 'pTintRampRate', 'pTintRampStart'],

    "Tornado_Funnel2":
         ['pRenderLayerOverride', 'pShadowStrength'],

    "Game_WeatherParticle":
         ['pEmissiveIntensity', 'pEmissiveTint', 'pOpacity', 'pRenderLayerOverride'],

    "WindVectorField_Debug":
         ['pRenderLayerOverride'],

    "Particle_Alpha_AmbientOnly":
         ['pEmissiveAdaptiveBrighnessWeight', 'pEmissiveBlend', 'pEmissiveScale', 'pEnableScreenSpaceAO', 'pFalloff', 'pLightingParticleVolumeBetaMieExtScale', 'pLightingParticleVolumeMieDensity', 'pLightingSurfaceDiffuseWrap', 'pParticleFadeCollapse', 'pParticleNormalType', 'pParticleSoftDepth', 'pRelativeFalloff', 'pRenderLayerOverride', 'pUnderwaterOnly', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold'],

    "Particle_Alpha_AmbientOnly_WaterOccludee":
         ['pEmissiveAdaptiveBrighnessWeight', 'pEmissiveBlend', 'pEmissiveScale', 'pEnableScreenSpaceAO', 'pFalloff', 'pLightingParticleVolumeBetaMieExtScale', 'pLightingParticleVolumeMieDensity', 'pLightingSurfaceDiffuseWrap', 'pParticleFadeCollapse', 'pParticleNormalType', 'pParticleSoftDepth', 'pRelativeFalloff', 'pRenderLayerOverride', 'pUnderwaterOnly', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold'],

    "Particle_Alpha_AmbientOnly_TexBlend":
         ['pEmissiveAdaptiveBrighnessWeight', 'pEmissiveBlend', 'pEmissiveScale', 'pEnableScreenSpaceAO', 'pFalloff', 'pLightingParticleVolumeBetaMieExtScale', 'pLightingParticleVolumeMieDensity', 'pLightingSurfaceDiffuseWrap', 'pMotionBlendStrength', 'pParticleFadeCollapse', 'pParticleNormalType', 'pParticleSoftDepth', 'pRelativeFalloff', 'pRenderLayerOverride', 'pUnderwaterOnly', 'pUseMotionVectors', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold'],

    "Particle_Alpha_EmissiveOnly":
         ['pEmissiveAdaptiveBrighnessWeight', 'pEmissiveScale', 'pFalloff', 'pLightingSurfaceDiffuseWrap', 'pParticleFadeCollapse', 'pParticleNormalType', 'pParticleSoftDepth', 'pRelativeFalloff', 'pRenderLayerOverride', 'pUnderwaterOnly', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold'],

    "Particle_Alpha_EmissiveOnly_TexBlend":
         ['pEmissiveAdaptiveBrighnessWeight', 'pEmissiveScale', 'pFalloff', 'pLightingSurfaceDiffuseWrap', 'pMotionBlendStrength', 'pParticleFadeCollapse', 'pParticleNormalType', 'pParticleSoftDepth', 'pRelativeFalloff', 'pRenderLayerOverride', 'pUnderwaterOnly', 'pUseMotionVectors', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold'],

    "Particle_Alpha":
         ['pEmissiveAdaptiveBrighnessWeight', 'pEmissiveBlend', 'pEmissiveScale', 'pEnableScreenSpaceAO', 'pFalloff', 'pLightingParticleVolumeBetaMieExtScale', 'pLightingParticleVolumeMieDensity', 'pLightingParticleVolumeMieDirectivity0', 'pLightingParticleVolumeMieDirectivity1', 'pLightingParticleVolumeMieDirectivityWeight', 'pLightingSurfaceDiffuseWrap', 'pParticleFadeCollapse', 'pParticleNormalType', 'pParticleSoftDepth', 'pRelativeFalloff', 'pRenderLayerOverride', 'pUnderwaterOnly', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold'],

    "Particle_Alpha_TexBlend":
         ['pEmissiveAdaptiveBrighnessWeight', 'pEmissiveBlend', 'pEmissiveScale', 'pEnableScreenSpaceAO', 'pFalloff', 'pLightingParticleVolumeBetaMieExtScale', 'pLightingParticleVolumeMieDensity', 'pLightingParticleVolumeMieDirectivity0', 'pLightingParticleVolumeMieDirectivity1', 'pLightingParticleVolumeMieDirectivityWeight', 'pLightingSurfaceDiffuseWrap', 'pMotionBlendStrength', 'pParticleFadeCollapse', 'pParticleNormalType', 'pParticleSoftDepth', 'pRelativeFalloff', 'pRenderLayerOverride', 'pUnderwaterOnly', 'pUseMotionVectors', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold'],

    "Particle_Alpha_Modulate":
         ['pEmissiveAdaptiveBrighnessWeight', 'pEmissiveBlend', 'pEmissiveScale', 'pEnableScreenSpaceAO', 'pFalloff', 'pLightingParticleVolumeBetaMieExtScale', 'pLightingParticleVolumeMieDensity', 'pLightingParticleVolumeMieDirectivity0', 'pLightingParticleVolumeMieDirectivity1', 'pLightingParticleVolumeMieDirectivityWeight', 'pLightingSurfaceDiffuseWrap', 'pParticleFadeCollapse', 'pParticleNormalType', 'pParticleSoftDepth', 'pRelativeFalloff', 'pRenderLayerOverride', 'pUnderwaterOnly', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold'],

    "Particle_Clip":
         ['pAlphaTestRef', 'pEmissiveAdaptiveBrighnessWeight', 'pEmissiveBlend', 'pEmissiveScale', 'pEnableAlphaTestRefFade', 'pEnableScreenSpaceAO', 'pLightingParticleVolumeBetaMieExtScale', 'pLightingParticleVolumeMieDensity', 'pLightingParticleVolumeMieDirectivity0', 'pLightingParticleVolumeMieDirectivity1', 'pLightingParticleVolumeMieDirectivityWeight', 'pLightingSurfaceDiffuseWrap', 'pParticleFadeCollapse', 'pParticleNormalType', 'pRenderLayerOverride'],

    "Particle_Clip_TexBlend":
         ['pAlphaTestRef', 'pEmissiveAdaptiveBrighnessWeight', 'pEmissiveBlend', 'pEmissiveScale', 'pEnableAlphaTestRefFade', 'pEnableScreenSpaceAO', 'pLightingParticleVolumeBetaMieExtScale', 'pLightingParticleVolumeMieDensity', 'pLightingParticleVolumeMieDirectivity0', 'pLightingParticleVolumeMieDirectivity1', 'pLightingParticleVolumeMieDirectivityWeight', 'pLightingSurfaceDiffuseWrap', 'pMotionBlendStrength', 'pParticleFadeCollapse', 'pParticleNormalType', 'pRenderLayerOverride', 'pUseMotionVectors'],

    "Particle_Clip_Specular":
         ['pAlphaTestRef', 'pEnableAlphaTestRefFade', 'pEnableScreenSpaceAO', 'pLightingParticleVolumeBetaMieExtScale', 'pLightingParticleVolumeMieDensity', 'pLightingParticleVolumeMieDirectivity0', 'pLightingParticleVolumeMieDirectivity1', 'pLightingParticleVolumeMieDirectivityWeight', 'pLightingSurfaceDiffuseWrap', 'pParticleFadeCollapse', 'pParticleNormalType', 'pRenderLayerOverride', 'pRoughness'],

    "Particle_Refractive":
         ['pDistortionOpacityThreshold', 'pDistortionScale', 'pFalloff', 'pParticleFadeCollapse', 'pParticleNormalType', 'pParticleSoftDepth', 'pRelativeFalloff', 'pRenderLayerOverride', 'pUnderwaterOnly'],

    "Particle_Volumetric_TexBlend":
         ['pDirectionalScatterOcclusionScale', 'pLightingParticleVolumeAdaptiveBrighnessWeight', 'pLightingParticleVolumeBetaMieExtScale', 'pLightingParticleVolumeBrightnessScale', 'pLightingParticleVolumeDirectivityAttenuation', 'pLightingParticleVolumeLightOpticalDepthAttenuation', 'pLightingParticleVolumeMieDensity', 'pLightingParticleVolumeMieDirectivity0', 'pLightingParticleVolumeMieDirectivity1', 'pLightingParticleVolumeMieDirectivityWeight', 'pLightingParticleVolumeTransmittanceAttenuation', 'pLightingVolumeDiffuseTextureStrength', 'pLightingVolumeOpacityTextureCurve', 'pLightingVolumeOpacityTextureScale', 'pMotionBlendStrength', 'pParticleFadeCollapse', 'pParticleNormalType', 'pRenderLayerOverride', 'pUseMotionVectors', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold'],

    "Particle_Volumetric":
         ['pDirectionalScatterOcclusionScale', 'pLightingParticleVolumeAdaptiveBrighnessWeight', 'pLightingParticleVolumeBetaMieExtScale', 'pLightingParticleVolumeBrightnessScale', 'pLightingParticleVolumeDirectivityAttenuation', 'pLightingParticleVolumeLightOpticalDepthAttenuation', 'pLightingParticleVolumeMieDensity', 'pLightingParticleVolumeMieDirectivity0', 'pLightingParticleVolumeMieDirectivity1', 'pLightingParticleVolumeMieDirectivityWeight', 'pLightingParticleVolumeTransmittanceAttenuation', 'pLightingVolumeDiffuseTextureStrength', 'pLightingVolumeOpacityTextureCurve', 'pLightingVolumeOpacityTextureScale', 'pParticleFadeCollapse', 'pParticleNormalType', 'pRenderLayerOverride', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold'],

    "Particle_VolumetricEmissive_TexBlend":
         ['pDirectionalScatterOcclusionScale', 'pLightingParticleVolumeAdaptiveBrighnessWeight', 'pLightingParticleVolumeBetaMieExtScale', 'pLightingParticleVolumeBrightnessScale', 'pLightingParticleVolumeDirectivityAttenuation', 'pLightingParticleVolumeLightOpticalDepthAttenuation', 'pLightingParticleVolumeMieDensity', 'pLightingParticleVolumeMieDirectivity0', 'pLightingParticleVolumeMieDirectivity1', 'pLightingParticleVolumeMieDirectivityWeight', 'pLightingParticleVolumeTransmittanceAttenuation', 'pLightingVolumeDiffuseTextureStrength', 'pLightingVolumeOpacityTextureCurve', 'pLightingVolumeOpacityTextureScale', 'pMotionBlendStrength', 'pParticleFadeCollapse', 'pParticleNormalType', 'pRenderLayerOverride', 'pUseMotionVectors', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold'],

    "Particle_Alpha_Specular_Normal_TexBlend":
         ['pAlphaToOpacityRemap', 'pDirectionalScatterOcclusionScale', 'pFalloff', 'pLightingParticleVolumeAdaptiveBrighnessWeight', 'pLightingParticleVolumeBetaMieExtScale', 'pLightingParticleVolumeBrightnessScale', 'pLightingParticleVolumeDirectivityAttenuation', 'pLightingParticleVolumeLightOpticalDepthAttenuation', 'pLightingParticleVolumeMieDensity', 'pLightingParticleVolumeMieDirectivity0', 'pLightingParticleVolumeMieDirectivity1', 'pLightingParticleVolumeMieDirectivityWeight', 'pLightingParticleVolumeTransmittanceAttenuation', 'pMotionBlendStrength', 'pNormalStrength', 'pParticleFadeCollapse', 'pParticleNormalType', 'pParticleSoftDepth', 'pPerceptualRoughness', 'pRelativeFalloff', 'pRenderLayerOverride', 'pScatteringAlbedoScale', 'pScreenDistortionStrength', 'pSpecularReflectance', 'pUnderwaterOnly', 'pUseMotionVectors', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold'],

    "DinosaurFur_Vanilla_Base":
         ['gAnisotropicStrength', 'gDirectionScale', 'gLodFade', 'gWetHairBaseDirectionStrength', 'gWetHairDirectionStrength', 'gWetHairDownwardPush', 'pAnisoNormalBend', 'pDiffuseLevels', 'pEnableScreenSpaceAO', 'pExtrusionScaling', 'pFurDepthScale', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pNormalContrast', 'pPatterning_EmissiveAdaptiveBrighnessWeight', 'pPatterning_EmissiveMaximumBrightness', 'pPerturbationViewFlag', 'pRenderLayerOverride', 'pSnowOnSlopesOffset', 'pVerticalTiling', 'pWeather_ExplicitNormalThreshold', 'pWetFlattening', 'pWetSurfaceRoughness'],

    "DinosaurFur_Vanilla_BaseLayered":
         ['gAnisotropicStrength', 'gDirectionScale', 'gLodFade', 'gWetHairBaseDirectionStrength', 'gWetHairDirectionStrength', 'gWetHairDownwardPush', 'pAnisoNormalBend', 'pDiffuseLevels', 'pEnableScreenSpaceAO', 'pExtrusionScaling', 'pFurDepthScale', 'pLayered_BlendWeightBatchCount', 'pLayered_EnableWarp', 'pLayered_HeightScale', 'pLayered_LayerCount', 'pLayered_PositionOffset', 'pLayered_PositionScale', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pNormalContrast', 'pPatterning_EmissiveAdaptiveBrighnessWeight', 'pPatterning_EmissiveMaximumBrightness', 'pPerturbationViewFlag', 'pRenderLayerOverride', 'pSnowOnSlopesOffset', 'pVerticalTiling', 'pWeather_ExplicitNormalThreshold', 'pWetFlattening', 'pWetSurfaceRoughness'],

    "DinosaurFeathers_ClipDoubleSided":
         ['pAlphaTestRef', 'pAniso_DirectionOffset', 'pAniso_IsBody', 'pAniso_LengthStraightenStrength', 'pAniso_Strength', 'pDepthBias', 'pDinoWind_JitterSpeed', 'pDinoWind_JitterSpread', 'pDinoWind_JitterStrength', 'pDinoWind_Strength', 'pDinoWind_WindSizeScale', 'pDinoWind_WindStrength', 'pEnableAlphaTestRefFade', 'pEnableScreenSpaceAO', 'pExtrusionScaling', 'pFlexiColourBlended', 'pFlexiColourTexCoordIndex', 'pFlexiColourUseAdditiveBlend', 'pFlexiColourVertexColour', 'pHighlightAlphaTestRefBias', 'pIridescenceAmount', 'pIridescenceColourRange', 'pIridescenceCurve', 'pIridescenceFilmThickness', 'pIridescenceHueRange', 'pIridescenceHueRoll', 'pLengthTransmissionStrength', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pRenderLayerOverride', 'pSnowOnSlopesOffset', 'pSurfaceNormalDistortion', 'pTransmissionAmbient', 'pTransmissionColourTint', 'pTransmissionFalloff', 'pTransmissionIridescenceTint', 'pTransmissionScale', 'pVerticalTiling', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_ExplicitNormalThreshold', 'pWetSurfaceRoughness'],

    "DinosaurFur_Vanilla_Fin":
         ['gAnisotropicStrength', 'gDirectionScale', 'gFinBrushScale', 'gLodFade', 'gWetHairBaseDirectionStrength', 'gWetHairDirectionStrength', 'gWetHairDownwardPush', 'pAlphaClip', 'pAlphaTestRef', 'pAnisoNormalBend', 'pDiffuseLevels', 'pDiffuseTransmittance', 'pDinoWind_JitterSpeed', 'pDinoWind_JitterSpread', 'pDinoWind_JitterStrength', 'pDinoWind_Strength', 'pDinoWind_WindSizeScale', 'pDinoWind_WindStrength', 'pEnableAlphaTestRefFade', 'pEnableScreenSpaceAO', 'pExtrusionScaling', 'pFinAxisFade', 'pFinCorpseAlpha', 'pFinNormalBend', 'pFinNormalCurveBend', 'pFinOpacity', 'pFinRimFade', 'pFinTilingRate', 'pFurDepthScale', 'pFurSpecularDepthScale', 'pIBLRoughnessTweak', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pMipBias', 'pNormalContrast', 'pPatterning_EmissiveAdaptiveBrighnessWeight', 'pPatterning_EmissiveMaximumBrightness', 'pRenderLayerOverride', 'pSnowOnSlopesOffset', 'pSurfaceNormalDistortion', 'pTransmissionColour', 'pTransmissionFalloff', 'pTransmissionRoughness', 'pVerticalTiling', 'pWeather_ExplicitNormalThreshold', 'pWetFlattening', 'pWetSurfaceRoughness'],

    "DinosaurFur_Vanilla_Shell":
         ['gAnisotropicStrength', 'gBendStretchScale', 'gDirectionScale', 'gHeightStretchScale', 'gLodFade', 'gShellClumping', 'gShellUVStretchPower', 'gWetClumping', 'gWetHairBaseDirectionStrength', 'gWetHairDirectionStrength', 'gWetHairDownwardPush', 'pAnisoNormalBend', 'pDiffuseLevels', 'pDiffuseTransmittance', 'pDinoWind_FurDirectionScale', 'pDinoWind_JitterMax', 'pDinoWind_JitterSpeed', 'pDinoWind_JitterSpread', 'pDinoWind_JitterStrength', 'pDinoWind_NormalBend', 'pDinoWind_ShellDisplacementMin', 'pDinoWind_ShellDisplacementRange', 'pDinoWind_Strength', 'pDinoWind_WindSizeScale', 'pDinoWind_WindStrength', 'pDinosaurFur_OverrideShellCount', 'pEnableScreenSpaceAO', 'pExtrusionScaling', 'pFurDepthScale', 'pIBLRoughnessTweak', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pMipBias', 'pNormalContrast', 'pPatterning_EmissiveAdaptiveBrighnessWeight', 'pPatterning_EmissiveMaximumBrightness', 'pRenderLayerOverride', 'pShellCorpseAlphaCut', 'pShellOpacity', 'pShellRimFade', 'pShellRimNudge', 'pShellTilingRate', 'pSnowOnSlopesOffset', 'pSurfaceNormalDistortion', 'pTransmissionColour', 'pTransmissionFalloff', 'pTransmissionRoughness', 'pVerticalTiling', 'pWeather_ExplicitNormalThreshold', 'pWetFlattening', 'pWetSurfaceRoughness'],

    "Foliage_Opaque":
         ['pBarkNormalStrength', 'pCrownRadius', 'pEnableMoss', 'pEnableScreenSpaceAO', 'pEnableVertexAO', 'pIsSpeedTree', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pMossEdge', 'pMossEdgeFalloff', 'pMossNoiseMaskTilingX', 'pMossNoiseMaskTilingY', 'pMossNormalStrength', 'pMossProjectionBreaker', 'pMossTiling', 'pMossTrunkBaseEdgeFalloff', 'pMossTrunkBaseHeight', 'pMossYaw', 'pNormalizeType', 'pObjectPressScale', 'pOffset0', 'pOffset1', 'pOffset2', 'pRenderLayerOverride', 'pScale0', 'pScale1', 'pScale1Normal', 'pScale2', 'pScale2Normal', 'pSnowOnSlopesOffset', 'pTransmittance', 'pTrunkHeight', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_ExplicitNormalThreshold', 'pWeight1Power'],

    "UI_TransparentBillboard":
         ['isHorizontal', 'pAlphaBlendWeight', 'pEmissiveIntensity', 'pEmissiveScrollData', 'pEmissiveTint', 'pEnableAlphaScrolling', 'pEnableFresnelOpacity', 'pFlexiColourBlended', 'pFlexiColourTexCoordIndex', 'pFlexiColourUseAdditiveBlend', 'pFlexiColourVertexColour', 'pFresnelPower', 'pIsSpeedTree', 'pOcclusionDistance', 'pOcclusionEmissiveIntensity', 'pOcclusionEmissiveTint0', 'pOcclusionEmissiveTint1', 'pOcclusionOpacity', 'pOpacityScale', 'pRenderLayerOverride', 'testing'],

    "UI_Transparent":
         ['pAlphaBlendWeight', 'pEmissiveIntensity', 'pEmissiveScrollData', 'pEmissiveTint', 'pEnableAlphaScrolling', 'pEnableFresnelOpacity', 'pExtrusionScaling', 'pFlexiColourBlended', 'pFlexiColourTexCoordIndex', 'pFlexiColourUseAdditiveBlend', 'pFlexiColourVertexColour', 'pFresnelPower', 'pOcclusionDistance', 'pOcclusionEmissiveIntensity', 'pOcclusionEmissiveTint0', 'pOcclusionEmissiveTint1', 'pOcclusionOpacity', 'pOpacityScale', 'pRenderLayerOverride', 'pVerticalTiling'],

    "Foliage_Billboard":
         ['pAlphaTestRef', 'pAmbientTransmissionAmount', 'pAmbientTransmissionTint', 'pDielectricReflectivity', 'pEnableAlphaTestRefFade', 'pHighlightAlphaTestRefBias', 'pIsSpeedTree', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pMipBias', 'pRenderLayerOverride', 'pRoughness', 'pScreenSpaceAOStrength', 'pSnowOnSlopesOffset', 'pTransmittanceScale', 'pUseExplicitNormals', 'pUseTwoSidedExplicitNormal', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_ExplicitNormalThreshold'],

    "Foliage_Billboard_DetailObject":
         ['pAlphaTestRef', 'pAmbientTransmissionAmount', 'pAmbientTransmissionTint', 'pDielectricReflectivity', 'pEnableAlphaTestRefFade', 'pIsSpeedTree', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pMipBias', 'pRenderLayerOverride', 'pRoughness', 'pScreenSpaceAOStrength', 'pSnowOnSlopesOffset', 'pTransmittanceScale', 'pUseExplicitNormals', 'pUseTwoSidedExplicitNormal', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_ExplicitNormalThreshold'],

    "Foliage_BillboardFading_DetailObject":
         ['pAlphaTestRef', 'pAmbientTransmissionAmount', 'pAmbientTransmissionTint', 'pDielectricReflectivity', 'pEnableAlphaTestRefFade', 'pIsSpeedTree', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pMipBias', 'pRenderLayerOverride', 'pRoughness', 'pScreenSpaceAOStrength', 'pSnowOnSlopesOffset', 'pTransmittanceScale', 'pUseExplicitNormals', 'pUseTwoSidedExplicitNormal', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_ExplicitNormalThreshold'],

    "Foliage_Clip":
         ['pAlphaTestRef', 'pAmbientTransmissionAmount', 'pAmbientTransmissionTint', 'pCrownRadius', 'pEnableAlphaTestRefFade', 'pEnableVertexAO', 'pHighlightAlphaTestRefBias', 'pIsSpeedTree', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pMipBias', 'pNormalizeType', 'pObjectPressScale', 'pOffset0', 'pOffset1', 'pOffset2', 'pRenderLayerOverride', 'pScale0', 'pScale1', 'pScale1Normal', 'pScale2', 'pScale2Normal', 'pScreenSpaceAOStrength', 'pSnowOnSlopesOffset', 'pTransmissionScale', 'pTrunkHeight', 'pUseExplicitNormals', 'pUseTwoSidedExplicitNormal', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_ExplicitNormalThreshold', 'pWeight1Power'],

    "Foliage_ClipLeaf_DetailObject":
         ['pAlphaTestRef', 'pAmbientTransmissionAmount', 'pAmbientTransmissionTint', 'pCrownRadius', 'pEnableAlphaTestRefFade', 'pEnableVertexAO', 'pIsSpeedTree', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pMipBias', 'pNormalizeType', 'pObjectPressScale', 'pOffset0', 'pOffset1', 'pOffset2', 'pRenderLayerOverride', 'pScale0', 'pScale1', 'pScale1Normal', 'pScale2', 'pScale2Normal', 'pScreenSpaceAOStrength', 'pSnowOnSlopesOffset', 'pTransmissionScale', 'pTrunkHeight', 'pUseExplicitNormals', 'pUseTwoSidedExplicitNormal', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_ExplicitNormalThreshold', 'pWeight1Power'],

    "Foliage_ClipLeafFading_DetailObject":
         ['pAlphaTestRef', 'pAmbientTransmissionAmount', 'pAmbientTransmissionTint', 'pCrownRadius', 'pEnableAlphaTestRefFade', 'pEnableVertexAO', 'pIsSpeedTree', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pMipBias', 'pNormalizeType', 'pObjectPressScale', 'pOffset0', 'pOffset1', 'pOffset2', 'pRenderLayerOverride', 'pScale0', 'pScale1', 'pScale1Normal', 'pScale2', 'pScale2Normal', 'pScreenSpaceAOStrength', 'pSnowOnSlopesOffset', 'pTransmissionScale', 'pTrunkHeight', 'pUseExplicitNormals', 'pUseTwoSidedExplicitNormal', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_ExplicitNormalThreshold', 'pWeight1Power'],

    "Foliage_OpaqueTrunk_DetailObject":
         ['pBarkNormalStrength', 'pCrownRadius', 'pEnableMoss', 'pEnableScreenSpaceAO', 'pEnableVertexAO', 'pIsSpeedTree', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pMossEdge', 'pMossEdgeFalloff', 'pMossNoiseMaskTilingX', 'pMossNoiseMaskTilingY', 'pMossNormalStrength', 'pMossProjectionBreaker', 'pMossTiling', 'pMossTrunkBaseEdgeFalloff', 'pMossTrunkBaseHeight', 'pMossYaw', 'pNormalizeType', 'pObjectPressScale', 'pOffset0', 'pOffset1', 'pOffset2', 'pRenderLayerOverride', 'pScale0', 'pScale1', 'pScale1Normal', 'pScale2', 'pScale2Normal', 'pSnowOnSlopesOffset', 'pTransmittance', 'pTrunkHeight', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_ExplicitNormalThreshold', 'pWeight1Power'],

    "Foliage_OpaqueTrunkFading_DetailObject":
         ['pBarkNormalStrength', 'pCrownRadius', 'pEnableMoss', 'pEnableScreenSpaceAO', 'pEnableVertexAO', 'pIsSpeedTree', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pMossEdge', 'pMossEdgeFalloff', 'pMossNoiseMaskTilingX', 'pMossNoiseMaskTilingY', 'pMossNormalStrength', 'pMossProjectionBreaker', 'pMossTiling', 'pMossTrunkBaseEdgeFalloff', 'pMossTrunkBaseHeight', 'pMossYaw', 'pNormalizeType', 'pObjectPressScale', 'pOffset0', 'pOffset1', 'pOffset2', 'pRenderLayerOverride', 'pScale0', 'pScale1', 'pScale1Normal', 'pScale2', 'pScale2Normal', 'pSnowOnSlopesOffset', 'pTransmittance', 'pTrunkHeight', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_ExplicitNormalThreshold', 'pWeight1Power'],

    "Foliage_ClipTexcoordWeight":
         ['pAlphaTestRef', 'pAmbientTransmissionAmount', 'pAmbientTransmissionTint', 'pCrownRadius', 'pEnableAlphaTestRefFade', 'pEnableVertexAO', 'pHighlightAlphaTestRefBias', 'pIsSpeedTree', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pMipBias', 'pNormalizeType', 'pObjectPressScale', 'pOffset0', 'pOffset1', 'pOffset2', 'pRenderLayerOverride', 'pScale0', 'pScale1', 'pScale1Normal', 'pScale2', 'pScale2Normal', 'pScreenSpaceAOStrength', 'pSnowOnSlopesOffset', 'pTransmissionScale', 'pTrunkHeight', 'pUseExplicitNormals', 'pUseTwoSidedExplicitNormal', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_ExplicitNormalThreshold', 'pWeight1Power'],

    "Foliage_ClipTexcoordWeight_DetailObject":
         ['pAlphaTestRef', 'pAmbientTransmissionAmount', 'pAmbientTransmissionTint', 'pCrownRadius', 'pEnableAlphaTestRefFade', 'pEnableVertexAO', 'pIsSpeedTree', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pMipBias', 'pNormalizeType', 'pObjectPressScale', 'pOffset0', 'pOffset1', 'pOffset2', 'pRenderLayerOverride', 'pScale0', 'pScale1', 'pScale1Normal', 'pScale2', 'pScale2Normal', 'pScreenSpaceAOStrength', 'pSnowOnSlopesOffset', 'pTransmissionScale', 'pTrunkHeight', 'pUseExplicitNormals', 'pUseTwoSidedExplicitNormal', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_ExplicitNormalThreshold', 'pWeight1Power'],

    "Foliage_ClipTexcoordWeightFading_DetailObject":
         ['pAlphaTestRef', 'pAmbientTransmissionAmount', 'pAmbientTransmissionTint', 'pCrownRadius', 'pEnableAlphaTestRefFade', 'pEnableVertexAO', 'pIsSpeedTree', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pMipBias', 'pNormalizeType', 'pObjectPressScale', 'pOffset0', 'pOffset1', 'pOffset2', 'pRenderLayerOverride', 'pScale0', 'pScale1', 'pScale1Normal', 'pScale2', 'pScale2Normal', 'pScreenSpaceAOStrength', 'pSnowOnSlopesOffset', 'pTransmissionScale', 'pTrunkHeight', 'pUseExplicitNormals', 'pUseTwoSidedExplicitNormal', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_ExplicitNormalThreshold', 'pWeight1Power'],

    "Foliage_ClipNoDisplacement":
         ['pAlphaTestRef', 'pAmbientTransmissionAmount', 'pAmbientTransmissionTint', 'pCrownRadius', 'pEnableAlphaTestRefFade', 'pEnableVertexAO', 'pHighlightAlphaTestRefBias', 'pIsSpeedTree', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pMipBias', 'pNormalizeType', 'pObjectPressScale', 'pOffset0', 'pOffset1', 'pOffset2', 'pRenderLayerOverride', 'pScale0', 'pScale1', 'pScale1Normal', 'pScale2', 'pScale2Normal', 'pScreenSpaceAOStrength', 'pSnowOnSlopesOffset', 'pTransmissionScale', 'pTrunkHeight', 'pUseExplicitNormals', 'pUseTwoSidedExplicitNormal', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_ExplicitNormalThreshold', 'pWeight1Power'],

    "Foliage_OpaqueNoDisplacement":
         ['pBarkNormalStrength', 'pCrownRadius', 'pEnableMoss', 'pEnableScreenSpaceAO', 'pEnableVertexAO', 'pIsSpeedTree', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pMossEdge', 'pMossEdgeFalloff', 'pMossNoiseMaskTilingX', 'pMossNoiseMaskTilingY', 'pMossNormalStrength', 'pMossProjectionBreaker', 'pMossTiling', 'pMossTrunkBaseEdgeFalloff', 'pMossTrunkBaseHeight', 'pMossYaw', 'pNormalizeType', 'pObjectPressScale', 'pOffset0', 'pOffset1', 'pOffset2', 'pRenderLayerOverride', 'pScale0', 'pScale1', 'pScale1Normal', 'pScale2', 'pScale2Normal', 'pSnowOnSlopesOffset', 'pTransmittance', 'pTrunkHeight', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_ExplicitNormalThreshold', 'pWeight1Power'],

    "Foliage_GrassPrioritisedCull_DetailObject":
         ['pAmbientTransmissionAmount', 'pAmbientTransmissionTint', 'pIsSpeedTree', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pRandomFrequency', 'pRandomScale', 'pRenderLayerOverride', 'pScreenSpaceAOStrength', 'pSnowOnSlopesOffset', 'pTerrainMaximumWaterPermeability', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_ExplicitNormalThreshold', 'pWeather_GrassPoolOffset', 'pWindScale'],

    "Metallic_Roughness_Alpha_Emissive":
         ['pEmissiveAdaptiveBrighnessWeight', 'pEmissiveIntensity', 'pEmissiveScrollData', 'pEmissiveTint', 'pEnableEmissiveFlexiColour', 'pEnableScreenSpaceAO', 'pExtrusionScaling', 'pFlexiColourBlended', 'pFlexiColourTexCoordIndex', 'pFlexiColourUseAdditiveBlend', 'pFlexiColourVertexColour', 'pRenderLayerOverride', 'pTransmittance', 'pVerticalTiling', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold'],

    "Water_WaterOccluder":
         ['pExtrusionScaling', 'pRenderLayerOverride', 'pVerticalTiling'],

    "Glass_UniformWeatherTwoSided":
         ['pDiffuseTint', 'pEnableWeatherPooling', 'pExtrusionScaling', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pOpacity', 'pRenderLayerOverride', 'pRoughness', 'pSnowOnSlopesOffset', 'pSnowOpacity', 'pSpecularReflectance', 'pTransmittance', 'pVerticalTiling', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_Enable', 'pWeather_ExplicitNormalThreshold'],

    "Glass_UniformWeather":
         ['pDiffuseTint', 'pEnableWeatherPooling', 'pExtrusionScaling', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pOpacity', 'pRenderLayerOverride', 'pRoughness', 'pSnowOnSlopesOffset', 'pSnowOpacity', 'pSpecularReflectance', 'pTransmittance', 'pVerticalTiling', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_Enable', 'pWeather_ExplicitNormalThreshold'],

    "Perturbation_Invisible":
         ['pPerturbationViewFlag', 'pRenderLayerOverride', 'pVerticalTiling'],

    "Metallic_Roughness_Opaque_Cavity_Projection_Weather":
         ['pEnableScreenSpaceAO', 'pEnableWeatherPooling', 'pExtrusionScaling', 'pFlexiColourBlended', 'pFlexiColourTexCoordIndex', 'pFlexiColourUseAdditiveBlend', 'pFlexiColourVertexColour', 'pMaximumDustAmount', 'pMaximumSnowAmount', 'pMaximumWaterPermeability', 'pOpacity', 'pOpacityRef', 'pPerturbationViewFlag', 'pProjection_AmbientOcclusion', 'pProjection_ColourTint', 'pProjection_CoordinateScale', 'pProjection_CylinderWeight', 'pProjection_Dimensions', 'pProjection_EmissiveBrightness', 'pProjection_EmissiveColour', 'pProjection_EmissiveColourBrightness', 'pProjection_FresnelDarken', 'pProjection_HeightOffset', 'pProjection_MipBias', 'pProjection_Plane0TexCoords', 'pProjection_Plane1TexCoords', 'pProjection_Plane2TexCoords', 'pProjection_PlanePositions', 'pProjection_TexCoordIndex', 'pProjection_TexCoords', 'pRefractionStrength', 'pRenderLayerOverride', 'pSnowOnSlopesOffset', 'pSnowOpacity', 'pVerticalTiling', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_Enable', 'pWeather_ExplicitNormalThreshold'],

    "Glass_Uniform":
         ['pDiffuseTint', 'pExtrusionScaling', 'pOpacity', 'pRenderLayerOverride', 'pRoughness', 'pSpecularReflectance', 'pTransmittance', 'pVerticalTiling', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold'],

    "Galileo_Terrain_BespokeSkirtLayers":
         ['pAutoZoomLodDitherScale', 'pAutoZoomLodOffset', 'pAutoZoomLodPostScale', 'pAutoZoomLodPreScale', 'pBlendWeightLodDistanceCoeff', 'pBlendWeightLodLayerScale', 'pBlendWeightLodTriplanarScale', 'pDetailNormalLodFade', 'pDetailNormalScale', 'pDetailNormalTile', 'pEnableBlendWeightLod', 'pEnableScreenSpaceAO', 'pEnableVerticalMacro', 'pFallbackCavityRoughness', 'pFallbackSpecular', 'pLayerHeightBlend', 'pMacroTile', 'pMaximumWaterPermeability', 'pPatchBlendMapScale', 'pPatchBlendMapTile', 'pPlayAreaBlendFactorScaleOffset', 'pPlayAreaHeightScaleOffset', 'pPlayAreaTexelMetrics', 'pPlayAreaUVScaleOffset', 'pPrimaryBlendMapScale', 'pPrimaryBlendMapTile', 'pRenderLayerOverride', 'pSkirtMaskScaleOffset', 'pSkirtNormalBlend', 'pSkirtShadowBorderScaleOffset', 'pSnowOnSlopesOffset', 'pSnowOpacity', 'pSpecialMaskType', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_ExplicitNormalThreshold', 'pWeather_LocalWaterAmount'],

    "Galileo_Terrain_BespokeSkirtLayers_Cutout":
         ['pAutoZoomLodDitherScale', 'pAutoZoomLodOffset', 'pAutoZoomLodPostScale', 'pAutoZoomLodPreScale', 'pBlendWeightLodDistanceCoeff', 'pBlendWeightLodLayerScale', 'pBlendWeightLodTriplanarScale', 'pDetailNormalLodFade', 'pDetailNormalScale', 'pDetailNormalTile', 'pEnableBlendWeightLod', 'pEnableScreenSpaceAO', 'pEnableVerticalMacro', 'pFallbackCavityRoughness', 'pFallbackSpecular', 'pLayerHeightBlend', 'pMacroTile', 'pMaximumWaterPermeability', 'pPatchBlendMapScale', 'pPatchBlendMapTile', 'pPlayAreaBlendFactorScaleOffset', 'pPlayAreaHeightScaleOffset', 'pPlayAreaTexelMetrics', 'pPlayAreaUVScaleOffset', 'pPrimaryBlendMapScale', 'pPrimaryBlendMapTile', 'pRenderLayerOverride', 'pSkirtMaskScaleOffset', 'pSkirtNormalBlend', 'pSkirtShadowBorderScaleOffset', 'pSnowOnSlopesOffset', 'pSnowOpacity', 'pSpecialMaskType', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold', 'pWeather_ExplicitNormalThreshold', 'pWeather_LocalWaterAmount'],

    "Depth_Pollution":
         ['pDepthDistance', 'pEmissiveAdaptiveBrighnessWeight', 'pEmissiveIntensity', 'pEmissiveScrollData', 'pEmissiveTint', 'pEnableEmissiveFlexiColour', 'pExtrusionScaling', 'pFlexiColourBlended', 'pFlexiColourTexCoordIndex', 'pFlexiColourUseAdditiveBlend', 'pFlexiColourVertexColour', 'pRenderLayerOverride', 'pVerticalTiling'],

    "Glass_Textured":
         ['pEnableDiffuseFlexiColour', 'pEnableSpecularFlexiColour', 'pExtrusionScaling', 'pRenderLayerOverride', 'pVerticalTiling', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold'],

    "ModelViewer_FloorGrid":
         ['pExtrusionScaling', 'pFlexiColourBlended', 'pFlexiColourTexCoordIndex', 'pFlexiColourUseAdditiveBlend', 'pFlexiColourVertexColour', 'pModelViewer_AnimatedGlowFrequencyCircular', 'pModelViewer_AnimatedGlowFrequencyNoisy', 'pModelViewer_AnimatedGlowIntensityCircular', 'pModelViewer_AnimatedGlowIntensityNoisy', 'pModelViewer_AnimatedGlowMapContributionCircular', 'pModelViewer_AnimatedGlowMapContributionNoisy', 'pModelViewer_AnimatedGlowSpeedCircular', 'pModelViewer_AnimatedGlowSpeedNoisy', 'pModelViewer_ChomaticAbberationIntensity', 'pModelViewer_EchoDistance', 'pModelViewer_EchoOpacity1', 'pModelViewer_EchoOpacity2', 'pModelViewer_EchoSteps', 'pModelViewer_EmissiveStrength1', 'pModelViewer_EmissiveStrength2', 'pModelViewer_ExposureCompensation', 'pModelViewer_GridColour', 'pModelViewer_GridSize', 'pModelViewer_HorizonFadeFalloff', 'pModelViewer_LineThickness', 'pModelViewer_SpecularStrength', 'pModelViewer_UseEchoEffect', 'pModelViewer_UseTexturedEmissive', 'pPerturbationViewFlag', 'pRenderLayerOverride', 'pVerticalTiling', 'pWaterEdge_Falloff', 'pWaterEdge_NoiseScale', 'pWaterEdge_NoiseSpeed', 'pWaterEdge_NoiseStrength', 'pWaterEdge_WaterEdgeThreshold'],

    "UI_Hyperloops":
         ['pExtrusionScaling', 'pFlexiColourBlended', 'pFlexiColourTexCoordIndex', 'pFlexiColourUseAdditiveBlend', 'pFlexiColourVertexColour', 'pHyperloops_DiffuseIntensity', 'pHyperloops_DiffuseTint', 'pHyperloops_EnableFresnelOpacity', 'pHyperloops_FresnelPower', 'pHyperloops_OpacityHeightAdjust', 'pHyperloops_OpacityHeightWeight', 'pHyperloops_OpacityScale', 'pLight_Height', 'pLight_Rotation', 'pLight_Shading', 'pPlayAreaBlendFactorScaleOffset', 'pPlayAreaHeightScaleOffset', 'pPlayAreaTexelMetrics', 'pPlayAreaUVScaleOffset', 'pRenderLayerOverride', 'pSkirtMaskScaleOffset', 'pSkirtNormalBlend', 'pSkirtShadowBorderScaleOffset', 'pVerticalTiling'],

    "Water_CameraBubble":
         ['pDiffuseHeightVarianceOcclusionBias', 'pExtrusionScaling', 'pReflectionDistortion', 'pRefractionDistortion', 'pRenderLayerOverride', 'pScatterHeightVarianceOcclusionBias', 'pSpecularHeightVarianceOcclusionBias', 'pVerticalTiling', 'pWaterEdgeOpacityScale', 'pWaterFogging', 'pWaterNormalIntensity', 'pWaterScattering'],

}

