jwe_specdefs = {

b'AmenityProvider': [0],
b'Animation': [1, 1],
b'AnimationControl': [0],
b'AnimationDataStreams': [0],
b'AnimationProxy': [1,1],
b'ArrivalHelipad': [0],
b'AssetPackageLoader': [1,2,1,1],#needs work
b'AssetPackageProvider': [1, 1],
b'AssetPackageStream': [1],
b'AudioBakedAnimation': [0],
b'AudioBoundingVolume': [1],
b'AudioBuilding': [0],
b'AudioBuildingDetail': [0],
b'AudioBuildingMusic': [0],
b'AudioBuildingParticle': [0],
b'AudioBuildingStorm': [0],
b'AudioCar': [0],
b'AudioCarDamage': [0],
b'AudioCarvo': [0],
b'AudioCrowdDetail': [0],
b'AudioCullingNode': [0],
b'AudioDataStream': [1],
b'AudioDinosaurCore': [1, 4],
b'AudioDinosaurDetail': [1],
b'AudioDinosaurRagdoll': [1,1],
b'AudioDoppler': [1],
b'AudioEmitterCullingPack': [0],
b'AudioGuest': [0],
b'AudioGunner': [0],
b'AudioGyrosphere': [0],
b'AudioHelicopter': [0],
b'AudioLFOGenerator': [0],
b'AudioMonorail': [0],
b'AudioObstruction': [0],
b'AudioParticle': [0],
b'AudioPosition': [1],
b'AudioProjectile': [0],
b'AudioSimpleDinosaur': [0],
b'AudioStorm': [0],
b'AudioTestTone': [0],
b'AudioTornado': [0],
b'AudioVehicleTour': [0],
b'AudioWithinListenerRange': [1],
b'Aviary': [0],
b'AviaryMusic': [0],
b'BakedAnimation': [0],
b'BehaviourTreeAgent': [0],
b'BehaviourTreeIdleAgentDestroyer': [0],
b'BehaviourTreeProvider': [1, 1],
b'Boid': [0],
b'BoidFlock': [0],
b'BoneTransform': [1, 2],
b'BoundingVolumeBroadphase': [1],
b'Building': [0],

b'Coordination': [0],
b'CrowdInterestingEventSpawner': [1,3],
b'CrowdPhysicsCollider': [0],



b'DinosaurAmenities': [0],
b'DinosaurBehaviourTag': [0],
b'DinosaurCamera': [1, 2],
b'DinosaurDiseaseSource': [1],
b'DinosaurGenome': [1],
b'DinosaurHeadLookReaction': [0],
b'DinosaurHeadLookTargetPicker': [1,2],
b'DinosaurLifecycle': [1,1],
b'DinosaurMaterialDecay': [0],
b'DinosaurMovementTarget': [1],
b'DinosaurObjectiveMarker': [0],
b'DinosaurSimulation': [1,1],
b'DinosaurSpecies': [1,2],
b'DinosaurStatistics': [0],
b'DinosaurStatusIcon': [1,1],
b'DinosaurThreat': [1],
b'DinosaurTreeAgent': [0],
b'DinosaurUIContext': [0],
b'FlowDirection': [0],
b'FlowDiscomfort': [1],
b'FlowMotion': [1],
b'FlowParticle': [1],
b'FlowPath': [0],
b'FlowStreamPath': [1,1],
b'FlowTargetReservation': [1],
b'FlowTheatre': [0],
b'GuestThreatMap': [1],
b'HeadLookTarget': [1,2],
b'HerdMembership': [0],
b'IKFootPlant': [1,2,"countt",2],
b'IKHeadLook': [1,1],
b'IKSolver': [1],
b'LevelOfDetail': [0],
b'Locomotion': [1],
b'MapIcon': [1],
b'MaterialCollection': [1,1,2],
b'Model': [1,2],
b'ModelSkeleton': [1,1],
b'MotionApplication': [0],
b'MotionGraph': [1,2],
b'MotionGraphLocomotion': [1,9],
b'ObjectiveMarker': [1],
b'Particle': [1,1],
b'ParticleSelector': [1,1],
b'ParticleTrigger': [1,1],
b'PhysicsCapsuleShape': [1],
b'PhysicsDrivenSkeleton': [1,2],
b'PhysicsProxy': [1],
b'PhysicsRagdollImpact': [0],
b'PhysicsRigidBody': [1,4],
b'RenderBoundingVolume': [1],
b'RopeAttachPoint': [1,2],
b'SkeletonDebug': [1],
b'SpatialCapsule': [1],
b'SpatialDatabase': [0],
b'SpatialSphere': [1],
b'StatusIcon': [1],
b'TheatreActor': [0],
b'UIEntityName': [1,2],
b'Velocity': [0],
b'ViewFilter': [1],
b'ViewpointTarget': [0],
b'Winchable': [1,2,"countt"],
}