texchannels = {
	'pAOTexture': {"": "AO"},
	# 'pAlphaTexture': {"": ""},
	# 'pBaseAOTexture': {"": ""},
	'pBaseColourTexture': {"RGB": "BC", "A": "CA"},  # check if A is used here
	# 'pBaseColourTextureDetailBase': {"RGB": "", "A": ""},
	# 'pBaseColourTextureDetailBlend': {"RGB": "", "A": ""},
	# 'pBaseDielectricSpecularLevelTexture': {"": ""},
	# 'pBaseDiffuseTexture': {"": ""},
	# 'pBaseNormalTexture': {"RG": "", "B": "", "A": ""},
	# 'pCavityRoughnessDielectricArray': {"R": "", "G": "", "B": "", "A": ""},
	# 'pDetailNormalTexture': {"": ""},
	# 'pDetailRoughnessTexture': {"": ""},
	'pDiffuseAlphaTexture': {"RGB": "BC", "A": "OP"},
	# 'pDiffuseArray': {"": ""},
	'pDiffuseTexture': {"": "BC"},
	# 'pDinosaurFeathers_BaseDiffuseTexture': {"": ""},
	# 'pEmissiveTexture': {"": ""},
	# 'pEnvironmentalNoiseMask': {"": ""},
	# 'pFeathersBaseDiffuseTexture': {"": ""},
	# 'pFeathers_AOHeightOpacityTransmission_PackedTexture': {"R": "", "G": "", "B": "", "A": ""},
	# 'pFeathers_Aniso_PackedTexture': {"R": "", "G": "", "B": "", "A": ""},
	# 'pFeathers_BaseColourTexture': {"": ""},
	# 'pFeathers_EmissiveTexture': {"": ""},
	# 'pFeathers_NormalTexture': {"": ""},
	# 'pFeathers_RoughnessPackedTexture': {"R": "", "G": "", "B": "", "A": ""},
	# 'pFinAlphaTexture': {"R": "", "G": "", "B": "", "A": ""},
	'pFlexiColourMasksTexture': {"R": "F1", "G": "F2", "B": "F3", "A": "F4"},
	# 'pFoamMapTexture': {"": ""},
	# 'pFoamyAreasDistantMap': {"": ""},
	# 'pFullScaleDiffuseAndSpecial': {"": ""},
	# 'pGradHeightArray': {"RG": "", "B": "", "A": ""},
	# 'pHeightTexture': {"": ""},
	# 'pHyperloops_AlphaEmissiveMaskTexture': {"": ""},
	# 'pHyperloops_DiffuseTexture': {"": ""},
	# 'pIridescenceMaskTexture': {"": ""},
	# 'pIridescenceTexture': {"": ""},
	# 'pLayered_BlendWeights': {"R": "", "G": "", "B": "", "A": ""},
	# 'pLayered_DiffuseTexture': {"R": "", "G": "", "B": "", "A": ""},
	# 'pLayered_HeightTexture': {"R": "", "G": "", "B": "", "A": ""},
	# 'pLayered_PackedTexture': {"R": "", "G": "", "B": "", "A": ""},
	# 'pLayered_RemapTexture': {"R": "", "G": "", "B": "", "A": ""},
	# 'pLayered_WarpOffset': {"": ""},
	# 'pMacroDiffuse': {"": ""},
	# 'pModelViewer_GridPatternMap': {"": ""},
	# 'pMoiseNoiseMask': {"": ""},
	# 'pMossBaseColour': {"": ""},
	# 'pMossBaseColourRoughnessPackedTexture': {"RGB": "", "A": ""},
	# 'pMossNormalTexture': {"": ""},
	# 'pMossVarianceTexture': {"": ""},
	# 'pNormalBlendWeightTexture': {"": ""},
	# 'pNormalMapTextureUnique': {"": ""},
	'pNormalTexture': {"RGB": "NM", "A": "AO"},  # BC7_UNORM - no coord dropping? not sure if A is actually always AO
	# 'pNormalTextureDetailBase': {"RGB": "", "A": ""},
	# 'pNormalTextureDetailBlend': {"RGB": "", "A": ""},
	'pOpacityTexture': {"": "OP"},
	# 'pPOM_DisplacementRelaxedConeTexture': {"": ""},
	# 'pPackedTexture': {"RGB": "", "A": ""},
	# 'pPatchBlendMap': {"": ""},
	# 'pPatterning_FeathersPatchworkGradientMap': {"": ""},
	# 'pPatterning_FeathersPatternGradientMap': {"": ""},
	# 'pPatterning_PatchworkGradientMap': {"": ""},
	# 'pPatterning_PatternGradientMap': {"": ""},
	# 'pPrimaryBlendMap': {"": ""},
	# 'pProjection_BackgroundPlaneDiffuseTexture': {"": ""},
	# 'pProjection_BackgroundPlaneEmissiveTexture': {"": ""},
	# 'pProjection_DiffuseTexture': {"": ""},
	# 'pProjection_EmissiveTexture': {"": ""},
	# 'pProjection_ForegroundPlaneDiffuseTexture': {"": ""},
	# 'pProjection_ForegroundPlaneEmissiveTexture': {"": ""},
	# 'pProjection_Plane0Texture': {"": ""},
	# 'pProjection_Plane1Texture': {"": ""},
	# 'pProjection_Plane2Texture': {"": ""},
	# 'pProjection_Texture': {"": ""},
	# 'pRemapTexture': {"": ""},
	'pRoughnessPackedTexture': {"R": "MT", "G": "SP", "B": "RN", "A": "FO"},
	# 'pRoughnessTexture': {"": ""},
	# 'pShellMap': {"R": "", "G": "", "B": "", "A": ""},
	# 'pSpecularTexture': {"": ""},
	# 'pSubLayerDiffuse0Texture': {"": ""},
	# 'pSubLayerDiffuse1Texture': {"": ""},
	# 'pThicknessTexture': {"": ""},
	# 'pWaterBottomHeight': {"": ""},
	# 'pWaterDetailGradientMap': {"": ""},
	# 'pWaterDetailHeightMap': {"": ""},
	# 'pWaterDetailNormalMapTexture': {"": ""},
	# 'pWaterDetailSpecMapTexture': {"": ""},
	# 'pWaterNormalMapTexture': {"": ""},
	# 'pWaterRipplesTexture': {"": ""},
	# 'pWaterRoughnessMapTexture': {"": ""},
	# 'u_basePatchworkMap': {"": ""},
	# 'u_basePatternMap': {"": ""},
	# 'u_feathersBasePatchworkMap': {"": ""},
	# 'u_feathersBasePatternMap': {"": ""},
}
