shaders = {
	'Animal_Eye': (
		[
			'pAOTexture',
			'pAlbinoBaseColourAndMaskTexture',
			'pBaseColourAndMaskTexture',
			'pErythristicBaseColourAndMaskTexture',
			'pHeight',
			'pLeucisticBaseColourAndMaskTexture',
			'pMelanisticBaseColourAndMaskTexture',
			'pNormalTexture',
			'pPiebaldMask',
			'pPiebaldTexture',
			'pRoughnessPackedTexture',
			'pXanthicBaseColourAndMaskTexture',
		],
		{
			'pAOTexCoordIndex': (5, [((0,), 3)]),
			'pAlbinoHeightScale': (0, [((0.05,), 1), ((0.1,), 1), ((0.062,), 1)]),
			'pAlbinoRoughnessMultiplier': (0, [((1.0,), 3)]),
			'pAlbinoSpecularMultiplier': (0, [((1.0,), 3)]),
			'pAnimalIdentityMask': (5, [((1,), 3)]),
			'pColourMask_HSLGenetic0': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGenetic1': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticAlbino0': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticAlbino1': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticErythristic0': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticErythristic1': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticLeucistic0': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticLeucistic1': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticMelanistic0': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticMelanistic1': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticXanthic0': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticXanthic1': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_NoiseContrast': (0, [((0.75,), 3)]),
			'pColourMask_NoiseThreshold': (0, [((0.5,), 3)]),
			'pColourMask_NoiseWeight': (0, [((1.0,), 3)]),
			'pCorpseTint': (2, [((0.5, 0.5, 0.5), 3)]),
			'pEnableScreenSpaceAO': (6, [((1,), 3)]),
			'pErythristicHeightScale': (0, [((0.2,), 3)]),
			'pErythristicRoughnessMultiplier': (0, [((1.0,), 3)]),
			'pErythristicSpecularMultiplier': (0, [((1.0,), 3)]),
			'pEyeHorizonOffset': (0, [((0.0,), 3)]),
			'pEyeSunYMultiplierIris': (0, [((0.0,), 3)]),
			'pEyeSunYMultiplierLens': (0, [((0.5,), 3)]),
			'pEyelidOcclusion': (1, [((0.0, 0.5), 2), ((0.0, 0.0), 1)]),
			'pHeightScale': (0, [((0.05,), 1), ((0.1,), 1), ((0.062,), 1)]),
			'pIBLRoughness': (0, [((0.1,), 3)]),
			'pLensRoughness': (0, [((0.15,), 3)]),
			'pLensSpecularLevel': (0, [((0.02,), 3)]),
			'pLeucisticHeightScale': (0, [((0.2,), 3)]),
			'pLeucisticRoughnessMultiplier': (0, [((1.0,), 3)]),
			'pLeucisticSpecularMultiplier': (0, [((1.0,), 3)]),
			'pMelanisticHeightScale': (0, [((0.2,), 3)]),
			'pMelanisticRoughnessMultiplier': (0, [((1.0,), 3)]),
			'pMelanisticSpecularMultiplier': (0, [((1.0,), 3)]),
			'pPiebaldMarkingMipBias': (0, [((-1.0,), 3)]),
			'pPiebaldMarkingMorph': (5, [((0,), 3)]),
			'pPiebaldWithAlbino': (6, [((1,), 3)]),
			'pPiebaldWithErythristic': (6, [((1,), 3)]),
			'pPiebaldWithLeucistic': (6, [((1,), 3)]),
			'pPiebaldWithMelanistic': (6, [((1,), 3)]),
			'pPiebaldWithXanthic': (6, [((1,), 3)]),
			'pRenderLayerOverride': (5, [((-1,), 3)]),
			'pSpecularBrightness': (0, [((1.0,), 3)]),
			'pSpecularLevel': (0, [((0.025,), 3)]),
			'pSpecularSaturation': (0, [((1.0,), 3)]),
			'pVerticalTiling': (0, [((0.25,), 3)]),
			'pXanthicHeightScale': (0, [((0.2,), 3)]),
			'pXanthicRoughnessMultiplier': (0, [((1.0,), 3)]),
			'pXanthicSpecularMultiplier': (0, [((1.0,), 3)]),
		}
	),
	'Animal_Skin': (
		[
			'pAOTexture',
			'pAlbinoBaseColourAndMaskTexture',
			'pBaldnessScarTexture',
			'pBaseColourAndMaskTexture',
			'pErythristicBaseColourAndMaskTexture',
			'pLeucisticBaseColourAndMaskTexture',
			'pMarkingNoise',
			'pMarkingPatchworkMask',
			'pMelanisticBaseColourAndMaskTexture',
			'pNormalTexture',
			'pPiebaldMask',
			'pPiebaldTexture',
			'pRoughnessPackedTexture',
			'pScarClut',
			'pXanthicBaseColourAndMaskTexture',
		],
		{
			'gWetBrightness': (0, [((0.7,), 3)]),
			'pAOTexCoordIndex': (5, [((0,), 3)]),
			'pAlbinoRoughnessMultiplier': (0, [((1.0,), 3)]),
			'pAlbinoSpecularMultiplier': (0, [((1.0,), 3)]),
			'pAnimalIdentityMask': (5, [((1,), 3)]),
			'pColourMask_HSLGenetic0': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGenetic1': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticAlbino0': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticAlbino1': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticErythristic0': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticErythristic1': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticLeucistic0': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticLeucistic1': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticMelanistic0': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticMelanistic1': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticXanthic0': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticXanthic1': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_NoiseContrast': (0, [((0.75,), 3)]),
			'pColourMask_NoiseThreshold': (0, [((0.5,), 3)]),
			'pColourMask_NoiseWeight': (0, [((1.0,), 3)]),
			'pCorpseTint': (2, [((0.5, 0.5, 0.5), 3)]),
			'pDirtDryColour': (2, [((0.056, 0.08, 0.13), 3)]),
			'pDirtWetColour': (2, [((0.045, 0.06, 0.09), 3)]),
			'pEnableScreenSpaceAO': (6, [((1,), 3)]),
			'pErythristicRoughnessMultiplier': (0, [((1.0,), 3)]),
			'pErythristicSpecularMultiplier': (0, [((1.0,), 3)]),
			'pLeucisticRoughnessMultiplier': (0, [((1.0,), 3)]),
			'pLeucisticSpecularMultiplier': (0, [((1.0,), 3)]),
			'pMarkingNoiseEnableRandomOffset': (6, [((1,), 3)]),
			'pMarkingNoiseScale': (0, [((0.1,), 3)]),
			'pMaximumSnowAmount': (0, [((1.0,), 3)]),
			'pMaximumWaterPermeability': (0, [((0.5,), 3)]),
			'pMelanisticRoughnessMultiplier': (0, [((1.0,), 3)]),
			'pMelanisticSpecularMultiplier': (0, [((1.0,), 3)]),
			'pNoisiness': (0, [((0.55,), 3)]),
			'pPiebaldMarkingMipBias': (0, [((-1.0,), 3)]),
			'pPiebaldMarkingMorph': (5, [((0,), 3)]),
			'pPiebaldWithAlbino': (6, [((1,), 3)]),
			'pPiebaldWithErythristic': (6, [((1,), 3)]),
			'pPiebaldWithLeucistic': (6, [((1,), 3)]),
			'pPiebaldWithMelanistic': (6, [((1,), 3)]),
			'pPiebaldWithXanthic': (6, [((1,), 3)]),
			'pRenderLayerOverride': (5, [((-1,), 3)]),
			'pScarBaldnessCutoff': (0, [((0.5,), 3)]),
			'pScarMaskPower': (0, [((3.0,), 3)]),
			'pSnowOnSlopesOffset': (0, [((0.0,), 3)]),
			'pSpecularOcclusion': (0, [((0.0,), 3)]),
			'pUseOrenNayar': (6, [((1,), 3)]),
			'pVerticalTiling': (0, [((0.25,), 3)]),
			'pWeather_ExplicitNormalThreshold': (0, [((0.85,), 3)]),
			'pWetRoughnessStrength': (0, [((0.8,), 3)]),
			'pWetRoughnessValue': (0, [((0.115,), 3)]),
			'pWetSpecularStrength': (0, [((0.0,), 3)]),
			'pWetSpecularValue': (0, [((1.0,), 3)]),
			'pWetnessYPositionLower': (0, [((1.0,), 3)]),
			'pWetnessYPositionUpper': (0, [((1.5,), 3)]),
			'pWoundBloodDepthStrength': (0, [((10.0,), 3)]),
			'pWoundBloodNormalStrength': (0, [((0.25,), 3)]),
			'pWoundBloodRoughness': (0, [((0.224,), 3)]),
			'pWoundBloodSpecularReflectance': (0, [((0.011,), 3)]),
			'pWoundDepthMaskPower': (0, [((4.346,), 3)]),
			'pWoundScarDepthStrength': (0, [((5.0,), 3)]),
			'pWoundScarNormalStrength': (0, [((0.0,), 3)]),
			'pWoundScarRoughness': (0, [((0.446,), 3)]),
			'pWoundScarSpecularReflectance': (0, [((0.04,), 3)]),
			'pXanthicRoughnessMultiplier': (0, [((1.0,), 3)]),
			'pXanthicSpecularMultiplier': (0, [((1.0,), 3)]),
		}
	),
	'FurBase': (
		[
			'pAOTexture',
			'pAlbinoBaseColourAndMaskTexture',
			'pBaldnessScarTexture',
			'pBaseColourAndMaskTexture',
			'pErythristicBaseColourAndMaskTexture',
			'pLeucisticBaseColourAndMaskTexture',
			'pMarkingNoise',
			'pMarkingPatchworkMask',
			'pMelanisticBaseColourAndMaskTexture',
			'pNormalTexture',
			'pPiebaldMask',
			'pPiebaldTexture',
			'pRoughnessPackedTexture',
			'pScarClut',
			'pTransmittanceTexture',
			'pXanthicBaseColourAndMaskTexture',
		],
		{
			'gAnisotropicStrength': (0, [((0.449,), 1), ((0.129,), 1), ((0.703,), 1)]),
			'gDirectionScale': (0, [((1.0,), 2), ((3.15,), 1)]),
			'gFurExtension': (0, [((1.0,), 3)]),
			'gLodFade': (1, [((5.0, 10.0), 3)]),
			'gWetBrightness': (0, [((0.7,), 3)]),
			'gWetFlattening': (0, [((0.7,), 3)]),
			'gWetHairBaseDirectionStrength': (0, [((0.64,), 3)]),
			'gWetHairDirectionStrength': (0, [((1.0,), 3)]),
			'gWetHairDownwardPush': (0, [((0.59,), 2), ((0.15,), 1)]),
			'pAOTexCoordIndex': (5, [((0,), 3)]),
			'pAlbinoRoughnessMultiplier': (0, [((1.0,), 3)]),
			'pAlbinoSpecularMultiplier': (0, [((1.0,), 3)]),
			'pAnimalIdentityMask': (5, [((1,), 3)]),
			'pAnisoNormalBend': (0, [((0.0,), 3)]),
			'pColourMask_HSLGenetic0': (2, [((0.505, 0.512, 0.52), 1), ((0.505, 0.513, 0.52), 1), ((0.512, 0.515, 0.53), 1)]),
			'pColourMask_HSLGenetic1': (2, [((0.345, 0.495, 0.5), 2), ((0.27, 0.5, 0.507), 1)]),
			'pColourMask_HSLGeneticAlbino0': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticAlbino1': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticErythristic0': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticErythristic1': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticLeucistic0': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticLeucistic1': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticMelanistic0': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticMelanistic1': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticXanthic0': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticXanthic1': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_NoiseContrast': (0, [((1.0,), 3)]),
			'pColourMask_NoiseThreshold': (0, [((0.0,), 3)]),
			'pCorpseTint': (2, [((0.5, 0.5, 0.5), 3)]),
			'pDirtDryColour': (2, [((0.056, 0.08, 0.13), 3)]),
			'pDirtWetColour': (2, [((0.045, 0.06, 0.09), 3)]),
			'pEnableScreenSpaceAO': (6, [((1,), 3)]),
			'pErythristicRoughnessMultiplier': (0, [((1.0,), 3)]),
			'pErythristicSpecularMultiplier': (0, [((1.0,), 3)]),
			'pFurAlbinoDepthScale': (0, [((0.715,), 3)]),
			'pFurDepthScale': (0, [((0.473,), 2), ((1.0,), 1)]),
			'pFurErythristicDepthScale': (0, [((0.715,), 3)]),
			'pFurLeucisticDepthScale': (0, [((0.715,), 3)]),
			'pFurMelanisticDepthScale': (0, [((0.715,), 3)]),
			'pFurXanthicDepthScale': (0, [((0.715,), 3)]),
			'pLeucisticRoughnessMultiplier': (0, [((1.0,), 3)]),
			'pLeucisticSpecularMultiplier': (0, [((1.0,), 3)]),
			'pMarkingNoiseEnableRandomOffset': (6, [((1,), 3)]),
			'pMarkingNoiseScale': (0, [((0.1,), 3)]),
			'pMaximumSnowAmount': (0, [((1.0,), 3)]),
			'pMaximumWaterPermeability': (0, [((0.5,), 3)]),
			'pMelanisticRoughnessMultiplier': (0, [((1.0,), 3)]),
			'pMelanisticSpecularMultiplier': (0, [((1.0,), 3)]),
			'pNoisiness': (0, [((0.55,), 3)]),
			'pPiebaldMarkingMipBias': (0, [((-1.0,), 3)]),
			'pPiebaldMarkingMorph': (5, [((0,), 3)]),
			'pPiebaldWithAlbino': (6, [((1,), 3)]),
			'pPiebaldWithErythristic': (6, [((1,), 3)]),
			'pPiebaldWithLeucistic': (6, [((1,), 3)]),
			'pPiebaldWithMelanistic': (6, [((1,), 3)]),
			'pPiebaldWithXanthic': (6, [((1,), 3)]),
			'pRenderLayerOverride': (5, [((-1,), 3)]),
			'pScarBaldnessCutoff': (0, [((0.85,), 3)]),
			'pScarBaldnessCutoffAlbino': (0, [((0.85,), 3)]),
			'pScarBaldnessCutoffErythristic': (0, [((0.5,), 3)]),
			'pScarBaldnessCutoffLeucistic': (0, [((0.5,), 3)]),
			'pScarBaldnessCutoffMelanistic': (0, [((0.5,), 3)]),
			'pScarBaldnessCutoffXanthic': (0, [((0.5,), 3)]),
			'pSnowOnSlopesOffset': (0, [((0.0,), 3)]),
			'pUseOrenNayar': (6, [((1,), 3)]),
			'pVerticalTiling': (0, [((0.25,), 3)]),
			'pWeather_ExplicitNormalThreshold': (0, [((0.85,), 3)]),
			'pWetRoughnessStrength': (0, [((0.68,), 2), ((0.8,), 1)]),
			'pWetRoughnessValue': (0, [((0.115,), 3)]),
			'pWetSpecularStrength': (0, [((0.5,), 3)]),
			'pWetSpecularValue': (0, [((0.02,), 3)]),
			'pWetnessYPositionLower': (0, [((0.3,), 2), ((0.05,), 1)]),
			'pWetnessYPositionUpper': (0, [((0.6,), 2), ((0.7,), 1)]),
			'pXanthicRoughnessMultiplier': (0, [((1.0,), 3)]),
			'pXanthicSpecularMultiplier': (0, [((1.0,), 3)]),
		}
	),
	'FurFin': (
		[
			'pAOTexture',
			'pAlbinoBaseColourAndMaskTexture',
			'pBaldnessScarTexture',
			'pBaseColourAndMaskTexture',
			'pErythristicBaseColourAndMaskTexture',
			'pFinAlphaTexture',
			'pLeucisticBaseColourAndMaskTexture',
			'pMarkingNoise',
			'pMarkingPatchworkMask',
			'pMelanisticBaseColourAndMaskTexture',
			'pNormalTexture',
			'pPiebaldMask',
			'pPiebaldTexture',
			'pRoughnessPackedTexture',
			'pScarClut',
			'pTransmittanceTexture',
			'pXanthicBaseColourAndMaskTexture',
		],
		{
			'gAnisotropicStrength': (0, [((0.455,), 2), ((0.4,), 1)]),
			'gDirectionScale': (0, [((1.3,), 2), ((1.0,), 1)]),
			'gFinBrushScale': (0, [((1.0,), 2), ((4.0,), 1)]),
			'gFurExtension': (0, [((1.0,), 3)]),
			'gLodFade': (1, [((6.0, 12.0), 3)]),
			'gWetBrightness': (0, [((0.7,), 3)]),
			'gWetFlattening': (0, [((0.7,), 3)]),
			'gWetHairBaseDirectionStrength': (0, [((0.664,), 2), ((1.0,), 1)]),
			'gWetHairDirectionStrength': (0, [((1.0,), 3)]),
			'gWetHairDownwardPush': (0, [((0.59,), 2), ((0.15,), 1)]),
			'pAOTexCoordIndex': (5, [((0,), 3)]),
			'pAlbinoRoughnessMultiplier': (0, [((1.0,), 3)]),
			'pAlbinoSpecularMultiplier': (0, [((1.0,), 3)]),
			'pAlphaClip': (0, [((0.2,), 3)]),
			'pAlphaTestRef': (0, [((0.5,), 3)]),
			'pAnimalIdentityMask': (5, [((1,), 3)]),
			'pAnisoNormalBend': (0, [((0.0,), 3)]),
			'pColourMask_HSLGenetic0': (2, [((0.505, 0.512, 0.52), 1), ((0.505, 0.513, 0.52), 1), ((0.512, 0.515, 0.53), 1)]),
			'pColourMask_HSLGenetic1': (2, [((0.345, 0.495, 0.5), 2), ((0.27, 0.5, 0.507), 1)]),
			'pColourMask_HSLGeneticAlbino0': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticAlbino1': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticErythristic0': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticErythristic1': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticLeucistic0': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticLeucistic1': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticMelanistic0': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticMelanistic1': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticXanthic0': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticXanthic1': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_NoiseContrast': (0, [((1.0,), 3)]),
			'pColourMask_NoiseThreshold': (0, [((0.0,), 3)]),
			'pCorpseTint': (2, [((0.5, 0.5, 0.5), 3)]),
			'pDiffuseTransmittance': (0, [((3.0,), 3)]),
			'pDirtDryColour': (2, [((0.056, 0.08, 0.13), 3)]),
			'pDirtWetColour': (2, [((0.045, 0.06, 0.09), 3)]),
			'pEnableAlphaTestRefFade': (6, [((0,), 3)]),
			'pEnableScreenSpaceAO': (6, [((0,), 3)]),
			'pErythristicRoughnessMultiplier': (0, [((1.0,), 3)]),
			'pErythristicSpecularMultiplier': (0, [((1.0,), 3)]),
			'pFinAxisFade': (0, [((0.5,), 2), ((0.269,), 1)]),
			'pFinCorpseAlpha': (0, [((0.2,), 3)]),
			'pFinNormalBend': (0, [((1.0,), 3)]),
			'pFinNormalCurveBend': (0, [((4.0,), 3)]),
			'pFinOpacity': (0, [((1.8,), 2), ((4.0,), 1)]),
			'pFinRimFade': (0, [((0.3,), 2), ((0.252,), 1)]),
			'pFinTilingRate': (0, [((2.0,), 3)]),
			'pFurAlbinoDepthScale': (0, [((0.641,), 3)]),
			'pFurAlbinoSpecularDepthScale': (0, [((0.0,), 3)]),
			'pFurDepthScale': (0, [((0.0,), 1), ((1.5,), 1), ((0.7040001,), 1)]),
			'pFurErythristicDepthScale': (0, [((0.715,), 3)]),
			'pFurErythristicSpecularDepthScale': (0, [((0.0,), 3)]),
			'pFurLeucisticDepthScale': (0, [((0.715,), 3)]),
			'pFurLeucisticSpecularDepthScale': (0, [((0.0,), 3)]),
			'pFurMelanisticDepthScale': (0, [((0.715,), 3)]),
			'pFurMelanisticSpecularDepthScale': (0, [((0.0,), 3)]),
			'pFurSpecularDepthScale': (0, [((1.253,), 2), ((0.167,), 1)]),
			'pFurXanthicDepthScale': (0, [((0.715,), 3)]),
			'pFurXanthicSpecularDepthScale': (0, [((0.0,), 3)]),
			'pIBLRoughnessTweak': (0, [((1.0,), 2), ((0.831,), 1)]),
			'pLeucisticRoughnessMultiplier': (0, [((1.0,), 3)]),
			'pLeucisticSpecularMultiplier': (0, [((1.0,), 3)]),
			'pMarkingNoiseEnableRandomOffset': (6, [((1,), 3)]),
			'pMarkingNoiseScale': (0, [((0.1,), 3)]),
			'pMelanisticRoughnessMultiplier': (0, [((1.0,), 3)]),
			'pMelanisticSpecularMultiplier': (0, [((1.0,), 3)]),
			'pMipBias': (0, [((-2.0,), 3)]),
			'pNoisiness': (0, [((0.55,), 3)]),
			'pPiebaldMarkingMipBias': (0, [((-1.0,), 3)]),
			'pPiebaldMarkingMorph': (5, [((0,), 3)]),
			'pPiebaldWithAlbino': (6, [((1,), 3)]),
			'pPiebaldWithErythristic': (6, [((1,), 3)]),
			'pPiebaldWithLeucistic': (6, [((1,), 3)]),
			'pPiebaldWithMelanistic': (6, [((1,), 3)]),
			'pPiebaldWithXanthic': (6, [((1,), 3)]),
			'pRenderLayerOverride': (5, [((-1,), 3)]),
			'pScarBaldnessCutoff': (0, [((0.5,), 3)]),
			'pScarBaldnessCutoffAlbino': (0, [((0.5,), 3)]),
			'pScarBaldnessCutoffErythristic': (0, [((0.5,), 3)]),
			'pScarBaldnessCutoffLeucistic': (0, [((0.5,), 3)]),
			'pScarBaldnessCutoffMelanistic': (0, [((0.5,), 3)]),
			'pScarBaldnessCutoffXanthic': (0, [((0.5,), 3)]),
			'pTransmissionColour': (2, [((0.05, 0.05, 0.05), 3)]),
			'pTransmissionFalloff': (0, [((0.6,), 3)]),
			'pTransmissionRoughness': (0, [((0.3,), 3)]),
			'pVerticalTiling': (0, [((0.25,), 3)]),
			'pWetRoughnessStrength': (0, [((0.6,), 3)]),
			'pWetRoughnessValue': (0, [((0.127,), 3)]),
			'pWetSpecularStrength': (0, [((0.5,), 3)]),
			'pWetSpecularValue': (0, [((0.02,), 3)]),
			'pWetnessYPositionLower': (0, [((0.3,), 2), ((0.05,), 1)]),
			'pWetnessYPositionUpper': (0, [((0.6,), 2), ((0.7,), 1)]),
			'pXanthicRoughnessMultiplier': (0, [((1.0,), 3)]),
			'pXanthicSpecularMultiplier': (0, [((1.0,), 3)]),
		}
	),
	'FurShell': (
		[
			'pAOTexture',
			'pAlbinoBaseColourAndMaskTexture',
			'pBaldnessScarTexture',
			'pBaseColourAndMaskTexture',
			'pErythristicBaseColourAndMaskTexture',
			'pLeucisticBaseColourAndMaskTexture',
			'pMarkingNoise',
			'pMarkingPatchworkMask',
			'pMelanisticBaseColourAndMaskTexture',
			'pNormalTexture',
			'pPiebaldMask',
			'pPiebaldTexture',
			'pRoughnessPackedTexture',
			'pScarClut',
			'pShellMap',
			'pTransmittanceTexture',
			'pXanthicBaseColourAndMaskTexture',
		],
		{
			'gAnisotropicStrength': (0, [((0.314,), 1), ((0.433,), 1), ((0.0,), 1)]),
			'gBendStretchScale': (0, [((0.2,), 3)]),
			'gDirectionScale': (0, [((1.73,), 2), ((1.0,), 1)]),
			'gFurExtension': (0, [((1.0,), 3)]),
			'gHeightStretchScale': (0, [((700.0,), 2), ((0.3,), 1)]),
			'gLodFade': (1, [((5.0, 10.0), 3)]),
			'gShellClumping': (0, [((0.5,), 2), ((0.4,), 1)]),
			'gShellUVStretchPower': (0, [((0.081,), 2), ((0.01,), 1)]),
			'gWetBrightness': (0, [((0.6,), 3)]),
			'gWetClumping': (0, [((0.5,), 3)]),
			'gWetFlattening': (0, [((0.7,), 3)]),
			'gWetHairBaseDirectionStrength': (0, [((0.2,), 2), ((1.0,), 1)]),
			'gWetHairDirectionStrength': (0, [((1.0,), 3)]),
			'gWetHairDownwardPush': (0, [((0.15,), 3)]),
			'pAOTexCoordIndex': (5, [((0,), 3)]),
			'pAlbinoRoughnessMultiplier': (0, [((1.0,), 3)]),
			'pAlbinoSpecularMultiplier': (0, [((1.0,), 3)]),
			'pAnimalIdentityMask': (5, [((1,), 3)]),
			'pAnisoNormalBend': (0, [((0.174,), 2), ((0.0,), 1)]),
			'pColourMask_HSLGenetic0': (2, [((0.505, 0.512, 0.52), 1), ((0.505, 0.513, 0.52), 1), ((0.512, 0.515, 0.53), 1)]),
			'pColourMask_HSLGenetic1': (2, [((0.345, 0.495, 0.5), 2), ((0.27, 0.5, 0.507), 1)]),
			'pColourMask_HSLGeneticAlbino0': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticAlbino1': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticErythristic0': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticErythristic1': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticLeucistic0': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticLeucistic1': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticMelanistic0': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticMelanistic1': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticXanthic0': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_HSLGeneticXanthic1': (2, [((0.5, 0.5, 0.5), 3)]),
			'pColourMask_NoiseContrast': (0, [((1.0,), 3)]),
			'pColourMask_NoiseThreshold': (0, [((0.0,), 3)]),
			'pCorpseTint': (2, [((0.5, 0.5, 0.5), 3)]),
			'pDiffuseTransmittance': (0, [((3.0,), 3)]),
			'pDirtDryColour': (2, [((0.056, 0.08, 0.13), 3)]),
			'pDirtWetColour': (2, [((0.045, 0.06, 0.09), 3)]),
			'pEnableScreenSpaceAO': (6, [((0,), 3)]),
			'pErythristicRoughnessMultiplier': (0, [((1.0,), 3)]),
			'pErythristicSpecularMultiplier': (0, [((1.0,), 3)]),
			'pFurAlbinoDepthScale': (0, [((1.2,), 1), ((1.5,), 1), ((1.058,), 1)]),
			'pFurDepthScale': (0, [((1.6,), 2), ((1.0,), 1)]),
			'pFurErythristicDepthScale': (0, [((0.715,), 3)]),
			'pFurLeucisticDepthScale': (0, [((0.715,), 3)]),
			'pFurMelanisticDepthScale': (0, [((0.715,), 3)]),
			'pFurXanthicDepthScale': (0, [((0.715,), 3)]),
			'pIBLRoughnessTweak': (0, [((1.0,), 2), ((0.249,), 1)]),
			'pLeucisticRoughnessMultiplier': (0, [((1.0,), 3)]),
			'pLeucisticSpecularMultiplier': (0, [((1.0,), 3)]),
			'pMarkingNoiseEnableRandomOffset': (6, [((1,), 3)]),
			'pMarkingNoiseScale': (0, [((0.1,), 3)]),
			'pMelanisticRoughnessMultiplier': (0, [((1.0,), 3)]),
			'pMelanisticSpecularMultiplier': (0, [((1.0,), 3)]),
			'pMipBias': (0, [((0.0,), 3)]),
			'pNoisiness': (0, [((0.55,), 3)]),
			'pPiebaldMarkingMipBias': (0, [((-1.0,), 3)]),
			'pPiebaldMarkingMorph': (5, [((0,), 3)]),
			'pPiebaldWithAlbino': (6, [((1,), 3)]),
			'pPiebaldWithErythristic': (6, [((1,), 3)]),
			'pPiebaldWithLeucistic': (6, [((1,), 3)]),
			'pPiebaldWithMelanistic': (6, [((1,), 3)]),
			'pPiebaldWithXanthic': (6, [((1,), 3)]),
			'pRenderLayerOverride': (5, [((-1,), 3)]),
			'pScarBaldnessCutoff': (0, [((0.5,), 3)]),
			'pScarBaldnessCutoffAlbino': (0, [((0.5,), 3)]),
			'pScarBaldnessCutoffErythristic': (0, [((0.5,), 3)]),
			'pScarBaldnessCutoffLeucistic': (0, [((0.5,), 3)]),
			'pScarBaldnessCutoffMelanistic': (0, [((0.5,), 3)]),
			'pScarBaldnessCutoffXanthic': (0, [((0.5,), 3)]),
			'pShellCorpseAlphaCut': (0, [((0.6,), 3)]),
			'pShellOpacity': (0, [((4.0,), 3)]),
			'pShellRimFade': (0, [((0.001,), 3)]),
			'pShellRimNudge': (0, [((0.0,), 3)]),
			'pShellSoftBlendEnabled': (6, [((0,), 3)]),
			'pShellTilingRate': (0, [((1.4,), 2), ((1.0,), 1)]),
			'pTransmissionColour': (2, [((0.05, 0.05, 0.05), 3)]),
			'pTransmissionFalloff': (0, [((0.2,), 3)]),
			'pTransmissionRoughness': (0, [((0.2,), 3)]),
			'pVerticalTiling': (0, [((0.25,), 3)]),
			'pWetRoughnessStrength': (0, [((0.6,), 2), ((0.259,), 1)]),
			'pWetRoughnessValue': (0, [((0.127,), 2), ((0.049,), 1)]),
			'pWetSpecularStrength': (0, [((0.5,), 2), ((0.043,), 1)]),
			'pWetSpecularValue': (0, [((0.02,), 3)]),
			'pWetnessYPositionLower': (0, [((0.3,), 2), ((0.05,), 1)]),
			'pWetnessYPositionUpper': (0, [((0.6,), 2), ((0.7,), 1)]),
			'pXanthicRoughnessMultiplier': (0, [((1.0,), 3)]),
			'pXanthicSpecularMultiplier': (0, [((1.0,), 3)]),
		}
	),
}
