texchannels = {
	# 'p2MarkingBaldnessScarTexture': {"R": "", "G": "", "B": "", "A": ""},
	# 'p3MarkingScarTexture': {"R": "", "G": "", "B": "", "A": ""},
	'pAOTexture': {"": "AO"},
	'pAOTexture2': {"": "AO2"},
	# 'pAOTextureDetail': {"": ""},
	# 'pAOTextureUnique': {"": ""},
	# 'pAlbedoAndRoughnessDetail': {"RGB": "", "A": ""},
	'pAlbinoBaseColourAndMaskTexture': {"RGB": "AB", "A": ""},  # ? Mask
	# 'pBaldnessScarTexture': {"R": "", "G": "", "B": "", "A": ""},
	# 'pBaseColour2': {"": ""},
	# 'pBaseColourAndMaskTexture': {"RGB": "BC", "A": ""},
	'pBaseColourTexture': {"RGB": "BC", "A": "CA"},  # A apparently not used on tree trunks in PZ
	'pBaseColourTexture2': {"RGB": "BC2", "A": "CA2"},
	# 'pBaseColourTextureDetail': {"RGB": "", "A": ""},
	# 'pBaseColourTextureDetailBase': {"RGB": "", "A": ""},
	# 'pBaseColourTextureDetailBlend': {"RGB": "", "A": ""},
	# 'pBaseColourTextureUnique': {"RGB": "", "A": ""},
	# 'pBaseDielectricSpecularLevelTexture': {"": ""},
	# 'pBaseNormalTexture': {"RG": "", "B": "", "A": ""},
	# 'pCavityRoughnessDielectricArray': {"R": "", "G": "", "B": "", "A": ""},
	# 'pClipMap2': {"": ""},
	# 'pClut': {"": ""},
	# 'pCoarseNoise': {"": ""},
	# 'pDamageBlendMap': {"": ""},
	# 'pDetailMask': {"": ""},
	# 'pDetailNormalTexture': {"": ""},
	# 'pDetailRoughnessTexture': {"": ""},
	'pDiffuse': {"": "BC"},
	'pDiffuseAlbino': {"": "AB"},
	# 'pDiffuseArray': {"": ""},
	'pDiffuseErythristic': {"": "ER"},
	'pDiffuseLeucistic': {"": "LE"},
	'pDiffuseMelanistic': {"": "ME"},
	'pDiffuseTexture': {"": "BC"},
	'pDiffuseXanthic': {"": "XA"},
	# 'pDistortionTexture': {"": ""},
	# 'pEmissiveMaskTexture': {"": ""},
	'pEmissiveTexture': {"": "EM"},
	'pErythristicBaseColourAndMaskTexture': {"RGB": "ER", "A": ""},  # ? Mask
	'pFinAlphaTexture': {"R": "OP", "G": "OP", "B": "OP", "A": "OP"},
	# 'pFlexiColourMaskTexture': {"": ""},
	'pFlexiColourMasksTexture': {"R": "F1", "G": "F2", "B": "F3", "A": "F4"},
	# 'pFlexiColourMasterMask': {"": ""},
	# 'pGradHeightArray': {"RG": "", "B": "", "A": ""},
	# 'pHeight': {"": ""},
	# 'pIridescenceStrength': {"": ""},
	# 'pIridescenceTexture': {"": ""},
	'pLeucisticBaseColourAndMaskTexture': {"RGB": "LE", "A": ""},  # ? Mask
	# 'pMacroDamageBlendMap': {"": ""},
	# 'pMacroDiffuse': {"": ""},
	# 'pMarkingNoise': {"": ""},
	# 'pMarkingPatchworkMask': {"": ""},
	# 'pMaskAOTextureUnique': {"": ""},
	'pMelanisticBaseColourAndMaskTexture': {"RGB": "ME", "A": ""},  # ? Mask
	# 'pMossBaseColourRoughnessPackedTexture': {"RGB": "", "A": ""},
	# 'pMossNormalTexture': {"": ""},
	# 'pMossVarianceTexture': {"": ""},
	# 'pNormalBlendWeightTexture': {"": ""},
	# 'pNormalMapTextureUnique': {"": ""},
	'pNormalTexture': {"RG": "NM"},
	'pNormalTexture2': {"RG": "NM2"},
	# 'pNormalTextureDetail': {"RGB": "", "A": ""},
	# 'pNormalTextureDetailBase': {"RGB": "", "A": ""},
	# 'pNormalTextureDetailBlend': {"RGB": "", "A": ""},
	# 'pNormalTextureUnique': {"RGB": "", "A": ""},
	'pOpacityTexture': {"": "OP"},
	'pOpacityTexture2': {"": "OP2"},
	# 'pPiebaldMask': {"": ""},
	# 'pPiebaldTexture': {"R": "", "G": "", "B": "", "A": ""},
	# 'pPropertyTexture': {"": ""},
	# 'pRetroreflectiveness': {"": ""},
	# 'pRoughnessAOPackedTextureDetailBase': {"R": "", "G": "", "B": "", "A": ""},
	"pRoughnessPackedTexture": {"R": "MT", "G": "SP", "B": "RN", "A": "OP"},
	# 'pRoughnessPackedTexture2': {"R": "", "G": "", "B": "", "A": ""},
	# 'pRoughnessPackedTextureDetail': {"R": "", "G": "", "B": "", "A": ""},
	# 'pRoughnessPackedTextureUnique': {"R": "", "G": "", "B": "", "A": ""},
	# 'pScarClut': {"": ""},
	# 'pShellMap': {"R": "", "G": "", "B": "", "A": ""},
	# 'pSkirtMaterialMask': {"": ""},
	# 'pSkirtNormals': {"": ""},
	# 'pSubLayerDiffuse0Texture': {"": ""},
	# 'pSubLayerDiffuse1Texture': {"": ""},
	# 'pThicknessTexture': {"": ""},
	# 'pTransmittancePackedTexture': {"R": "", "G": "", "B": "", "A": ""},
	# 'pTransmittanceTexture': {"": ""},
	# 'pWaterDetailNormalTexture': {"": ""},
	# 'pWaterDetailRoughnessTexture': {"": ""},
	# 'pWaterfall_WaterFlowAndTimeOffsetMap': {"": ""},
	# 'pWaterfall_WaterFoamMaskMap': {"": ""},
	# 'pWaterfall_WaterNormalRoughnessMap': {"": ""},
	'pXanthicBaseColourAndMaskTexture': {"RGB": "XA", "A": ""},  # ? Mask
}
