texchannels = {
	'pAOTexture': {"": "AO"},
	'pAlphaTexture': {"": "OP"},
	'pBaseAOTexture': {
		"R": "AO", "G": "BA",  # BC5
		"": "AO"  # BC4
		},
	# 'pBaseColour2Texture': {"RGB": "", "A": ""},
	'pBaseColourTexture': {"RGB": "BC", "A": "CA"},  # check if A is used here  # Metallic_Roughness_Clip A = OP
	'pBaseColourTextureDetailBase': {"RGB": "DE_BC", "A": ""},
	'pBaseColourTextureDetailBlend': {"RGB": "BL_BC", "A": ""},  # Overlaid on pBaseColourTextureDetailBase
	# 'pBaseDielectricSpecularLevelTexture': {"": ""},
	'pBaseDiffuseTexture': {"": "BC"},
	'pBaseNormalTexture': {"RG": "NM", "B": "SP", "A": "RN"},
	# 'pBaseTransmissionTexture': {"": ""},
	# 'pCavityRoughnessDielectricArray': {"R": "", "G": "", "B": "", "A": ""},
	# 'pCustomisation_AOTexture': {"": ""},
	# 'pCustomisation_Channel1PatternTexture': {"": ""},
	# 'pCustomisation_Channel2PatternTexture': {"": ""},
	# 'pCustomisation_Channel3PatternTexture': {"": ""},
	# 'pCustomisation_Channel4PatternTexture': {"": ""},
	# 'pCustomisation_ChannelMasksAndValueTexture': {"": ""},
	# 'pCustomisation_ChannelMasksTexture': {"": ""},
	# 'pCustomisation_HSVOffsetTexture': {"": ""},
	# 'pCustomisation_MasterMaskTexture': {"": ""},
	# 'pCustomisation_Value2Texture': {"": ""},
	# 'pCustomisation_ValueTexture': {"": ""},
	# 'pDetailNormalTexture': {"": ""},
	# 'pDetailRoughnessTexture': {"": ""},
	'pDiffuseAlphaTexture': {"RGB": "BC", "A": "OP"},
	# 'pDiffuseArray': {"": ""},
	'pDiffuseTexture': {"": "BC"},
	'pDinosaurFeathers_BaseDiffuseTexture': {"": "BC"},
	'pEmissiveTexture': {"": "EM"},
	# 'pEnvironmentalNoiseMask': {"": ""},
	'pFeathersBaseDiffuseTexture': {"": "BC"},
	'pFeathers_AOHeightOpacityTransmission_PackedTexture': {"R": "AO", "G": "HE", "B": "OP", "A": "TR"},
	# 'pFeathers_Aniso_PackedTexture': {"R": "", "G": "", "B": "", "A": ""},
	'pFeathers_BaseColourTexture': {"": "DE"},
	'pFeathers_EmissiveTexture': {"": "EM"},
	'pFeathers_NormalTexture': {"RG": "NM"},
	'pFeathers_RoughnessPackedTexture': {"R": "MT", "G": "RN", "B": "SP", "A": ""},  # unsure about A
	'pFinAlphaTexture': {"R": "OP", "G": "OP", "B": "OP", "A": "OP"},
	'pFlexiColourMasksTexture': {"R": "F1", "G": "F2", "B": "F3", "A": "F4"},
	# 'pFoamMapTexture': {"": ""},
	# 'pFoamScrollMapTexture': {"": ""},
	# 'pFoamyAreasDistantMap': {"": ""},
	# 'pFullScaleDiffuseAndSpecial': {"": ""},
	# 'pGradHeightArray': {"RG": "", "B": "", "A": ""},
	'pHeightTexture': {"": "HE"},
	# 'pHyperloops_AlphaEmissiveMaskTexture': {"": ""},
	# 'pHyperloops_DiffuseTexture': {"": ""},
	'pIridescenceMaskTexture': {"": "IM"},  # used on UV1 for feathers
	'pIridescenceTexture': {"": "IR"},  # a LUT for reflection coordinates
	'pLayered_BlendWeights': {"R": "M0", "G": "M1", "B": "M2", "A": "M3"},
	# 'pLayered_DiffuseTexture': {"R": "", "G": "", "B": "", "A": ""},
	# 'pLayered_HeightTexture': {"R": "", "G": "", "B": "", "A": ""},
	# 'pLayered_PackedTexture': {"R": "", "G": "", "B": "", "A": ""},
	# 'pLayered_RemapTexture': {"R": "", "G": "", "B": "", "A": ""},
	# 'pLayered_WarpOffset': {"": ""},
	# 'pMacroDiffuse': {"": ""},
	# 'pModelViewer_GridPatternMap': {"": ""},
	# 'pMoiseNoiseMask': {"": ""},
	# 'pMossBaseColour': {"": ""},
	# 'pMossBaseColourRoughnessPackedTexture': {"RGB": "", "A": ""},
	# 'pMossNormalTexture': {"": ""},
	# 'pMossVarianceTexture': {"": ""},
	# 'pNormal2Texture': {"": ""},
	'pNormalMapTextureUnique': {"RG": "NQ_NM", "B": "DM", "A": "NQ_AO"},
	'pNormalTexture': {"RGB": "NM", "A": "AO"},  # BC7_UNORM - no coord dropping? not sure if A is actually always AO
	'pNormalTextureDetailBase': {"RG": "DE_NM", "B": "DE_RN", "A": "DE_AO"},  # Overlaid on pNormalMapTextureUnique
	'pNormalTextureDetailBlend': {"RG": "BL_NM"},  # Overlaid on pNormalTextureDetailBase
	# 'pOpacity2': {"": ""},
	'pOpacityTexture': {"": "OP"},
	# 'pPackedTexture': {"RGB": "", "A": ""},
	# 'pPatchBlendMap': {"": ""},
	# 'pPatterning_FeathersPatchworkGradientMap': {"": ""},
	# 'pPatterning_FeathersPatternGradientMap': {"": ""},
	# 'pPatterning_PatchworkGradientMap': {"": ""},
	# 'pPatterning_PatternGradientMap': {"": ""},
	# 'pPrimaryBlendMap': {"": ""},
	# 'pProjection_BackgroundPlaneEmissiveTexture': {"": ""},
	# 'pProjection_DiffuseTexture': {"": ""},
	# 'pProjection_EmissiveTexture': {"": ""},
	# 'pProjection_ForegroundPlaneDiffuseTexture': {"": ""},
	# 'pProjection_ForegroundPlaneEmissiveTexture': {"": ""},
	# 'pProjection_Plane0Texture': {"": ""},
	# 'pProjection_Plane1Texture': {"": ""},
	# 'pProjection_Plane2Texture': {"": ""},
	# 'pProjection_Texture': {"": ""},
	# 'pRemapTexture': {"": ""},
	# 'pRoughnessPacked2Texture': {"": ""},
	'pRoughnessPackedTexture': {"R": "MT", "G": "SP", "B": "RN", "A": "FO"},  # Metallic_Roughness_Clip_Geometry_Decal A = OP
	'pRoughnessTexture': {"": "RN"},
	# 'pShellMap': {"R": "", "G": "", "B": "", "A": ""},
	'pSpecularTexture': {"": "SP"},
	# 'pSubLayerDiffuse0Texture': {"": ""},
	# 'pSubLayerDiffuse1Texture': {"": ""},
	# 'pThicknessTexture': {"": ""},
	# 'pTransmissionTexture': {"": ""},
	# 'pWaterBottomHeight': {"": ""},
	# 'pWaterDetailGradientMap': {"": ""},
	# 'pWaterDetailHeightMap': {"": ""},
	# 'pWaterDetailNormalMapTexture': {"": ""},
	# 'pWaterDetailSpecMapTexture': {"": ""},
	# 'pWaterNormalMapTexture': {"": ""},
	# 'pWaterRipplesTexture': {"": ""},
	# 'pWaterRoughnessMapTexture': {"": ""},
	# 'pWaterfall_BaseWaterNormalRoughnessMap': {"RGB": "", "A": ""},
	# 'pWaterfall_FlowWaterFoamMaskMap': {"R": "", "G": "", "B": "", "A": ""},
	# 'pWaterfall_FlowWaterNormalRoughnessMap': {"RGB": "", "A": ""},
	# 'pWaterfall_FlowWaterTurbulanceMap1': {"": ""},
	# 'pWaterfall_FlowWaterTurbulanceMap2': {"": ""},
	# 'pWaterfall_MasksMap': {"": ""},
	# 'pWaterfall_NoiseMap': {"": ""},
	# 'pWaterfall_WaterTimeOffsetMap': {"": ""},
	# 'u_basePatchworkMap': {"": ""},
	# 'u_basePatternMap': {"": ""},
	# 'u_feathersBasePatchworkMap': {"": ""},
	# 'u_feathersBasePatternMap': {"": ""},
}
