texchannels = {
	'pAOTexture': {"": "AO"},
	'pBaseColourTexture': {"RGB": "BC", "A": ""},  # unsure about A
	'pBaseDiffuseTexture': {"": "BC"},
	'pBasePackedTexture': {"R": "", "G": "", "B": "MT", "A": "AO"},  # unsure about rest
	# 'pBase_AOTexture': {"": ""},
	# 'pBase_BaseColourTexture': {"": ""},
	# 'pBase_NormalTexture': {"": ""},
	# 'pBase_RoughnessPackedTexture': {"R": "", "G": "", "B": "", "A": ""},
	# 'pCavityRoughnessArray': {"": ""},
	# 'pCoarseNoise': {"": ""},
	# 'pDetailTexture': {"": ""},
	# 'pDiffuseAlphaTexture': {"RGB": "", "A": ""},
	# 'pDiffuseArray': {"": ""},
	# 'pDiffuseTexture': {"RGB": "", "A": ""},
	# 'pEmissiveTexture': {"": ""},
	# 'pFlexiColourMasksTexture': {"R": "", "G": "", "B": "", "A": ""},
	# 'pFoamMapTexture': {"": ""},
	# 'pFoamyAreasDistantMap': {"": ""},
	# 'pGradHeightArray': {"RG": "", "B": "", "A": ""},
	'pHeightTexture': {"": "HE"},
	# 'pLayered_BaseColourTexture': {"": ""},
	'pLayered_BlendWeights': {"R": "M0", "G": "M1", "B": "M2", "A": "M3"},
	# 'pLayered_HeightTexture': {"R": "", "G": "", "B": "", "A": ""},
	# 'pLayered_PackedTexture': {"R": "", "G": "", "B": "", "A": ""},
	# 'pLayered_WarpOffset': {"": ""},
	# 'pMacroDiffuse': {"": ""},
	# 'pNoiseTexture': {"": ""},
	# 'pNormalBlendWeightTexture': {"": ""},
	'pNormalTexture': {"RG": "NM", "RGB": "NM", "A": ""},  # unsure about A
	# 'pOpacityTexture': {"": ""},
	# 'pPackedTexture': {"RGB": "", "A": ""},
	# 'pPatchBlendMap': {"": ""},
	# 'pPrimaryBlendMap': {"": ""},
	# 'pProjection_Plane0Texture': {"": ""},
	# 'pProjection_Plane1Texture': {"": ""},
	# 'pProjection_Plane2Texture': {"": ""},
	# 'pProjection_Texture': {"": ""},
	# 'pRoughnessPackedTexture': {"R": "", "G": "", "B": "", "A": ""},
	# 'pRoughnessTexture': {"": ""},
	# 'pSkirtNormals': {"": ""},
	# 'pSpecularArray': {"": ""},
	'pSpecularTexture': {"": "SP"},
	# 'pTransmissionTexture': {"": ""},
	# 'pWaterDetailNormalMapTexture': {"": ""},
	# 'pWaterDetailSpecMapTexture': {"": ""},
}
