
from typing import Any, ClassVar, Iterator, Callable, TypeVar, Generator, ContextManager
import xml.etree.ElementTree as ET
from generated.context import ContextReference

TBaseStruct = TypeVar('TBaseStruct', bound='BaseStruct')

class StructMetaClass(type): ...

class BaseStruct(metaclass=StructMetaClass):
    context: ClassVar[ContextReference]
    _attribute_list: ClassVar[tuple]
    allow_np: ClassVar[bool]

    name: str
    _context: ContextReference
    arg: Any
    template: Any
    io_size: int
    io_start: int

    def __init__(self, context: Any, arg: Any = 0, template: Any = None, set_default: bool = True) -> None: ...
    def set_defaults(self) -> None: ...

    @classmethod
    def get_fields_str(cls, instance: 'BaseStruct', indent: int = 0) -> str: ...
    @classmethod
    def get_field_names(cls, instance: 'BaseStruct') -> set[str]: ...
    @classmethod
    def format_indented(cls, instance: 'BaseStruct', indent: int = 0) -> str: ...
    def get_info_str(self, indent: int = 0) -> str: ...

    @classmethod
    def from_xml_file(cls: type[TBaseStruct], file_path: str, context: Any, arg: Any = 0, template: Any = None) -> TBaseStruct: ...
    @classmethod
    def from_xml(cls: type[TBaseStruct], target: Any, elem: ET.Element, prop: str, arg: Any, template: Any) -> TBaseStruct | None: ...
    @classmethod
    def _from_xml(cls, instance: 'BaseStruct', elem: ET.Element) -> 'BaseStruct': ...
    @classmethod
    def to_xml_file(cls, instance: 'BaseStruct', file_path: str, debug: bool = False) -> ContextManager[ET.Element]: ...
    @classmethod
    def to_xml(cls, elem: ET.Element, prop: str, instance: 'BaseStruct', arg: Any, template: Any, debug: bool) -> None: ...
    @classmethod
    def is_array_count(cls, f_name: str, set_fields: set[str]) -> bool: ...
    @classmethod
    def _to_xml(cls, instance: 'BaseStruct', elem: ET.Element, debug: bool) -> None: ...

    @classmethod
    def read_fields(cls, stream: Any, instance: 'BaseStruct') -> None: ...
    @classmethod
    def write_fields(cls, stream: Any, instance: 'BaseStruct') -> None: ...

    def set_context(self, context: Any) -> None: ...
    def reset_field(self, target_f_name: str) -> Any: ...

    @classmethod
    def validate_instance(cls, instance: 'BaseStruct', context: Any, arg: Any, template: Any) -> None: ...
    @classmethod
    def init_attributes(cls) -> None: ...
    @classmethod
    def _get_attribute_list(cls) -> Generator[Any, None, None]: ...
    @classmethod
    def _get_filtered_attribute_list(cls, instance: 'BaseStruct', include_abstract: bool = True) -> Generator[Any, None, None]: ...

    @classmethod
    def get_conditioned_attributes(cls, struct_type: Any, struct_instance: Any, condition_function: Callable, arguments: tuple = (), include_abstract: bool = True) -> Generator[Any, None, None]: ...
    @classmethod
    def get_condition_attributes_recursive(cls, struct_type: Any, struct_instance: Any, condition_function: Callable, arguments: tuple = (), include_abstract: bool = True, enter_condition: Callable = ...) -> Generator[Any, None, None]: ...
    def get_condition_fields(self, condition_function: Callable, include_abstract: bool = True, enter_condition: Callable = ...) -> Generator[Any, None, None]: ...
    @classmethod
    def get_condition_values_recursive(cls, instance: 'BaseStruct', condition_function: Callable, arguments: tuple = (), include_abstract: bool = True, enter_condition: Callable = ...) -> Generator[Any, None, None]: ...

    @staticmethod
    def get_field(instance: 'BaseStruct', key: str) -> Any: ...
    @classmethod
    def set_field(cls, instance: 'BaseStruct', key: str, value: Any) -> None: ...
    @classmethod
    def get_size(cls, instance: 'BaseStruct', context: Any, arg: Any = 0, template: Any = None) -> int: ...

    @classmethod
    def from_stream(cls: type[TBaseStruct], stream: Any, context: Any, arg: Any = 0, template: Any = None) -> TBaseStruct: ...
    @classmethod
    def to_stream(cls: type[TBaseStruct], instance: TBaseStruct, stream: Any, context: Any, arg: Any = 0, template: Any = None) -> TBaseStruct: ...

    @classmethod
    def get_np_sig(cls, instance: 'BaseStruct') -> tuple[type, list[tuple[str, Any]]]: ...
    @classmethod
    def get_np_dtype(cls, context: Any, arg: Any = 0, template: Any = None) -> Any: ...

    # --- DYNAMIC METHODS ADDED BY init_attributes() ---
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __getitem__(self, key: int) -> Any: ...
    def __setitem__(self, key: int, value: Any) -> None: ...
    @classmethod
    def from_value(cls: type[TBaseStruct], value: Any) -> TBaseStruct: ...
    @classmethod
    def create_array(cls, shape: Any, default: Any = None, context: Any = None, arg: Any = 0, template: Any = None) -> Any: ...
    @classmethod
    def read_array(cls, stream: Any, shape: Any, context: Any = None, arg: Any = 0, template: Any = None) -> Any: ...
    @classmethod
    def write_array(cls, instance: Any, stream: Any) -> None: ...
