name: Run Pytest

on:
  push:
    paths-ignore:
      - .gitignore
      - .vscode/**
      - .idea/**
      - README.md
      - __version__.py
  pull_request:

jobs:
  run-pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ["3.11"]

    steps:  
      - uses: actions/checkout@v3
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[gui,dev,manis_tool_gui]
      - name: Install GitHub plugins
        run: |
          pip install pytest-github-actions-annotate-failures
      - name: Run Tests
        run: pytest

  run-pytest-verbose:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ["3.11"]

    steps:  
      - uses: actions/checkout@v3
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[gui,dev]
      - name: Run Tests
        run: pytest --verbose -o log_cli=true
      - name: Get APPDATA
        run: echo ("APPDATA_TEMP=" + $env:LOCALAPPDATA + "\Temp") >> $env:GITHUB_ENV
      - name: Upload Temp
        uses: actions/upload-artifact@v4
        with:
          name: pytest-tmp
          path: |
            ${{ env.APPDATA_TEMP }}/pytest**
      - name: Upload Log
        uses: actions/upload-artifact@v4
        with:
          name: pytest-log
          path: |
            ${{ github.workspace }}/logs/pytest.log
